/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appsCreateApp } from "../funcs/apps-create-app.js";
import { appsDeleteApp } from "../funcs/apps-delete-app.js";
import { appsDuplicate } from "../funcs/apps-duplicate.js";
import { appsGetAppVersion } from "../funcs/apps-get-app-version.js";
import { appsGetAppViewStats } from "../funcs/apps-get-app-view-stats.js";
import { appsGetDBSchema } from "../funcs/apps-get-db-schema.js";
import { appsGetDBTablePreview } from "../funcs/apps-get-db-table-preview.js";
import { appsGetMemberState } from "../funcs/apps-get-member-state.js";
import { appsGetMembersWithApps } from "../funcs/apps-get-members-with-apps.js";
import { appsGet } from "../funcs/apps-get.js";
import { appsHeartbeat } from "../funcs/apps-heartbeat.js";
import { appsInvokeComputeFunction } from "../funcs/apps-invoke-compute-function.js";
import { appsListActivitySince } from "../funcs/apps-list-activity-since.js";
import { appsListMyMemberActivity } from "../funcs/apps-list-my-member-activity.js";
import { appsListVersions } from "../funcs/apps-list-versions.js";
import { appsList } from "../funcs/apps-list.js";
import { appsMoveAppToFolder } from "../funcs/apps-move-app-to-folder.js";
import { appsPresenceHeartbeat } from "../funcs/apps-presence-heartbeat.js";
import { appsRecordMemberActivity } from "../funcs/apps-record-member-activity.js";
import { appsRefresh } from "../funcs/apps-refresh.js";
import { appsRestoreAppVersion } from "../funcs/apps-restore-app-version.js";
import { appsSetFavorite } from "../funcs/apps-set-favorite.js";
import { appsSetMemberState } from "../funcs/apps-set-member-state.js";
import { appsUpdate } from "../funcs/apps-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Apps extends ClientSDK {
  /**
   * Keeps the viewed app's compute worker alive; first view spawns and pre-warms it (dashboard viewer-TTL parity).
   *
   * @remarks
   * Keeps the viewed app's compute worker alive; first view spawns and pre-warms it (dashboard viewer-TTL parity).
   */
  async heartbeat(
    request: operations.AppServiceAppHeartbeatRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceAppHeartbeatResponse> {
    return unwrapAsync(appsHeartbeat(
      this,
      request,
      options,
    ));
  }

  /**
   * CreateApp
   */
  async createApp(
    request: operations.AppServiceCreateAppRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceCreateAppResponse> {
    return unwrapAsync(appsCreateApp(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteApp
   */
  async deleteApp(
    request: operations.AppServiceDeleteAppRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceDeleteAppResponse> {
    return unwrapAsync(appsDeleteApp(
      this,
      request,
      options,
    ));
  }

  /**
   * Duplicates an app the caller can view into a new app they own,  named "Copy of <name>". Copies code/files/data sources/compute functions/  schedule; never carries over the source's data snapshot.
   *
   * @remarks
   * Duplicates an app the caller can view into a new app they own,
   *  named "Copy of <name>". Copies code/files/data sources/compute functions/
   *  schedule; never carries over the source's data snapshot.
   */
  async duplicate(
    request: operations.AppServiceDuplicateAppRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceDuplicateAppResponse> {
    return unwrapAsync(appsDuplicate(
      this,
      request,
      options,
    ));
  }

  /**
   * GetApp
   */
  async get(
    request: operations.AppServiceGetAppRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetAppResponse> {
    return unwrapAsync(appsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * GetAppDBSchema
   */
  async getDBSchema(
    request: operations.AppServiceGetAppDBSchemaRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetAppDBSchemaResponse> {
    return unwrapAsync(appsGetDBSchema(
      this,
      request,
      options,
    ));
  }

  /**
   * Cross-member live activity: rows from every member of the app after a seq,  each carrying member_id + display_name (resolved server-side; never email).
   *
   * @remarks
   * Cross-member live activity: rows from every member of the app after a seq,
   *  each carrying member_id + display_name (resolved server-side; never email).
   */
  async getDBTablePreview(
    request: operations.AppServiceGetAppDBTablePreviewRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetAppDBTablePreviewResponse> {
    return unwrapAsync(appsGetDBTablePreview(
      this,
      request,
      options,
    ));
  }

  /**
   * Ordering overlay for the sidebar Bookmarks section: one position list per  member covering favorites and thread bookmarks ('<kind>:<id>' keys).  Membership truth stays in library_favorite / chat bookmarks; this persists  only the drag-and-drop order.
   *
   * @remarks
   * Ordering overlay for the sidebar Bookmarks section: one position list per
   *  member covering favorites and thread bookmarks ('<kind>:<id>' keys).
   *  Membership truth stays in library_favorite / chat bookmarks; this persists
   *  only the drag-and-drop order.
   */
  async getMemberState(
    request: operations.AppServiceGetAppMemberStateRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetAppMemberStateResponse> {
    return unwrapAsync(appsGetMemberState(
      this,
      request,
      options,
    ));
  }

  /**
   * GetAppVersion
   */
  async getAppVersion(
    request: operations.AppServiceGetAppVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetAppVersionResponse> {
    return unwrapAsync(appsGetAppVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Lists the calling member's favorited library items (apps, dashboards,  agents) for the sidebar Pinned section: id, type, name, preview screenshot.
   *
   * @remarks
   * Lists the calling member's favorited library items (apps, dashboards,
   *  agents) for the sidebar Pinned section: id, type, name, preview screenshot.
   */
  async getAppViewStats(
    request: operations.AppServiceGetAppViewStatsRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetAppViewStatsResponse> {
    return unwrapAsync(appsGetAppViewStats(
      this,
      request,
      options,
    ));
  }

  /**
   * GetMembersWithApps
   */
  async getMembersWithApps(
    request: operations.AppServiceGetMembersWithAppsRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceGetMembersWithAppsResponse> {
    return unwrapAsync(appsGetMembersWithApps(
      this,
      request,
      options,
    ));
  }

  /**
   * Executes a declared compute function on a pooled sandbox worker; gated, org-scoped, rate-limited.
   *
   * @remarks
   * Executes a declared compute function on a pooled sandbox worker; gated, org-scoped, rate-limited.
   */
  async invokeComputeFunction(
    request: operations.AppServiceInvokeAppComputeFunctionRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceInvokeAppComputeFunctionResponse> {
    return unwrapAsync(appsInvokeComputeFunction(
      this,
      request,
      options,
    ));
  }

  /**
   * Per-member app state: one JSON blob per (app, member) so apps remember  settings/progress. Member always resolved server-side from auth context;  per-member persistence, so viewers with read access can save their own state.
   *
   * @remarks
   * Per-member app state: one JSON blob per (app, member) so apps remember
   *  settings/progress. Member always resolved server-side from auth context;
   *  per-member persistence, so viewers with read access can save their own state.
   */
  async listActivitySince(
    request: operations.AppServiceListAppActivitySinceRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceListAppActivitySinceResponse> {
    return unwrapAsync(appsListActivitySince(
      this,
      request,
      options,
    ));
  }

  /**
   * Version history: git-backed, one version per save (plus legacy publish-era snapshots); authors can list and restore.
   *
   * @remarks
   * Version history: git-backed, one version per save (plus legacy publish-era snapshots); authors can list and restore.
   */
  async listVersions(
    request: operations.AppServiceListAppVersionsRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceListAppVersionsResponse> {
    return unwrapAsync(appsListVersions(
      this,
      request,
      options,
    ));
  }

  /**
   * ListApps
   */
  async list(
    request: operations.AppServiceListAppsRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceListAppsResponse> {
    return unwrapAsync(appsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Staff-only (superadmin gated in-handler): publishes the embedded component  gallery as an app tree and returns its signed viewer URL.
   *
   * @remarks
   * Staff-only (superadmin gated in-handler): publishes the embedded component
   *  gallery as an app tree and returns its signed viewer URL.
   */
  async listMyMemberActivity(
    request: operations.AppServiceListMyAppMemberActivityRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceListMyAppMemberActivityResponse> {
    return unwrapAsync(appsListMyMemberActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * Moves an app into a library folder (or to root when folder_id is empty).
   *
   * @remarks
   * Moves an app into a library folder (or to root when folder_id is empty).
   */
  async moveAppToFolder(
    request: operations.AppServiceMoveAppToFolderRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceMoveAppToFolderResponse> {
    return unwrapAsync(appsMoveAppToFolder(
      this,
      request,
      options,
    ));
  }

  /**
   * Append-only per-member activity log. Listing is own rows only; no  cross-member reads in this release.
   *
   * @remarks
   * Append-only per-member activity log. Listing is own rows only; no
   *  cross-member reads in this release.
   */
  async presenceHeartbeat(
    request: operations.AppServicePresenceHeartbeatRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServicePresenceHeartbeatResponse> {
    return unwrapAsync(appsPresenceHeartbeat(
      this,
      request,
      options,
    ));
  }

  /**
   * View analytics: reads the engagement views recorded on app page load.
   *
   * @remarks
   * View analytics: reads the engagement views recorded on app page load.
   */
  async recordMemberActivity(
    request: operations.AppServiceRecordAppMemberActivityRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceRecordAppMemberActivityResponse> {
    return unwrapAsync(appsRecordMemberActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * Re-fetches data sources, rebuilds the document with a fresh snapshot, re-uploads.
   *
   * @remarks
   * Re-fetches data sources, rebuilds the document with a fresh snapshot, re-uploads.
   */
  async refresh(
    request: operations.AppServiceRefreshAppRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceRefreshAppResponse> {
    return unwrapAsync(appsRefresh(
      this,
      request,
      options,
    ));
  }

  /**
   * RestoreAppVersion
   */
  async restoreAppVersion(
    request: operations.AppServiceRestoreAppVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceRestoreAppVersionResponse> {
    return unwrapAsync(appsRestoreAppVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Replaces the calling member's entire ordering; capped server-side.
   *
   * @remarks
   * Replaces the calling member's entire ordering; capped server-side.
   */
  async setMemberState(
    request: operations.AppServiceSetAppMemberStateRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceSetAppMemberStateResponse> {
    return unwrapAsync(appsSetMemberState(
      this,
      request,
      options,
    ));
  }

  /**
   * Favorite/unfavorite a library item (app or dashboard) for the calling member.  Per-member, per-org; favorited=false hard-deletes the row. Covers both primitives  since the merged library page pins apps and dashboards through one client.
   *
   * @remarks
   * Favorite/unfavorite a library item (app or dashboard) for the calling member.
   *  Per-member, per-org; favorited=false hard-deletes the row. Covers both primitives
   *  since the merged library page pins apps and dashboards through one client.
   */
  async setFavorite(
    request: operations.AppServiceSetFavoriteRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceSetFavoriteResponse> {
    return unwrapAsync(appsSetFavorite(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateApp
   */
  async update(
    request: operations.AppServiceUpdateAppRequest,
    options?: RequestOptions,
  ): Promise<operations.AppServiceUpdateAppResponse> {
    return unwrapAsync(appsUpdate(
      this,
      request,
      options,
    ));
  }
}
