/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsExportsConfigure } from "../funcs/metrics-exports-configure.js";
import { metricsExportsDeleteConfig } from "../funcs/metrics-exports-delete-config.js";
import { metricsExportsGetMetricsExportConfig } from "../funcs/metrics-exports-get-metrics-export-config.js";
import { metricsExportsTestConnection } from "../funcs/metrics-exports-test-connection.js";
import { metricsExportsTriggerPush } from "../funcs/metrics-exports-trigger-push.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class MetricsExports extends ClientSDK {
  /**
   * ConfigureMetricsExport
   */
  async configure(
    request: operations.MetricsExportServiceConfigureMetricsExportRequest,
    options?: RequestOptions,
  ): Promise<operations.MetricsExportServiceConfigureMetricsExportResponse> {
    return unwrapAsync(metricsExportsConfigure(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteMetricsExportConfig
   */
  async deleteConfig(
    request: operations.MetricsExportServiceDeleteMetricsExportConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.MetricsExportServiceDeleteMetricsExportConfigResponse> {
    return unwrapAsync(metricsExportsDeleteConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * GetMetricsExportConfig
   */
  async getMetricsExportConfig(
    request: operations.MetricsExportServiceGetMetricsExportConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.MetricsExportServiceGetMetricsExportConfigResponse> {
    return unwrapAsync(metricsExportsGetMetricsExportConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * TestMetricsExportConnection
   */
  async testConnection(
    request: operations.MetricsExportServiceTestMetricsExportConnectionRequest,
    options?: RequestOptions,
  ): Promise<
    operations.MetricsExportServiceTestMetricsExportConnectionResponse
  > {
    return unwrapAsync(metricsExportsTestConnection(
      this,
      request,
      options,
    ));
  }

  /**
   * TriggerMetricsPush
   */
  async triggerPush(
    request: operations.MetricsExportServiceTriggerMetricsPushRequest,
    options?: RequestOptions,
  ): Promise<operations.MetricsExportServiceTriggerMetricsPushResponse> {
    return unwrapAsync(metricsExportsTriggerPush(
      this,
      request,
      options,
    ));
  }
}
