/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rbacApproveAccessRequest } from "../funcs/rbac-approve-access-request.js";
import { rbacAssignPermissionToRole } from "../funcs/rbac-assign-permission-to-role.js";
import { rbacAssignRoleToMember } from "../funcs/rbac-assign-role-to-member.js";
import { rbacCreateApiKey } from "../funcs/rbac-create-api-key.js";
import { rbacCreateImportUpload } from "../funcs/rbac-create-import-upload.js";
import { rbacCreatePersonalApiKey } from "../funcs/rbac-create-personal-api-key.js";
import { rbacCreateRole } from "../funcs/rbac-create-role.js";
import { rbacCreateServiceAccountApiKey } from "../funcs/rbac-create-service-account-api-key.js";
import { rbacCreateServiceAccount } from "../funcs/rbac-create-service-account.js";
import { rbacDeleteRole } from "../funcs/rbac-delete-role.js";
import { rbacDeleteServiceAccount } from "../funcs/rbac-delete-service-account.js";
import { rbacExportRoles } from "../funcs/rbac-export-roles.js";
import { rbacGenerateShareLink } from "../funcs/rbac-generate-share-link.js";
import { rbacGetCurrentMemberRolesAndPermissions } from "../funcs/rbac-get-current-member-roles-and-permissions.js";
import { rbacGetEmbedUserApiKey } from "../funcs/rbac-get-embed-user-api-key.js";
import { rbacGetMemberRoles } from "../funcs/rbac-get-member-roles.js";
import { rbacGetObjectAccess } from "../funcs/rbac-get-object-access.js";
import { rbacGetRolePermissions } from "../funcs/rbac-get-role-permissions.js";
import { rbacGetRole } from "../funcs/rbac-get-role.js";
import { rbacHasObjectAccess } from "../funcs/rbac-has-object-access.js";
import { rbacImportRoles } from "../funcs/rbac-import-roles.js";
import { rbacListAccessRequests } from "../funcs/rbac-list-access-requests.js";
import { rbacListApiKeys } from "../funcs/rbac-list-api-keys.js";
import { rbacListPermissions } from "../funcs/rbac-list-permissions.js";
import { rbacListRoles } from "../funcs/rbac-list-roles.js";
import { rbacListServiceAccounts } from "../funcs/rbac-list-service-accounts.js";
import { rbacParseRoleImport } from "../funcs/rbac-parse-role-import.js";
import { rbacRejectAccessRequest } from "../funcs/rbac-reject-access-request.js";
import { rbacRemovePermissionFromRole } from "../funcs/rbac-remove-permission-from-role.js";
import { rbacRemoveRoleFromMember } from "../funcs/rbac-remove-role-from-member.js";
import { rbacRequestAccess } from "../funcs/rbac-request-access.js";
import { rbacRevokeApiKey } from "../funcs/rbac-revoke-api-key.js";
import { rbacRevokeObjectAccess } from "../funcs/rbac-revoke-object-access.js";
import { rbacRotateApiKey } from "../funcs/rbac-rotate-api-key.js";
import { rbacSetRolePermissions } from "../funcs/rbac-set-role-permissions.js";
import { rbacShareObjectWithRole } from "../funcs/rbac-share-object-with-role.js";
import { rbacShareObject } from "../funcs/rbac-share-object.js";
import { rbacUpdateObjectAccess } from "../funcs/rbac-update-object-access.js";
import { rbacUpdateObjectVisibility } from "../funcs/rbac-update-object-visibility.js";
import { rbacUpdateRole } from "../funcs/rbac-update-role.js";
import { rbacWhoAmI } from "../funcs/rbac-who-am-i.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rbac extends ClientSDK {
  /**
   * ApproveAccessRequest
   */
  async approveAccessRequest(
    request: operations.RBACServiceApproveAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceApproveAccessRequestResponse> {
    return unwrapAsync(rbacApproveAccessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * AssignPermissionToRole
   */
  async assignPermissionToRole(
    request: operations.RBACServiceAssignPermissionToRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceAssignPermissionToRoleResponse> {
    return unwrapAsync(rbacAssignPermissionToRole(
      this,
      request,
      options,
    ));
  }

  /**
   * Member role assignment
   *
   * @remarks
   * Member role assignment
   */
  async assignRoleToMember(
    request: operations.RBACServiceAssignRoleToMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceAssignRoleToMemberResponse> {
    return unwrapAsync(rbacAssignRoleToMember(
      this,
      request,
      options,
    ));
  }

  /**
   * API Key management
   *
   * @remarks
   * API Key management
   */
  async createApiKey(
    request: operations.RBACServiceCreateApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateApiKeyResponse> {
    return unwrapAsync(rbacCreateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an API key owned by the calling member. Requires no permission.
   *
   * @remarks
   * Create an API key owned by the calling member. Requires no permission.
   */
  async createPersonalApiKey(
    request: operations.RBACServiceCreatePersonalApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreatePersonalApiKeyResponse> {
    return unwrapAsync(rbacCreatePersonalApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Role management
   *
   * @remarks
   * Role management
   */
  async createRole(
    request: operations.RBACServiceCreateRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateRoleResponse> {
    return unwrapAsync(rbacCreateRole(
      this,
      request,
      options,
    ));
  }

  /**
   * CreateRolePermissionsUploadUrl
   */
  async createImportUpload(
    request: operations.RBACServiceCreateRolePermissionsUploadUrlRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateRolePermissionsUploadUrlResponse> {
    return unwrapAsync(rbacCreateImportUpload(
      this,
      request,
      options,
    ));
  }

  /**
   * Service account management
   *
   * @remarks
   * Service account management
   */
  async createServiceAccount(
    request: operations.RBACServiceCreateServiceAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateServiceAccountResponse> {
    return unwrapAsync(rbacCreateServiceAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an API key owned by a service account. Requires organization:write.
   *
   * @remarks
   * Create an API key owned by a service account. Requires organization:write.
   */
  async createServiceAccountApiKey(
    request: operations.RBACServiceCreateServiceAccountApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateServiceAccountApiKeyResponse> {
    return unwrapAsync(rbacCreateServiceAccountApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteRole
   */
  async deleteRole(
    request: operations.RBACServiceDeleteRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceDeleteRoleResponse> {
    return unwrapAsync(rbacDeleteRole(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteServiceAccount
   */
  async deleteServiceAccount(
    request: operations.RBACServiceDeleteServiceAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceDeleteServiceAccountResponse> {
    return unwrapAsync(rbacDeleteServiceAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * ExportRolePermissions
   */
  async exportRoles(
    request: operations.RBACServiceExportRolePermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceExportRolePermissionsResponse> {
    return unwrapAsync(rbacExportRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * GenerateShareLink
   */
  async generateShareLink(
    request: operations.RBACServiceGenerateShareLinkRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGenerateShareLinkResponse> {
    return unwrapAsync(rbacGenerateShareLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current member roles and permissions
   *
   * @remarks
   * Get current member roles and permissions
   */
  async getCurrentMemberRolesAndPermissions(
    request: operations.RBACServiceGetCurrentMemberRolesAndPermissionsRequest,
    options?: RequestOptions,
  ): Promise<
    operations.RBACServiceGetCurrentMemberRolesAndPermissionsResponse
  > {
    return unwrapAsync(rbacGetCurrentMemberRolesAndPermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * GetEmbedUserApiKey
   */
  async getEmbedUserApiKey(
    request: operations.RBACServiceGetEmbedUserApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetEmbedUserApiKeyResponse> {
    return unwrapAsync(rbacGetEmbedUserApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * GetMemberRoles
   */
  async getMemberRoles(
    request: operations.RBACServiceGetMemberRolesRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetMemberRolesResponse> {
    return unwrapAsync(rbacGetMemberRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * GetObjectAccess
   */
  async getObjectAccess(
    request: operations.RBACServiceGetObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetObjectAccessResponse> {
    return unwrapAsync(rbacGetObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * GetRole
   */
  async getRole(
    request: operations.RBACServiceGetRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetRoleResponse> {
    return unwrapAsync(rbacGetRole(
      this,
      request,
      options,
    ));
  }

  /**
   * GetRolePermissions
   */
  async getRolePermissions(
    request: operations.RBACServiceGetRolePermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetRolePermissionsResponse> {
    return unwrapAsync(rbacGetRolePermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * HasObjectAccess
   */
  async hasObjectAccess(
    request: operations.RBACServiceHasObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceHasObjectAccessResponse> {
    return unwrapAsync(rbacHasObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * ImportRolePermissions
   */
  async importRoles(
    request: operations.RBACServiceImportRolePermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceImportRolePermissionsResponse> {
    return unwrapAsync(rbacImportRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * ListAccessRequests
   */
  async listAccessRequests(
    request: operations.RBACServiceListAccessRequestsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListAccessRequestsResponse> {
    return unwrapAsync(rbacListAccessRequests(
      this,
      request,
      options,
    ));
  }

  /**
   * ListApiKeys
   */
  async listApiKeys(
    request: operations.RBACServiceListApiKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListApiKeysResponse> {
    return unwrapAsync(rbacListApiKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * Permission management
   *
   * @remarks
   * Permission management
   */
  async listPermissions(
    request: operations.RBACServiceListPermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListPermissionsResponse> {
    return unwrapAsync(rbacListPermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * ListRoles
   */
  async listRoles(
    request: operations.RBACServiceListRolesRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListRolesResponse> {
    return unwrapAsync(rbacListRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * ListServiceAccounts
   */
  async listServiceAccounts(
    request: operations.RBACServiceListServiceAccountsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListServiceAccountsResponse> {
    return unwrapAsync(rbacListServiceAccounts(
      this,
      request,
      options,
    ));
  }

  /**
   * Parse a CSV or XLSX file into an editable draft without creating roles.  Unknown names and values are preserved for correction; import validates them.
   *
   * @remarks
   * Parse a CSV or XLSX file into an editable draft without creating roles.
   *  Unknown names and values are preserved for correction; import validates them.
   */
  async parseRoleImport(
    request: operations.RBACServiceParseRolePermissionsImportRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceParseRolePermissionsImportResponse> {
    return unwrapAsync(rbacParseRoleImport(
      this,
      request,
      options,
    ));
  }

  /**
   * RejectAccessRequest
   */
  async rejectAccessRequest(
    request: operations.RBACServiceRejectAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRejectAccessRequestResponse> {
    return unwrapAsync(rbacRejectAccessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * RemovePermissionFromRole
   */
  async removePermissionFromRole(
    request: operations.RBACServiceRemovePermissionFromRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRemovePermissionFromRoleResponse> {
    return unwrapAsync(rbacRemovePermissionFromRole(
      this,
      request,
      options,
    ));
  }

  /**
   * RemoveRoleFromMember
   */
  async removeRoleFromMember(
    request: operations.RBACServiceRemoveRoleFromMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRemoveRoleFromMemberResponse> {
    return unwrapAsync(rbacRemoveRoleFromMember(
      this,
      request,
      options,
    ));
  }

  /**
   * Access request management
   *
   * @remarks
   * Access request management
   */
  async requestAccess(
    request: operations.RBACServiceRequestAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRequestAccessResponse> {
    return unwrapAsync(rbacRequestAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * RevokeApiKey
   */
  async revokeApiKey(
    request: operations.RBACServiceRevokeApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRevokeApiKeyResponse> {
    return unwrapAsync(rbacRevokeApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * RevokeObjectAccess
   */
  async revokeObjectAccess(
    request: operations.RBACServiceRevokeObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRevokeObjectAccessResponse> {
    return unwrapAsync(rbacRevokeObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * RotateApiKey
   */
  async rotateApiKey(
    request: operations.RBACServiceRotateApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRotateApiKeyResponse> {
    return unwrapAsync(rbacRotateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Bulk add/remove permissions on a role in one call, producing a single audit entry for the whole edit.
   *
   * @remarks
   * Bulk add/remove permissions on a role in one call, producing a single audit entry for the whole edit.
   */
  async setRolePermissions(
    request: operations.RBACServiceSetRolePermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceSetRolePermissionsResponse> {
    return unwrapAsync(rbacSetRolePermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * Object sharing and access control
   *
   * @remarks
   * Object sharing and access control
   */
  async shareObject(
    request: operations.RBACServiceShareObjectRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceShareObjectResponse> {
    return unwrapAsync(rbacShareObject(
      this,
      request,
      options,
    ));
  }

  /**
   * ShareObjectWithRole
   */
  async shareObjectWithRole(
    request: operations.RBACServiceShareObjectWithRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceShareObjectWithRoleResponse> {
    return unwrapAsync(rbacShareObjectWithRole(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateObjectAccess
   */
  async updateObjectAccess(
    request: operations.RBACServiceUpdateObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateObjectAccessResponse> {
    return unwrapAsync(rbacUpdateObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateObjectVisibility
   */
  async updateObjectVisibility(
    request: operations.RBACServiceUpdateObjectVisibilityRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateObjectVisibilityResponse> {
    return unwrapAsync(rbacUpdateObjectVisibility(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateRole
   */
  async updateRole(
    request: operations.RBACServiceUpdateRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateRoleResponse> {
    return unwrapAsync(rbacUpdateRole(
      this,
      request,
      options,
    ));
  }

  /**
   * Describe what a key is allowed to do.
   *
   * @remarks
   * Describe what a key is allowed to do.
   */
  async whoAmI(
    request: operations.RBACServiceWhoAmIRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceWhoAmIResponse> {
    return unwrapAsync(rbacWhoAmI(
      this,
      request,
      options,
    ));
  }
}
