/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rbacAddGroupMember } from "../funcs/rbac-add-group-member.js";
import { rbacApproveAccessRequest } from "../funcs/rbac-approve-access-request.js";
import { rbacAssignPermissionToRole } from "../funcs/rbac-assign-permission-to-role.js";
import { rbacAssignRoleToMember } from "../funcs/rbac-assign-role-to-member.js";
import { rbacConvertRoleToGroup } from "../funcs/rbac-convert-role-to-group.js";
import { rbacCreateApiKey } from "../funcs/rbac-create-api-key.js";
import { rbacCreateGroup } from "../funcs/rbac-create-group.js";
import { rbacCreateRole } from "../funcs/rbac-create-role.js";
import { rbacCreateServiceAccount } from "../funcs/rbac-create-service-account.js";
import { rbacDeleteGroup } from "../funcs/rbac-delete-group.js";
import { rbacDeleteRole } from "../funcs/rbac-delete-role.js";
import { rbacDeleteServiceAccount } from "../funcs/rbac-delete-service-account.js";
import { rbacGenerateShareLink } from "../funcs/rbac-generate-share-link.js";
import { rbacGetCurrentMemberRolesAndPermissions } from "../funcs/rbac-get-current-member-roles-and-permissions.js";
import { rbacGetEmbedUserApiKey } from "../funcs/rbac-get-embed-user-api-key.js";
import { rbacGetGroup } from "../funcs/rbac-get-group.js";
import { rbacGetMemberGroups } from "../funcs/rbac-get-member-groups.js";
import { rbacGetMemberRoles } from "../funcs/rbac-get-member-roles.js";
import { rbacGetObjectAccess } from "../funcs/rbac-get-object-access.js";
import { rbacGetRolePermissions } from "../funcs/rbac-get-role-permissions.js";
import { rbacGetRole } from "../funcs/rbac-get-role.js";
import { rbacHasObjectAccess } from "../funcs/rbac-has-object-access.js";
import { rbacListAccessRequests } from "../funcs/rbac-list-access-requests.js";
import { rbacListApiKeys } from "../funcs/rbac-list-api-keys.js";
import { rbacListGroupConnectors } from "../funcs/rbac-list-group-connectors.js";
import { rbacListGroups } from "../funcs/rbac-list-groups.js";
import { rbacListPermissions } from "../funcs/rbac-list-permissions.js";
import { rbacListRoles } from "../funcs/rbac-list-roles.js";
import { rbacListScimGroupMappings } from "../funcs/rbac-list-scim-group-mappings.js";
import { rbacListServiceAccounts } from "../funcs/rbac-list-service-accounts.js";
import { rbacMigrateAllScimGroupMappings } from "../funcs/rbac-migrate-all-scim-group-mappings.js";
import { rbacMigrateScimGroupMappingToGroup } from "../funcs/rbac-migrate-scim-group-mapping-to-group.js";
import { rbacRejectAccessRequest } from "../funcs/rbac-reject-access-request.js";
import { rbacRemoveGroupMember } from "../funcs/rbac-remove-group-member.js";
import { rbacRemovePermissionFromRole } from "../funcs/rbac-remove-permission-from-role.js";
import { rbacRemoveRoleFromMember } from "../funcs/rbac-remove-role-from-member.js";
import { rbacRequestAccess } from "../funcs/rbac-request-access.js";
import { rbacRevertScimGroupMappingToRole } from "../funcs/rbac-revert-scim-group-mapping-to-role.js";
import { rbacRevokeApiKey } from "../funcs/rbac-revoke-api-key.js";
import { rbacRevokeObjectAccess } from "../funcs/rbac-revoke-object-access.js";
import { rbacRotateApiKey } from "../funcs/rbac-rotate-api-key.js";
import { rbacShareObjectWithRole } from "../funcs/rbac-share-object-with-role.js";
import { rbacShareObject } from "../funcs/rbac-share-object.js";
import { rbacShareWithGroup } from "../funcs/rbac-share-with-group.js";
import { rbacUpdateGroup } from "../funcs/rbac-update-group.js";
import { rbacUpdateObjectAccess } from "../funcs/rbac-update-object-access.js";
import { rbacUpdateObjectVisibility } from "../funcs/rbac-update-object-visibility.js";
import { rbacUpdateRole } from "../funcs/rbac-update-role.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rbac extends ClientSDK {
  /**
   * AddGroupMember
   */
  async addGroupMember(
    request: operations.RBACServiceAddGroupMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceAddGroupMemberResponse> {
    return unwrapAsync(rbacAddGroupMember(
      this,
      request,
      options,
    ));
  }

  /**
   * ApproveAccessRequest
   */
  async approveAccessRequest(
    request: operations.RBACServiceApproveAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceApproveAccessRequestResponse> {
    return unwrapAsync(rbacApproveAccessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * AssignPermissionToRole
   */
  async assignPermissionToRole(
    request: operations.RBACServiceAssignPermissionToRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceAssignPermissionToRoleResponse> {
    return unwrapAsync(rbacAssignPermissionToRole(
      this,
      request,
      options,
    ));
  }

  /**
   * Member role assignment
   *
   * @remarks
   * Member role assignment
   */
  async assignRoleToMember(
    request: operations.RBACServiceAssignRoleToMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceAssignRoleToMemberResponse> {
    return unwrapAsync(rbacAssignRoleToMember(
      this,
      request,
      options,
    ));
  }

  /**
   * ConvertRoleToGroup
   */
  async convertRoleToGroup(
    request: operations.RBACServiceConvertRoleToGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceConvertRoleToGroupResponse> {
    return unwrapAsync(rbacConvertRoleToGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * API Key management
   *
   * @remarks
   * API Key management
   */
  async createApiKey(
    request: operations.RBACServiceCreateApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateApiKeyResponse> {
    return unwrapAsync(rbacCreateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * CreateGroup
   */
  async createGroup(
    request: operations.RBACServiceCreateGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateGroupResponse> {
    return unwrapAsync(rbacCreateGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Role management
   *
   * @remarks
   * Role management
   */
  async createRole(
    request: operations.RBACServiceCreateRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateRoleResponse> {
    return unwrapAsync(rbacCreateRole(
      this,
      request,
      options,
    ));
  }

  /**
   * Service account management
   *
   * @remarks
   * Service account management
   */
  async createServiceAccount(
    request: operations.RBACServiceCreateServiceAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceCreateServiceAccountResponse> {
    return unwrapAsync(rbacCreateServiceAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteGroup
   */
  async deleteGroup(
    request: operations.RBACServiceDeleteGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceDeleteGroupResponse> {
    return unwrapAsync(rbacDeleteGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteRole
   */
  async deleteRole(
    request: operations.RBACServiceDeleteRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceDeleteRoleResponse> {
    return unwrapAsync(rbacDeleteRole(
      this,
      request,
      options,
    ));
  }

  /**
   * DeleteServiceAccount
   */
  async deleteServiceAccount(
    request: operations.RBACServiceDeleteServiceAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceDeleteServiceAccountResponse> {
    return unwrapAsync(rbacDeleteServiceAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * GenerateShareLink
   */
  async generateShareLink(
    request: operations.RBACServiceGenerateShareLinkRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGenerateShareLinkResponse> {
    return unwrapAsync(rbacGenerateShareLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current member roles and permissions
   *
   * @remarks
   * Get current member roles and permissions
   */
  async getCurrentMemberRolesAndPermissions(
    request: operations.RBACServiceGetCurrentMemberRolesAndPermissionsRequest,
    options?: RequestOptions,
  ): Promise<
    operations.RBACServiceGetCurrentMemberRolesAndPermissionsResponse
  > {
    return unwrapAsync(rbacGetCurrentMemberRolesAndPermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * GetEmbedUserApiKey
   */
  async getEmbedUserApiKey(
    request: operations.RBACServiceGetEmbedUserApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetEmbedUserApiKeyResponse> {
    return unwrapAsync(rbacGetEmbedUserApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * GetGroup
   */
  async getGroup(
    request: operations.RBACServiceGetGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetGroupResponse> {
    return unwrapAsync(rbacGetGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * GetMemberGroups
   */
  async getMemberGroups(
    request: operations.RBACServiceGetMemberGroupsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetMemberGroupsResponse> {
    return unwrapAsync(rbacGetMemberGroups(
      this,
      request,
      options,
    ));
  }

  /**
   * GetMemberRoles
   */
  async getMemberRoles(
    request: operations.RBACServiceGetMemberRolesRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetMemberRolesResponse> {
    return unwrapAsync(rbacGetMemberRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * GetObjectAccess
   */
  async getObjectAccess(
    request: operations.RBACServiceGetObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetObjectAccessResponse> {
    return unwrapAsync(rbacGetObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * GetRole
   */
  async getRole(
    request: operations.RBACServiceGetRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetRoleResponse> {
    return unwrapAsync(rbacGetRole(
      this,
      request,
      options,
    ));
  }

  /**
   * GetRolePermissions
   */
  async getRolePermissions(
    request: operations.RBACServiceGetRolePermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceGetRolePermissionsResponse> {
    return unwrapAsync(rbacGetRolePermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * HasObjectAccess
   */
  async hasObjectAccess(
    request: operations.RBACServiceHasObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceHasObjectAccessResponse> {
    return unwrapAsync(rbacHasObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * ListAccessRequests
   */
  async listAccessRequests(
    request: operations.RBACServiceListAccessRequestsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListAccessRequestsResponse> {
    return unwrapAsync(rbacListAccessRequests(
      this,
      request,
      options,
    ));
  }

  /**
   * ListApiKeys
   */
  async listApiKeys(
    request: operations.RBACServiceListApiKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListApiKeysResponse> {
    return unwrapAsync(rbacListApiKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * ListGroupConnectors
   */
  async listGroupConnectors(
    request: operations.RBACServiceListGroupConnectorsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListGroupConnectorsResponse> {
    return unwrapAsync(rbacListGroupConnectors(
      this,
      request,
      options,
    ));
  }

  /**
   * ListGroups
   */
  async listGroups(
    request: operations.RBACServiceListGroupsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListGroupsResponse> {
    return unwrapAsync(rbacListGroups(
      this,
      request,
      options,
    ));
  }

  /**
   * Permission management
   *
   * @remarks
   * Permission management
   */
  async listPermissions(
    request: operations.RBACServiceListPermissionsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListPermissionsResponse> {
    return unwrapAsync(rbacListPermissions(
      this,
      request,
      options,
    ));
  }

  /**
   * ListRoles
   */
  async listRoles(
    request: operations.RBACServiceListRolesRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListRolesResponse> {
    return unwrapAsync(rbacListRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * ListScimGroupMappings
   */
  async listScimGroupMappings(
    request: operations.RBACServiceListScimGroupMappingsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListScimGroupMappingsResponse> {
    return unwrapAsync(rbacListScimGroupMappings(
      this,
      request,
      options,
    ));
  }

  /**
   * ListServiceAccounts
   */
  async listServiceAccounts(
    request: operations.RBACServiceListServiceAccountsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceListServiceAccountsResponse> {
    return unwrapAsync(rbacListServiceAccounts(
      this,
      request,
      options,
    ));
  }

  /**
   * MigrateAllScimGroupMappings
   */
  async migrateAllScimGroupMappings(
    request: operations.RBACServiceMigrateAllScimGroupMappingsRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceMigrateAllScimGroupMappingsResponse> {
    return unwrapAsync(rbacMigrateAllScimGroupMappings(
      this,
      request,
      options,
    ));
  }

  /**
   * MigrateScimGroupMappingToGroup
   */
  async migrateScimGroupMappingToGroup(
    request: operations.RBACServiceMigrateScimGroupMappingToGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceMigrateScimGroupMappingToGroupResponse> {
    return unwrapAsync(rbacMigrateScimGroupMappingToGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * RejectAccessRequest
   */
  async rejectAccessRequest(
    request: operations.RBACServiceRejectAccessRequestRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRejectAccessRequestResponse> {
    return unwrapAsync(rbacRejectAccessRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * RemoveGroupMember
   */
  async removeGroupMember(
    request: operations.RBACServiceRemoveGroupMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRemoveGroupMemberResponse> {
    return unwrapAsync(rbacRemoveGroupMember(
      this,
      request,
      options,
    ));
  }

  /**
   * RemovePermissionFromRole
   */
  async removePermissionFromRole(
    request: operations.RBACServiceRemovePermissionFromRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRemovePermissionFromRoleResponse> {
    return unwrapAsync(rbacRemovePermissionFromRole(
      this,
      request,
      options,
    ));
  }

  /**
   * RemoveRoleFromMember
   */
  async removeRoleFromMember(
    request: operations.RBACServiceRemoveRoleFromMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRemoveRoleFromMemberResponse> {
    return unwrapAsync(rbacRemoveRoleFromMember(
      this,
      request,
      options,
    ));
  }

  /**
   * Access request management
   *
   * @remarks
   * Access request management
   */
  async requestAccess(
    request: operations.RBACServiceRequestAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRequestAccessResponse> {
    return unwrapAsync(rbacRequestAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * RevertScimGroupMappingToRole
   */
  async revertScimGroupMappingToRole(
    request: operations.RBACServiceRevertScimGroupMappingToRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRevertScimGroupMappingToRoleResponse> {
    return unwrapAsync(rbacRevertScimGroupMappingToRole(
      this,
      request,
      options,
    ));
  }

  /**
   * RevokeApiKey
   */
  async revokeApiKey(
    request: operations.RBACServiceRevokeApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRevokeApiKeyResponse> {
    return unwrapAsync(rbacRevokeApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * RevokeObjectAccess
   */
  async revokeObjectAccess(
    request: operations.RBACServiceRevokeObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRevokeObjectAccessResponse> {
    return unwrapAsync(rbacRevokeObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * RotateApiKey
   */
  async rotateApiKey(
    request: operations.RBACServiceRotateApiKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceRotateApiKeyResponse> {
    return unwrapAsync(rbacRotateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Object sharing and access control
   *
   * @remarks
   * Object sharing and access control
   */
  async shareObject(
    request: operations.RBACServiceShareObjectRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceShareObjectResponse> {
    return unwrapAsync(rbacShareObject(
      this,
      request,
      options,
    ));
  }

  /**
   * ShareObjectWithGroup
   */
  async shareWithGroup(
    request: operations.RBACServiceShareObjectWithGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceShareObjectWithGroupResponse> {
    return unwrapAsync(rbacShareWithGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * ShareObjectWithRole
   */
  async shareObjectWithRole(
    request: operations.RBACServiceShareObjectWithRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceShareObjectWithRoleResponse> {
    return unwrapAsync(rbacShareObjectWithRole(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateGroup
   */
  async updateGroup(
    request: operations.RBACServiceUpdateGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateGroupResponse> {
    return unwrapAsync(rbacUpdateGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateObjectAccess
   */
  async updateObjectAccess(
    request: operations.RBACServiceUpdateObjectAccessRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateObjectAccessResponse> {
    return unwrapAsync(rbacUpdateObjectAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateObjectVisibility
   */
  async updateObjectVisibility(
    request: operations.RBACServiceUpdateObjectVisibilityRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateObjectVisibilityResponse> {
    return unwrapAsync(rbacUpdateObjectVisibility(
      this,
      request,
      options,
    ));
  }

  /**
   * UpdateRole
   */
  async updateRole(
    request: operations.RBACServiceUpdateRoleRequest,
    options?: RequestOptions,
  ): Promise<operations.RBACServiceUpdateRoleResponse> {
    return unwrapAsync(rbacUpdateRole(
      this,
      request,
      options,
    ));
  }
}
