/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sandboxCreate } from "../funcs/sandbox-create.js";
import { sandboxExec } from "../funcs/sandbox-exec.js";
import { sandboxExecuteCode } from "../funcs/sandbox-execute-code.js";
import { sandboxExecuteQuery } from "../funcs/sandbox-execute-query.js";
import { sandboxGetToolAvailability } from "../funcs/sandbox-get-tool-availability.js";
import { sandboxLoadConnectorData } from "../funcs/sandbox-load-connector-data.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sandbox extends ClientSDK {
  /**
   * CreateSandbox
   */
  async create(
    request: operations.SandboxExecServiceCreateSandboxRequest,
    options?: RequestOptions,
  ): Promise<operations.SandboxExecServiceCreateSandboxResponse> {
    return unwrapAsync(sandboxCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Exec
   */
  async exec(
    request: operations.SandboxExecServiceExecRequest,
    options?: RequestOptions,
  ): Promise<operations.SandboxExecServiceExecResponse> {
    return unwrapAsync(sandboxExec(
      this,
      request,
      options,
    ));
  }

  /**
   * ExecuteCode
   */
  async executeCode(
    request: operations.SandboxExecServiceExecuteCodeRequest,
    options?: RequestOptions,
  ): Promise<operations.SandboxExecServiceExecuteCodeResponse> {
    return unwrapAsync(sandboxExecuteCode(
      this,
      request,
      options,
    ));
  }

  /**
   * GetToolAvailability
   */
  async getToolAvailability(
    request: operations.SandboxExecServiceGetToolAvailabilityRequest,
    options?: RequestOptions,
  ): Promise<operations.SandboxExecServiceGetToolAvailabilityResponse> {
    return unwrapAsync(sandboxGetToolAvailability(
      this,
      request,
      options,
    ));
  }

  /**
   * LoadConnectorData
   */
  async loadConnectorData(
    request: operations.SandboxExecServiceLoadConnectorDataRequest,
    options?: RequestOptions,
  ): Promise<operations.SandboxExecServiceLoadConnectorDataResponse> {
    return unwrapAsync(sandboxLoadConnectorData(
      this,
      request,
      options,
    ));
  }

  /**
   * ExecuteQuery
   */
  async executeQuery(
    request: operations.SandboxQueryServiceExecuteQueryRequest,
    options?: RequestOptions,
  ): Promise<operations.SandboxQueryServiceExecuteQueryResponse> {
    return unwrapAsync(sandboxExecuteQuery(
      this,
      request,
      options,
    ));
  }
}
