/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Agents } from "./agents.js";
import { Apps } from "./apps.js";
import { AuditLogs } from "./audit-logs.js";
import { Chats } from "./chats.js";
import { Connectors } from "./connectors.js";
import { Dashboards } from "./dashboards.js";
import { Datasets } from "./datasets.js";
import { Libraries } from "./libraries.js";
import { LibraryService } from "./library-service.js";
import { Mcp } from "./mcp.js";
import { MetricsExports } from "./metrics-exports.js";
import { Observability } from "./observability.js";
import { Playbooks } from "./playbooks.js";
import { Powerbi } from "./powerbi.js";
import { Rbac } from "./rbac.js";
import { SandboxAdmin } from "./sandbox-admin.js";
import { Sandbox } from "./sandbox.js";
import { Scim } from "./scim.js";
import { Secrets } from "./secrets.js";
import { Slack } from "./slack.js";
import { Tableau } from "./tableau.js";
import { Teams } from "./teams.js";

export class Textql extends ClientSDK {
  private _agents?: Agents;
  get agents(): Agents {
    return (this._agents ??= new Agents(this._options));
  }

  private _apps?: Apps;
  get apps(): Apps {
    return (this._apps ??= new Apps(this._options));
  }

  private _auditLogs?: AuditLogs;
  get auditLogs(): AuditLogs {
    return (this._auditLogs ??= new AuditLogs(this._options));
  }

  private _chats?: Chats;
  get chats(): Chats {
    return (this._chats ??= new Chats(this._options));
  }

  private _connectors?: Connectors;
  get connectors(): Connectors {
    return (this._connectors ??= new Connectors(this._options));
  }

  private _dashboards?: Dashboards;
  get dashboards(): Dashboards {
    return (this._dashboards ??= new Dashboards(this._options));
  }

  private _datasets?: Datasets;
  get datasets(): Datasets {
    return (this._datasets ??= new Datasets(this._options));
  }

  private _mcp?: Mcp;
  get mcp(): Mcp {
    return (this._mcp ??= new Mcp(this._options));
  }

  private _metricsExports?: MetricsExports;
  get metricsExports(): MetricsExports {
    return (this._metricsExports ??= new MetricsExports(this._options));
  }

  private _observability?: Observability;
  get observability(): Observability {
    return (this._observability ??= new Observability(this._options));
  }

  private _libraries?: Libraries;
  get libraries(): Libraries {
    return (this._libraries ??= new Libraries(this._options));
  }

  private _libraryService?: LibraryService;
  get libraryService(): LibraryService {
    return (this._libraryService ??= new LibraryService(this._options));
  }

  private _playbooks?: Playbooks;
  get playbooks(): Playbooks {
    return (this._playbooks ??= new Playbooks(this._options));
  }

  private _powerbi?: Powerbi;
  get powerbi(): Powerbi {
    return (this._powerbi ??= new Powerbi(this._options));
  }

  private _rbac?: Rbac;
  get rbac(): Rbac {
    return (this._rbac ??= new Rbac(this._options));
  }

  private _sandboxAdmin?: SandboxAdmin;
  get sandboxAdmin(): SandboxAdmin {
    return (this._sandboxAdmin ??= new SandboxAdmin(this._options));
  }

  private _sandbox?: Sandbox;
  get sandbox(): Sandbox {
    return (this._sandbox ??= new Sandbox(this._options));
  }

  private _scim?: Scim;
  get scim(): Scim {
    return (this._scim ??= new Scim(this._options));
  }

  private _secrets?: Secrets;
  get secrets(): Secrets {
    return (this._secrets ??= new Secrets(this._options));
  }

  private _slack?: Slack;
  get slack(): Slack {
    return (this._slack ??= new Slack(this._options));
  }

  private _tableau?: Tableau;
  get tableau(): Tableau {
    return (this._tableau ??= new Tableau(this._options));
  }

  private _teams?: Teams;
  get teams(): Teams {
    return (this._teams ??= new Teams(this._options));
  }
}
