/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsDeleteApiAccessKey } from "../funcs/secrets-delete-api-access-key.js";
import { secretsGetApiAccessKey } from "../funcs/secrets-get-api-access-key.js";
import { secretsListApiAccessKeys } from "../funcs/secrets-list-api-access-keys.js";
import { secretsListApiProviders } from "../funcs/secrets-list-api-providers.js";
import { secretsTestApiAccessKey } from "../funcs/secrets-test-api-access-key.js";
import { secretsUpsertApiAccessKey } from "../funcs/secrets-upsert-api-access-key.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Secrets extends ClientSDK {
  /**
   * DeleteApiAccessKey
   */
  async deleteApiAccessKey(
    request: operations.SecretServiceDeleteApiAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.SecretServiceDeleteApiAccessKeyResponse> {
    return unwrapAsync(secretsDeleteApiAccessKey(
      this,
      request,
      options,
    ));
  }

  /**
   * GetApiAccessKey
   */
  async getApiAccessKey(
    request: operations.SecretServiceGetApiAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.SecretServiceGetApiAccessKeyResponse> {
    return unwrapAsync(secretsGetApiAccessKey(
      this,
      request,
      options,
    ));
  }

  /**
   * ListApiAccessKeys
   */
  async listApiAccessKeys(
    request: operations.SecretServiceListApiAccessKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.SecretServiceListApiAccessKeysResponse> {
    return unwrapAsync(secretsListApiAccessKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * ListApiProviders
   */
  async listApiProviders(
    request: operations.SecretServiceListApiProvidersRequest,
    options?: RequestOptions,
  ): Promise<operations.SecretServiceListApiProvidersResponse> {
    return unwrapAsync(secretsListApiProviders(
      this,
      request,
      options,
    ));
  }

  /**
   * ---- API Connectors (deprecated) ----
   *
   * @remarks
   * ---- API Connectors (deprecated) ----
   */
  async testApiAccessKey(
    request: operations.SecretServiceTestApiAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.SecretServiceTestApiAccessKeyResponse> {
    return unwrapAsync(secretsTestApiAccessKey(
      this,
      request,
      options,
    ));
  }

  /**
   * UpsertApiAccessKey
   */
  async upsertApiAccessKey(
    request: operations.SecretServiceUpsertApiAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.SecretServiceUpsertApiAccessKeyResponse> {
    return unwrapAsync(secretsUpsertApiAccessKey(
      this,
      request,
      options,
    ));
  }
}
