/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AgentServiceResetAgentAvatarRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAgentResetAgentAvatarRequest;
};

export type AgentServiceResetAgentAvatarResponse =
  | models.TextqlRpcPublicAgentResetAgentAvatarResponse
  | models.ConnectError;

/** @internal */
export type AgentServiceResetAgentAvatarRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAgentResetAgentAvatarRequest$Outbound;
};

/** @internal */
export const AgentServiceResetAgentAvatarRequest$outboundSchema: z.ZodMiniType<
  AgentServiceResetAgentAvatarRequest$Outbound,
  AgentServiceResetAgentAvatarRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicAgentResetAgentAvatarRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function agentServiceResetAgentAvatarRequestToJSON(
  agentServiceResetAgentAvatarRequest: AgentServiceResetAgentAvatarRequest,
): string {
  return JSON.stringify(
    AgentServiceResetAgentAvatarRequest$outboundSchema.parse(
      agentServiceResetAgentAvatarRequest,
    ),
  );
}

/** @internal */
export const AgentServiceResetAgentAvatarResponse$inboundSchema: z.ZodMiniType<
  AgentServiceResetAgentAvatarResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicAgentResetAgentAvatarResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function agentServiceResetAgentAvatarResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentServiceResetAgentAvatarResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AgentServiceResetAgentAvatarResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentServiceResetAgentAvatarResponse' from JSON`,
  );
}
