/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AgentServiceCreateAgentRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAgentCreateAgentRequest;
};

export type AgentServiceCreateAgentResponse =
  | models.TextqlRpcPublicAgentCreateAgentResponse
  | models.ConnectError;

/** @internal */
export type AgentServiceCreateAgentRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAgentCreateAgentRequest$Outbound;
};

/** @internal */
export const AgentServiceCreateAgentRequest$outboundSchema: z.ZodMiniType<
  AgentServiceCreateAgentRequest$Outbound,
  AgentServiceCreateAgentRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicAgentCreateAgentRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function agentServiceCreateAgentRequestToJSON(
  agentServiceCreateAgentRequest: AgentServiceCreateAgentRequest,
): string {
  return JSON.stringify(
    AgentServiceCreateAgentRequest$outboundSchema.parse(
      agentServiceCreateAgentRequest,
    ),
  );
}

/** @internal */
export const AgentServiceCreateAgentResponse$inboundSchema: z.ZodMiniType<
  AgentServiceCreateAgentResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicAgentCreateAgentResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function agentServiceCreateAgentResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentServiceCreateAgentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentServiceCreateAgentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentServiceCreateAgentResponse' from JSON`,
  );
}
