/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ApiOAuthServiceExchangeApiOAuthCodeRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicApiOauthExchangeApiOAuthCodeRequest;
};

export type ApiOAuthServiceExchangeApiOAuthCodeResponse =
  | models.TextqlRpcPublicApiOauthExchangeApiOAuthCodeResponse
  | models.ConnectError;

/** @internal */
export type ApiOAuthServiceExchangeApiOAuthCodeRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicApiOauthExchangeApiOAuthCodeRequest$Outbound;
};

/** @internal */
export const ApiOAuthServiceExchangeApiOAuthCodeRequest$outboundSchema:
  z.ZodMiniType<
    ApiOAuthServiceExchangeApiOAuthCodeRequest$Outbound,
    ApiOAuthServiceExchangeApiOAuthCodeRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicApiOauthExchangeApiOAuthCodeRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function apiOAuthServiceExchangeApiOAuthCodeRequestToJSON(
  apiOAuthServiceExchangeApiOAuthCodeRequest:
    ApiOAuthServiceExchangeApiOAuthCodeRequest,
): string {
  return JSON.stringify(
    ApiOAuthServiceExchangeApiOAuthCodeRequest$outboundSchema.parse(
      apiOAuthServiceExchangeApiOAuthCodeRequest,
    ),
  );
}

/** @internal */
export const ApiOAuthServiceExchangeApiOAuthCodeResponse$inboundSchema:
  z.ZodMiniType<ApiOAuthServiceExchangeApiOAuthCodeResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicApiOauthExchangeApiOAuthCodeResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function apiOAuthServiceExchangeApiOAuthCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiOAuthServiceExchangeApiOAuthCodeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiOAuthServiceExchangeApiOAuthCodeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiOAuthServiceExchangeApiOAuthCodeResponse' from JSON`,
  );
}
