/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AppServiceGetAppMemberStateRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAppGetAppMemberStateRequest;
};

export type AppServiceGetAppMemberStateResponse =
  | models.TextqlRpcPublicAppGetAppMemberStateResponse
  | models.ConnectError;

/** @internal */
export type AppServiceGetAppMemberStateRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAppGetAppMemberStateRequest$Outbound;
};

/** @internal */
export const AppServiceGetAppMemberStateRequest$outboundSchema: z.ZodMiniType<
  AppServiceGetAppMemberStateRequest$Outbound,
  AppServiceGetAppMemberStateRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicAppGetAppMemberStateRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function appServiceGetAppMemberStateRequestToJSON(
  appServiceGetAppMemberStateRequest: AppServiceGetAppMemberStateRequest,
): string {
  return JSON.stringify(
    AppServiceGetAppMemberStateRequest$outboundSchema.parse(
      appServiceGetAppMemberStateRequest,
    ),
  );
}

/** @internal */
export const AppServiceGetAppMemberStateResponse$inboundSchema: z.ZodMiniType<
  AppServiceGetAppMemberStateResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicAppGetAppMemberStateResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function appServiceGetAppMemberStateResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppServiceGetAppMemberStateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AppServiceGetAppMemberStateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppServiceGetAppMemberStateResponse' from JSON`,
  );
}
