/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AppServiceVerifyAppRenderRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAppVerifyAppRenderRequest;
};

export type AppServiceVerifyAppRenderResponse =
  | models.TextqlRpcPublicAppVerifyAppRenderResponse
  | models.ConnectError;

/** @internal */
export type AppServiceVerifyAppRenderRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAppVerifyAppRenderRequest$Outbound;
};

/** @internal */
export const AppServiceVerifyAppRenderRequest$outboundSchema: z.ZodMiniType<
  AppServiceVerifyAppRenderRequest$Outbound,
  AppServiceVerifyAppRenderRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicAppVerifyAppRenderRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function appServiceVerifyAppRenderRequestToJSON(
  appServiceVerifyAppRenderRequest: AppServiceVerifyAppRenderRequest,
): string {
  return JSON.stringify(
    AppServiceVerifyAppRenderRequest$outboundSchema.parse(
      appServiceVerifyAppRenderRequest,
    ),
  );
}

/** @internal */
export const AppServiceVerifyAppRenderResponse$inboundSchema: z.ZodMiniType<
  AppServiceVerifyAppRenderResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicAppVerifyAppRenderResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function appServiceVerifyAppRenderResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppServiceVerifyAppRenderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppServiceVerifyAppRenderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppServiceVerifyAppRenderResponse' from JSON`,
  );
}
