/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AppServiceSetFavoriteRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAppSetFavoriteRequest;
};

export type AppServiceSetFavoriteResponse =
  | models.TextqlRpcPublicAppSetFavoriteResponse
  | models.ConnectError;

/** @internal */
export type AppServiceSetFavoriteRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAppSetFavoriteRequest$Outbound;
};

/** @internal */
export const AppServiceSetFavoriteRequest$outboundSchema: z.ZodMiniType<
  AppServiceSetFavoriteRequest$Outbound,
  AppServiceSetFavoriteRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicAppSetFavoriteRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function appServiceSetFavoriteRequestToJSON(
  appServiceSetFavoriteRequest: AppServiceSetFavoriteRequest,
): string {
  return JSON.stringify(
    AppServiceSetFavoriteRequest$outboundSchema.parse(
      appServiceSetFavoriteRequest,
    ),
  );
}

/** @internal */
export const AppServiceSetFavoriteResponse$inboundSchema: z.ZodMiniType<
  AppServiceSetFavoriteResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicAppSetFavoriteResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function appServiceSetFavoriteResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppServiceSetFavoriteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppServiceSetFavoriteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppServiceSetFavoriteResponse' from JSON`,
  );
}
