/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AuditLogServiceDeleteOtlpExportConfigRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAuditLogDeleteOtlpExportConfigRequest;
};

export type AuditLogServiceDeleteOtlpExportConfigResponse =
  | models.TextqlRpcPublicAuditLogDeleteOtlpExportConfigResponse
  | models.ConnectError;

/** @internal */
export type AuditLogServiceDeleteOtlpExportConfigRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAuditLogDeleteOtlpExportConfigRequest$Outbound;
};

/** @internal */
export const AuditLogServiceDeleteOtlpExportConfigRequest$outboundSchema:
  z.ZodMiniType<
    AuditLogServiceDeleteOtlpExportConfigRequest$Outbound,
    AuditLogServiceDeleteOtlpExportConfigRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicAuditLogDeleteOtlpExportConfigRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function auditLogServiceDeleteOtlpExportConfigRequestToJSON(
  auditLogServiceDeleteOtlpExportConfigRequest:
    AuditLogServiceDeleteOtlpExportConfigRequest,
): string {
  return JSON.stringify(
    AuditLogServiceDeleteOtlpExportConfigRequest$outboundSchema.parse(
      auditLogServiceDeleteOtlpExportConfigRequest,
    ),
  );
}

/** @internal */
export const AuditLogServiceDeleteOtlpExportConfigResponse$inboundSchema:
  z.ZodMiniType<AuditLogServiceDeleteOtlpExportConfigResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicAuditLogDeleteOtlpExportConfigResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function auditLogServiceDeleteOtlpExportConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AuditLogServiceDeleteOtlpExportConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuditLogServiceDeleteOtlpExportConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuditLogServiceDeleteOtlpExportConfigResponse' from JSON`,
  );
}
