/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AuditLogServiceGetS3ExportConfigRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicAuditLogGetS3ExportConfigRequest;
};

export type AuditLogServiceGetS3ExportConfigResponse =
  | models.TextqlRpcPublicAuditLogGetS3ExportConfigResponse
  | models.ConnectError;

/** @internal */
export type AuditLogServiceGetS3ExportConfigRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicAuditLogGetS3ExportConfigRequest$Outbound;
};

/** @internal */
export const AuditLogServiceGetS3ExportConfigRequest$outboundSchema:
  z.ZodMiniType<
    AuditLogServiceGetS3ExportConfigRequest$Outbound,
    AuditLogServiceGetS3ExportConfigRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicAuditLogGetS3ExportConfigRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function auditLogServiceGetS3ExportConfigRequestToJSON(
  auditLogServiceGetS3ExportConfigRequest:
    AuditLogServiceGetS3ExportConfigRequest,
): string {
  return JSON.stringify(
    AuditLogServiceGetS3ExportConfigRequest$outboundSchema.parse(
      auditLogServiceGetS3ExportConfigRequest,
    ),
  );
}

/** @internal */
export const AuditLogServiceGetS3ExportConfigResponse$inboundSchema:
  z.ZodMiniType<AuditLogServiceGetS3ExportConfigResponse, unknown> = smartUnion(
    [
      models.TextqlRpcPublicAuditLogGetS3ExportConfigResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ],
  );

export function auditLogServiceGetS3ExportConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AuditLogServiceGetS3ExportConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AuditLogServiceGetS3ExportConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AuditLogServiceGetS3ExportConfigResponse' from JSON`,
  );
}
