/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChatServiceDismissQuestionsRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicChatDismissQuestionsRequest;
};

export type ChatServiceDismissQuestionsResponse =
  | models.TextqlRpcPublicChatDismissQuestionsResponse
  | models.ConnectError;

/** @internal */
export type ChatServiceDismissQuestionsRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicChatDismissQuestionsRequest$Outbound;
};

/** @internal */
export const ChatServiceDismissQuestionsRequest$outboundSchema: z.ZodMiniType<
  ChatServiceDismissQuestionsRequest$Outbound,
  ChatServiceDismissQuestionsRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z.literal(1),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicChatDismissQuestionsRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function chatServiceDismissQuestionsRequestToJSON(
  chatServiceDismissQuestionsRequest: ChatServiceDismissQuestionsRequest,
): string {
  return JSON.stringify(
    ChatServiceDismissQuestionsRequest$outboundSchema.parse(
      chatServiceDismissQuestionsRequest,
    ),
  );
}

/** @internal */
export const ChatServiceDismissQuestionsResponse$inboundSchema: z.ZodMiniType<
  ChatServiceDismissQuestionsResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicChatDismissQuestionsResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function chatServiceDismissQuestionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatServiceDismissQuestionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatServiceDismissQuestionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatServiceDismissQuestionsResponse' from JSON`,
  );
}
