/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChatServiceCancelStreamRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicChatCancelStreamRequest;
};

export type ChatServiceCancelStreamResponse =
  | models.TextqlRpcPublicChatCancelStreamResponse
  | models.ConnectError;

/** @internal */
export type ChatServiceCancelStreamRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicChatCancelStreamRequest$Outbound;
};

/** @internal */
export const ChatServiceCancelStreamRequest$outboundSchema: z.ZodMiniType<
  ChatServiceCancelStreamRequest$Outbound,
  ChatServiceCancelStreamRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicChatCancelStreamRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function chatServiceCancelStreamRequestToJSON(
  chatServiceCancelStreamRequest: ChatServiceCancelStreamRequest,
): string {
  return JSON.stringify(
    ChatServiceCancelStreamRequest$outboundSchema.parse(
      chatServiceCancelStreamRequest,
    ),
  );
}

/** @internal */
export const ChatServiceCancelStreamResponse$inboundSchema: z.ZodMiniType<
  ChatServiceCancelStreamResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicChatCancelStreamResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function chatServiceCancelStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatServiceCancelStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatServiceCancelStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatServiceCancelStreamResponse' from JSON`,
  );
}
