/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChatServiceDuplicateChatRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicChatDuplicateChatRequest;
};

export type ChatServiceDuplicateChatResponse =
  | models.TextqlRpcPublicChatDuplicateChatResponse
  | models.ConnectError;

/** @internal */
export type ChatServiceDuplicateChatRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicChatDuplicateChatRequest$Outbound;
};

/** @internal */
export const ChatServiceDuplicateChatRequest$outboundSchema: z.ZodMiniType<
  ChatServiceDuplicateChatRequest$Outbound,
  ChatServiceDuplicateChatRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z.literal(1),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicChatDuplicateChatRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function chatServiceDuplicateChatRequestToJSON(
  chatServiceDuplicateChatRequest: ChatServiceDuplicateChatRequest,
): string {
  return JSON.stringify(
    ChatServiceDuplicateChatRequest$outboundSchema.parse(
      chatServiceDuplicateChatRequest,
    ),
  );
}

/** @internal */
export const ChatServiceDuplicateChatResponse$inboundSchema: z.ZodMiniType<
  ChatServiceDuplicateChatResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicChatDuplicateChatResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function chatServiceDuplicateChatResponseFromJSON(
  jsonString: string,
): SafeParseResult<ChatServiceDuplicateChatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatServiceDuplicateChatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatServiceDuplicateChatResponse' from JSON`,
  );
}
