/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ChatServiceApproveContextPromptChangeRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicChatApproveContextPromptChangeRequest;
};

export type ChatServiceApproveContextPromptChangeResponse =
  | models.TextqlRpcPublicChatApproveContextPromptChangeResponse
  | models.ConnectError;

/** @internal */
export type ChatServiceApproveContextPromptChangeRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicChatApproveContextPromptChangeRequest$Outbound;
};

/** @internal */
export const ChatServiceApproveContextPromptChangeRequest$outboundSchema:
  z.ZodMiniType<
    ChatServiceApproveContextPromptChangeRequest$Outbound,
    ChatServiceApproveContextPromptChangeRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicChatApproveContextPromptChangeRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function chatServiceApproveContextPromptChangeRequestToJSON(
  chatServiceApproveContextPromptChangeRequest:
    ChatServiceApproveContextPromptChangeRequest,
): string {
  return JSON.stringify(
    ChatServiceApproveContextPromptChangeRequest$outboundSchema.parse(
      chatServiceApproveContextPromptChangeRequest,
    ),
  );
}

/** @internal */
export const ChatServiceApproveContextPromptChangeResponse$inboundSchema:
  z.ZodMiniType<ChatServiceApproveContextPromptChangeResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicChatApproveContextPromptChangeResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function chatServiceApproveContextPromptChangeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ChatServiceApproveContextPromptChangeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChatServiceApproveContextPromptChangeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChatServiceApproveContextPromptChangeResponse' from JSON`,
  );
}
