/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ConnectorServiceGetConnectorStatsRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicConnectorGetConnectorStatsRequest;
};

export type ConnectorServiceGetConnectorStatsResponse =
  | models.TextqlRpcPublicConnectorGetConnectorStatsResponse
  | models.ConnectError;

/** @internal */
export type ConnectorServiceGetConnectorStatsRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicConnectorGetConnectorStatsRequest$Outbound;
};

/** @internal */
export const ConnectorServiceGetConnectorStatsRequest$outboundSchema:
  z.ZodMiniType<
    ConnectorServiceGetConnectorStatsRequest$Outbound,
    ConnectorServiceGetConnectorStatsRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicConnectorGetConnectorStatsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function connectorServiceGetConnectorStatsRequestToJSON(
  connectorServiceGetConnectorStatsRequest:
    ConnectorServiceGetConnectorStatsRequest,
): string {
  return JSON.stringify(
    ConnectorServiceGetConnectorStatsRequest$outboundSchema.parse(
      connectorServiceGetConnectorStatsRequest,
    ),
  );
}

/** @internal */
export const ConnectorServiceGetConnectorStatsResponse$inboundSchema:
  z.ZodMiniType<ConnectorServiceGetConnectorStatsResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicConnectorGetConnectorStatsResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function connectorServiceGetConnectorStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ConnectorServiceGetConnectorStatsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ConnectorServiceGetConnectorStatsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ConnectorServiceGetConnectorStatsResponse' from JSON`,
  );
}
