/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DashboardServiceCreateDashboardFolderRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicDashboardCreateDashboardFolderRequest;
};

export type DashboardServiceCreateDashboardFolderResponse =
  | models.TextqlRpcPublicDashboardCreateDashboardFolderResponse
  | models.ConnectError;

/** @internal */
export type DashboardServiceCreateDashboardFolderRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicDashboardCreateDashboardFolderRequest$Outbound;
};

/** @internal */
export const DashboardServiceCreateDashboardFolderRequest$outboundSchema:
  z.ZodMiniType<
    DashboardServiceCreateDashboardFolderRequest$Outbound,
    DashboardServiceCreateDashboardFolderRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicDashboardCreateDashboardFolderRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function dashboardServiceCreateDashboardFolderRequestToJSON(
  dashboardServiceCreateDashboardFolderRequest:
    DashboardServiceCreateDashboardFolderRequest,
): string {
  return JSON.stringify(
    DashboardServiceCreateDashboardFolderRequest$outboundSchema.parse(
      dashboardServiceCreateDashboardFolderRequest,
    ),
  );
}

/** @internal */
export const DashboardServiceCreateDashboardFolderResponse$inboundSchema:
  z.ZodMiniType<DashboardServiceCreateDashboardFolderResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicDashboardCreateDashboardFolderResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function dashboardServiceCreateDashboardFolderResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DashboardServiceCreateDashboardFolderResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DashboardServiceCreateDashboardFolderResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DashboardServiceCreateDashboardFolderResponse' from JSON`,
  );
}
