/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DashboardServiceListDashboardsRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicDashboardListDashboardsRequest;
};

export type DashboardServiceListDashboardsResponse =
  | models.TextqlRpcPublicDashboardListDashboardsResponse
  | models.ConnectError;

/** @internal */
export type DashboardServiceListDashboardsRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicDashboardListDashboardsRequest$Outbound;
};

/** @internal */
export const DashboardServiceListDashboardsRequest$outboundSchema:
  z.ZodMiniType<
    DashboardServiceListDashboardsRequest$Outbound,
    DashboardServiceListDashboardsRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicDashboardListDashboardsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function dashboardServiceListDashboardsRequestToJSON(
  dashboardServiceListDashboardsRequest: DashboardServiceListDashboardsRequest,
): string {
  return JSON.stringify(
    DashboardServiceListDashboardsRequest$outboundSchema.parse(
      dashboardServiceListDashboardsRequest,
    ),
  );
}

/** @internal */
export const DashboardServiceListDashboardsResponse$inboundSchema:
  z.ZodMiniType<DashboardServiceListDashboardsResponse, unknown> = smartUnion([
    models.TextqlRpcPublicDashboardListDashboardsResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function dashboardServiceListDashboardsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DashboardServiceListDashboardsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DashboardServiceListDashboardsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DashboardServiceListDashboardsResponse' from JSON`,
  );
}
