/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DashboardServiceRegenerateScreenshotRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicDashboardRegenerateScreenshotRequest;
};

export type DashboardServiceRegenerateScreenshotResponse =
  | models.TextqlRpcPublicDashboardRegenerateScreenshotResponse
  | models.ConnectError;

/** @internal */
export type DashboardServiceRegenerateScreenshotRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicDashboardRegenerateScreenshotRequest$Outbound;
};

/** @internal */
export const DashboardServiceRegenerateScreenshotRequest$outboundSchema:
  z.ZodMiniType<
    DashboardServiceRegenerateScreenshotRequest$Outbound,
    DashboardServiceRegenerateScreenshotRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicDashboardRegenerateScreenshotRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function dashboardServiceRegenerateScreenshotRequestToJSON(
  dashboardServiceRegenerateScreenshotRequest:
    DashboardServiceRegenerateScreenshotRequest,
): string {
  return JSON.stringify(
    DashboardServiceRegenerateScreenshotRequest$outboundSchema.parse(
      dashboardServiceRegenerateScreenshotRequest,
    ),
  );
}

/** @internal */
export const DashboardServiceRegenerateScreenshotResponse$inboundSchema:
  z.ZodMiniType<DashboardServiceRegenerateScreenshotResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicDashboardRegenerateScreenshotResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function dashboardServiceRegenerateScreenshotResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DashboardServiceRegenerateScreenshotResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DashboardServiceRegenerateScreenshotResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DashboardServiceRegenerateScreenshotResponse' from JSON`,
  );
}
