/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type DashboardServiceCreateDashboardRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicDashboardCreateDashboardRequest;
};

export type DashboardServiceCreateDashboardResponse =
  | models.TextqlRpcPublicDashboardCreateDashboardResponse
  | models.ConnectError;

/** @internal */
export type DashboardServiceCreateDashboardRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicDashboardCreateDashboardRequest$Outbound;
};

/** @internal */
export const DashboardServiceCreateDashboardRequest$outboundSchema:
  z.ZodMiniType<
    DashboardServiceCreateDashboardRequest$Outbound,
    DashboardServiceCreateDashboardRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicDashboardCreateDashboardRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function dashboardServiceCreateDashboardRequestToJSON(
  dashboardServiceCreateDashboardRequest:
    DashboardServiceCreateDashboardRequest,
): string {
  return JSON.stringify(
    DashboardServiceCreateDashboardRequest$outboundSchema.parse(
      dashboardServiceCreateDashboardRequest,
    ),
  );
}

/** @internal */
export const DashboardServiceCreateDashboardResponse$inboundSchema:
  z.ZodMiniType<DashboardServiceCreateDashboardResponse, unknown> = smartUnion([
    models.TextqlRpcPublicDashboardCreateDashboardResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function dashboardServiceCreateDashboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DashboardServiceCreateDashboardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DashboardServiceCreateDashboardResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DashboardServiceCreateDashboardResponse' from JSON`,
  );
}
