/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceCreateContextPatchAutoApproveRuleRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleRequest;
};

export type LibraryServiceCreateContextPatchAutoApproveRuleResponse =
  | models.TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceCreateContextPatchAutoApproveRuleRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body:
    models.TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleRequest$Outbound;
};

/** @internal */
export const LibraryServiceCreateContextPatchAutoApproveRuleRequest$outboundSchema:
  z.ZodMiniType<
    LibraryServiceCreateContextPatchAutoApproveRuleRequest$Outbound,
    LibraryServiceCreateContextPatchAutoApproveRuleRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function libraryServiceCreateContextPatchAutoApproveRuleRequestToJSON(
  libraryServiceCreateContextPatchAutoApproveRuleRequest:
    LibraryServiceCreateContextPatchAutoApproveRuleRequest,
): string {
  return JSON.stringify(
    LibraryServiceCreateContextPatchAutoApproveRuleRequest$outboundSchema.parse(
      libraryServiceCreateContextPatchAutoApproveRuleRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceCreateContextPatchAutoApproveRuleResponse$inboundSchema:
  z.ZodMiniType<
    LibraryServiceCreateContextPatchAutoApproveRuleResponse,
    unknown
  > = smartUnion([
    models
      .TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function libraryServiceCreateContextPatchAutoApproveRuleResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  LibraryServiceCreateContextPatchAutoApproveRuleResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceCreateContextPatchAutoApproveRuleResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'LibraryServiceCreateContextPatchAutoApproveRuleResponse' from JSON`,
  );
}
