/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceValidateConfigRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesValidateConfigRequest;
};

export type LibraryServiceValidateConfigResponse =
  | models.TextqlRpcPublicPatchesValidateConfigResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceValidateConfigRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesValidateConfigRequest$Outbound;
};

/** @internal */
export const LibraryServiceValidateConfigRequest$outboundSchema: z.ZodMiniType<
  LibraryServiceValidateConfigRequest$Outbound,
  LibraryServiceValidateConfigRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z.literal(1),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicPatchesValidateConfigRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function libraryServiceValidateConfigRequestToJSON(
  libraryServiceValidateConfigRequest: LibraryServiceValidateConfigRequest,
): string {
  return JSON.stringify(
    LibraryServiceValidateConfigRequest$outboundSchema.parse(
      libraryServiceValidateConfigRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceValidateConfigResponse$inboundSchema: z.ZodMiniType<
  LibraryServiceValidateConfigResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicPatchesValidateConfigResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function libraryServiceValidateConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<LibraryServiceValidateConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceValidateConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LibraryServiceValidateConfigResponse' from JSON`,
  );
}
