/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceListLibraryEntriesRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesListLibraryEntriesRequest;
};

export type LibraryServiceListLibraryEntriesResponse =
  | models.TextqlRpcPublicPatchesListLibraryEntriesResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceListLibraryEntriesRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesListLibraryEntriesRequest$Outbound;
};

/** @internal */
export const LibraryServiceListLibraryEntriesRequest$outboundSchema:
  z.ZodMiniType<
    LibraryServiceListLibraryEntriesRequest$Outbound,
    LibraryServiceListLibraryEntriesRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicPatchesListLibraryEntriesRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function libraryServiceListLibraryEntriesRequestToJSON(
  libraryServiceListLibraryEntriesRequest:
    LibraryServiceListLibraryEntriesRequest,
): string {
  return JSON.stringify(
    LibraryServiceListLibraryEntriesRequest$outboundSchema.parse(
      libraryServiceListLibraryEntriesRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceListLibraryEntriesResponse$inboundSchema:
  z.ZodMiniType<LibraryServiceListLibraryEntriesResponse, unknown> = smartUnion(
    [
      models.TextqlRpcPublicPatchesListLibraryEntriesResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ],
  );

export function libraryServiceListLibraryEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  LibraryServiceListLibraryEntriesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceListLibraryEntriesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LibraryServiceListLibraryEntriesResponse' from JSON`,
  );
}
