/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceListChatsForFileRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesListChatsForFileRequest;
};

export type LibraryServiceListChatsForFileResponse =
  | models.TextqlRpcPublicPatchesListChatsForFileResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceListChatsForFileRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesListChatsForFileRequest$Outbound;
};

/** @internal */
export const LibraryServiceListChatsForFileRequest$outboundSchema:
  z.ZodMiniType<
    LibraryServiceListChatsForFileRequest$Outbound,
    LibraryServiceListChatsForFileRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesListChatsForFileRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function libraryServiceListChatsForFileRequestToJSON(
  libraryServiceListChatsForFileRequest: LibraryServiceListChatsForFileRequest,
): string {
  return JSON.stringify(
    LibraryServiceListChatsForFileRequest$outboundSchema.parse(
      libraryServiceListChatsForFileRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceListChatsForFileResponse$inboundSchema:
  z.ZodMiniType<LibraryServiceListChatsForFileResponse, unknown> = smartUnion([
    models.TextqlRpcPublicPatchesListChatsForFileResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function libraryServiceListChatsForFileResponseFromJSON(
  jsonString: string,
): SafeParseResult<LibraryServiceListChatsForFileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceListChatsForFileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LibraryServiceListChatsForFileResponse' from JSON`,
  );
}
