/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceGetLibraryOwnersRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetLibraryOwnersRequest;
};

export type LibraryServiceGetLibraryOwnersResponse =
  | models.TextqlRpcPublicPatchesGetLibraryOwnersResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceGetLibraryOwnersRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetLibraryOwnersRequest$Outbound;
};

/** @internal */
export const LibraryServiceGetLibraryOwnersRequest$outboundSchema:
  z.ZodMiniType<
    LibraryServiceGetLibraryOwnersRequest$Outbound,
    LibraryServiceGetLibraryOwnersRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesGetLibraryOwnersRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function libraryServiceGetLibraryOwnersRequestToJSON(
  libraryServiceGetLibraryOwnersRequest: LibraryServiceGetLibraryOwnersRequest,
): string {
  return JSON.stringify(
    LibraryServiceGetLibraryOwnersRequest$outboundSchema.parse(
      libraryServiceGetLibraryOwnersRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceGetLibraryOwnersResponse$inboundSchema:
  z.ZodMiniType<LibraryServiceGetLibraryOwnersResponse, unknown> = smartUnion([
    models.TextqlRpcPublicPatchesGetLibraryOwnersResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function libraryServiceGetLibraryOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<LibraryServiceGetLibraryOwnersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceGetLibraryOwnersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LibraryServiceGetLibraryOwnersResponse' from JSON`,
  );
}
