/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceCreateLibraryDirectoryRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesCreateLibraryDirectoryRequest;
};

export type LibraryServiceCreateLibraryDirectoryResponse =
  | models.TextqlRpcPublicPatchesCreateLibraryDirectoryResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceCreateLibraryDirectoryRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesCreateLibraryDirectoryRequest$Outbound;
};

/** @internal */
export const LibraryServiceCreateLibraryDirectoryRequest$outboundSchema:
  z.ZodMiniType<
    LibraryServiceCreateLibraryDirectoryRequest$Outbound,
    LibraryServiceCreateLibraryDirectoryRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPatchesCreateLibraryDirectoryRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function libraryServiceCreateLibraryDirectoryRequestToJSON(
  libraryServiceCreateLibraryDirectoryRequest:
    LibraryServiceCreateLibraryDirectoryRequest,
): string {
  return JSON.stringify(
    LibraryServiceCreateLibraryDirectoryRequest$outboundSchema.parse(
      libraryServiceCreateLibraryDirectoryRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceCreateLibraryDirectoryResponse$inboundSchema:
  z.ZodMiniType<LibraryServiceCreateLibraryDirectoryResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesCreateLibraryDirectoryResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function libraryServiceCreateLibraryDirectoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  LibraryServiceCreateLibraryDirectoryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceCreateLibraryDirectoryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'LibraryServiceCreateLibraryDirectoryResponse' from JSON`,
  );
}
