/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type LibraryServiceGetLibraryFileRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetLibraryFileRequest;
};

export type LibraryServiceGetLibraryFileResponse =
  | models.TextqlRpcPublicPatchesGetLibraryFileResponse
  | models.ConnectError;

/** @internal */
export type LibraryServiceGetLibraryFileRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetLibraryFileRequest$Outbound;
};

/** @internal */
export const LibraryServiceGetLibraryFileRequest$outboundSchema: z.ZodMiniType<
  LibraryServiceGetLibraryFileRequest$Outbound,
  LibraryServiceGetLibraryFileRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicPatchesGetLibraryFileRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function libraryServiceGetLibraryFileRequestToJSON(
  libraryServiceGetLibraryFileRequest: LibraryServiceGetLibraryFileRequest,
): string {
  return JSON.stringify(
    LibraryServiceGetLibraryFileRequest$outboundSchema.parse(
      libraryServiceGetLibraryFileRequest,
    ),
  );
}

/** @internal */
export const LibraryServiceGetLibraryFileResponse$inboundSchema: z.ZodMiniType<
  LibraryServiceGetLibraryFileResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicPatchesGetLibraryFileResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function libraryServiceGetLibraryFileResponseFromJSON(
  jsonString: string,
): SafeParseResult<LibraryServiceGetLibraryFileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LibraryServiceGetLibraryFileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LibraryServiceGetLibraryFileResponse' from JSON`,
  );
}
