/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type MCPServiceUpsertMCPServersRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicMCPUpsertMCPServersRequest;
};

export type MCPServiceUpsertMCPServersResponse =
  | models.TextqlRpcPublicMCPUpsertMCPServersResponse
  | models.ConnectError;

/** @internal */
export type MCPServiceUpsertMCPServersRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicMCPUpsertMCPServersRequest$Outbound;
};

/** @internal */
export const MCPServiceUpsertMCPServersRequest$outboundSchema: z.ZodMiniType<
  MCPServiceUpsertMCPServersRequest$Outbound,
  MCPServiceUpsertMCPServersRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicMCPUpsertMCPServersRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function mcpServiceUpsertMCPServersRequestToJSON(
  mcpServiceUpsertMCPServersRequest: MCPServiceUpsertMCPServersRequest,
): string {
  return JSON.stringify(
    MCPServiceUpsertMCPServersRequest$outboundSchema.parse(
      mcpServiceUpsertMCPServersRequest,
    ),
  );
}

/** @internal */
export const MCPServiceUpsertMCPServersResponse$inboundSchema: z.ZodMiniType<
  MCPServiceUpsertMCPServersResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicMCPUpsertMCPServersResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function mcpServiceUpsertMCPServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<MCPServiceUpsertMCPServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MCPServiceUpsertMCPServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MCPServiceUpsertMCPServersResponse' from JSON`,
  );
}
