/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type MetricsExportServiceTestMetricsExportConnectionRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicMetricsExportTestMetricsExportConnectionRequest;
};

export type MetricsExportServiceTestMetricsExportConnectionResponse =
  | models.TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse
  | models.ConnectError;

/** @internal */
export type MetricsExportServiceTestMetricsExportConnectionRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body:
    models.TextqlRpcPublicMetricsExportTestMetricsExportConnectionRequest$Outbound;
};

/** @internal */
export const MetricsExportServiceTestMetricsExportConnectionRequest$outboundSchema:
  z.ZodMiniType<
    MetricsExportServiceTestMetricsExportConnectionRequest$Outbound,
    MetricsExportServiceTestMetricsExportConnectionRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicMetricsExportTestMetricsExportConnectionRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function metricsExportServiceTestMetricsExportConnectionRequestToJSON(
  metricsExportServiceTestMetricsExportConnectionRequest:
    MetricsExportServiceTestMetricsExportConnectionRequest,
): string {
  return JSON.stringify(
    MetricsExportServiceTestMetricsExportConnectionRequest$outboundSchema.parse(
      metricsExportServiceTestMetricsExportConnectionRequest,
    ),
  );
}

/** @internal */
export const MetricsExportServiceTestMetricsExportConnectionResponse$inboundSchema:
  z.ZodMiniType<
    MetricsExportServiceTestMetricsExportConnectionResponse,
    unknown
  > = smartUnion([
    models
      .TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function metricsExportServiceTestMetricsExportConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  MetricsExportServiceTestMetricsExportConnectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MetricsExportServiceTestMetricsExportConnectionResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'MetricsExportServiceTestMetricsExportConnectionResponse' from JSON`,
  );
}
