/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ObservabilityServiceSetTopicTagFeedbackRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicObserveSetTopicTagFeedbackRequest;
};

export type ObservabilityServiceSetTopicTagFeedbackResponse =
  | models.TextqlRpcPublicObserveSetTopicTagFeedbackResponse
  | models.ConnectError;

/** @internal */
export type ObservabilityServiceSetTopicTagFeedbackRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicObserveSetTopicTagFeedbackRequest$Outbound;
};

/** @internal */
export const ObservabilityServiceSetTopicTagFeedbackRequest$outboundSchema:
  z.ZodMiniType<
    ObservabilityServiceSetTopicTagFeedbackRequest$Outbound,
    ObservabilityServiceSetTopicTagFeedbackRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicObserveSetTopicTagFeedbackRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function observabilityServiceSetTopicTagFeedbackRequestToJSON(
  observabilityServiceSetTopicTagFeedbackRequest:
    ObservabilityServiceSetTopicTagFeedbackRequest,
): string {
  return JSON.stringify(
    ObservabilityServiceSetTopicTagFeedbackRequest$outboundSchema.parse(
      observabilityServiceSetTopicTagFeedbackRequest,
    ),
  );
}

/** @internal */
export const ObservabilityServiceSetTopicTagFeedbackResponse$inboundSchema:
  z.ZodMiniType<ObservabilityServiceSetTopicTagFeedbackResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicObserveSetTopicTagFeedbackResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function observabilityServiceSetTopicTagFeedbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ObservabilityServiceSetTopicTagFeedbackResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ObservabilityServiceSetTopicTagFeedbackResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ObservabilityServiceSetTopicTagFeedbackResponse' from JSON`,
  );
}
