/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ObservabilityServiceUpdateCustomTopicRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicObserveUpdateCustomTopicRequest;
};

export type ObservabilityServiceUpdateCustomTopicResponse =
  | models.TextqlRpcPublicObserveCustomTopicResponse
  | models.ConnectError;

/** @internal */
export type ObservabilityServiceUpdateCustomTopicRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicObserveUpdateCustomTopicRequest$Outbound;
};

/** @internal */
export const ObservabilityServiceUpdateCustomTopicRequest$outboundSchema:
  z.ZodMiniType<
    ObservabilityServiceUpdateCustomTopicRequest$Outbound,
    ObservabilityServiceUpdateCustomTopicRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicObserveUpdateCustomTopicRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function observabilityServiceUpdateCustomTopicRequestToJSON(
  observabilityServiceUpdateCustomTopicRequest:
    ObservabilityServiceUpdateCustomTopicRequest,
): string {
  return JSON.stringify(
    ObservabilityServiceUpdateCustomTopicRequest$outboundSchema.parse(
      observabilityServiceUpdateCustomTopicRequest,
    ),
  );
}

/** @internal */
export const ObservabilityServiceUpdateCustomTopicResponse$inboundSchema:
  z.ZodMiniType<ObservabilityServiceUpdateCustomTopicResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicObserveCustomTopicResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function observabilityServiceUpdateCustomTopicResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ObservabilityServiceUpdateCustomTopicResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ObservabilityServiceUpdateCustomTopicResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ObservabilityServiceUpdateCustomTopicResponse' from JSON`,
  );
}
