/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ObservabilityServiceGetBackfillPreviewRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicObserveGetBackfillPreviewRequest;
};

export type ObservabilityServiceGetBackfillPreviewResponse =
  | models.TextqlRpcPublicObserveGetBackfillPreviewResponse
  | models.ConnectError;

/** @internal */
export type ObservabilityServiceGetBackfillPreviewRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicObserveGetBackfillPreviewRequest$Outbound;
};

/** @internal */
export const ObservabilityServiceGetBackfillPreviewRequest$outboundSchema:
  z.ZodMiniType<
    ObservabilityServiceGetBackfillPreviewRequest$Outbound,
    ObservabilityServiceGetBackfillPreviewRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicObserveGetBackfillPreviewRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function observabilityServiceGetBackfillPreviewRequestToJSON(
  observabilityServiceGetBackfillPreviewRequest:
    ObservabilityServiceGetBackfillPreviewRequest,
): string {
  return JSON.stringify(
    ObservabilityServiceGetBackfillPreviewRequest$outboundSchema.parse(
      observabilityServiceGetBackfillPreviewRequest,
    ),
  );
}

/** @internal */
export const ObservabilityServiceGetBackfillPreviewResponse$inboundSchema:
  z.ZodMiniType<ObservabilityServiceGetBackfillPreviewResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicObserveGetBackfillPreviewResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function observabilityServiceGetBackfillPreviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ObservabilityServiceGetBackfillPreviewResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ObservabilityServiceGetBackfillPreviewResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ObservabilityServiceGetBackfillPreviewResponse' from JSON`,
  );
}
