/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceGetPatchRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetPatchRequest;
};

export type OntologyManagementServiceGetPatchResponse =
  | models.TextqlRpcPublicPatchesPatch
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceGetPatchRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetPatchRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceGetPatchRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceGetPatchRequest$Outbound,
    OntologyManagementServiceGetPatchRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesGetPatchRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceGetPatchRequestToJSON(
  ontologyManagementServiceGetPatchRequest:
    OntologyManagementServiceGetPatchRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceGetPatchRequest$outboundSchema.parse(
      ontologyManagementServiceGetPatchRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceGetPatchResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceGetPatchResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesPatch$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceGetPatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceGetPatchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceGetPatchResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceGetPatchResponse' from JSON`,
  );
}
