/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceListGoldenFilesRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesListGoldenFilesRequest;
};

export type OntologyManagementServiceListGoldenFilesResponse =
  | models.TextqlRpcPublicPatchesListGoldenFilesResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceListGoldenFilesRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesListGoldenFilesRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceListGoldenFilesRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceListGoldenFilesRequest$Outbound,
    OntologyManagementServiceListGoldenFilesRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesListGoldenFilesRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceListGoldenFilesRequestToJSON(
  ontologyManagementServiceListGoldenFilesRequest:
    OntologyManagementServiceListGoldenFilesRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceListGoldenFilesRequest$outboundSchema.parse(
      ontologyManagementServiceListGoldenFilesRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceListGoldenFilesResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceListGoldenFilesResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesListGoldenFilesResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceListGoldenFilesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceListGoldenFilesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceListGoldenFilesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceListGoldenFilesResponse' from JSON`,
  );
}
