/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceRevertPatchRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesRevertPatchRequest;
};

export type OntologyManagementServiceRevertPatchResponse =
  | models.TextqlRpcPublicPatchesRevertPatchResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceRevertPatchRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesRevertPatchRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceRevertPatchRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceRevertPatchRequest$Outbound,
    OntologyManagementServiceRevertPatchRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesRevertPatchRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceRevertPatchRequestToJSON(
  ontologyManagementServiceRevertPatchRequest:
    OntologyManagementServiceRevertPatchRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceRevertPatchRequest$outboundSchema.parse(
      ontologyManagementServiceRevertPatchRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceRevertPatchResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceRevertPatchResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesRevertPatchResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceRevertPatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceRevertPatchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceRevertPatchResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceRevertPatchResponse' from JSON`,
  );
}
