/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceGetOntologySizeTimelineRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetOntologySizeTimelineRequest;
};

export type OntologyManagementServiceGetOntologySizeTimelineResponse =
  | models.TextqlRpcPublicPatchesGetOntologySizeTimelineResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceGetOntologySizeTimelineRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetOntologySizeTimelineRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceGetOntologySizeTimelineRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceGetOntologySizeTimelineRequest$Outbound,
    OntologyManagementServiceGetOntologySizeTimelineRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPatchesGetOntologySizeTimelineRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceGetOntologySizeTimelineRequestToJSON(
  ontologyManagementServiceGetOntologySizeTimelineRequest:
    OntologyManagementServiceGetOntologySizeTimelineRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceGetOntologySizeTimelineRequest$outboundSchema
      .parse(ontologyManagementServiceGetOntologySizeTimelineRequest),
  );
}

/** @internal */
export const OntologyManagementServiceGetOntologySizeTimelineResponse$inboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceGetOntologySizeTimelineResponse,
    unknown
  > = smartUnion([
    models.TextqlRpcPublicPatchesGetOntologySizeTimelineResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function ontologyManagementServiceGetOntologySizeTimelineResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceGetOntologySizeTimelineResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceGetOntologySizeTimelineResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OntologyManagementServiceGetOntologySizeTimelineResponse' from JSON`,
  );
}
