/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceListPatchesRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesListPatchesRequest;
};

export type OntologyManagementServiceListPatchesResponse =
  | models.TextqlRpcPublicPatchesListPatchesResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceListPatchesRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesListPatchesRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceListPatchesRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceListPatchesRequest$Outbound,
    OntologyManagementServiceListPatchesRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesListPatchesRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceListPatchesRequestToJSON(
  ontologyManagementServiceListPatchesRequest:
    OntologyManagementServiceListPatchesRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceListPatchesRequest$outboundSchema.parse(
      ontologyManagementServiceListPatchesRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceListPatchesResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceListPatchesResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesListPatchesResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceListPatchesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceListPatchesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceListPatchesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceListPatchesResponse' from JSON`,
  );
}
