/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceListApprovalRulesRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesListApprovalRulesRequest;
};

export type OntologyManagementServiceListApprovalRulesResponse =
  | models.TextqlRpcPublicPatchesListApprovalRulesResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceListApprovalRulesRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesListApprovalRulesRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceListApprovalRulesRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceListApprovalRulesRequest$Outbound,
    OntologyManagementServiceListApprovalRulesRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicPatchesListApprovalRulesRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceListApprovalRulesRequestToJSON(
  ontologyManagementServiceListApprovalRulesRequest:
    OntologyManagementServiceListApprovalRulesRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceListApprovalRulesRequest$outboundSchema.parse(
      ontologyManagementServiceListApprovalRulesRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceListApprovalRulesResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceListApprovalRulesResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesListApprovalRulesResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceListApprovalRulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceListApprovalRulesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceListApprovalRulesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceListApprovalRulesResponse' from JSON`,
  );
}
