/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceSetOntologyOwnersRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesSetOntologyOwnersRequest;
};

export type OntologyManagementServiceSetOntologyOwnersResponse =
  | models.TextqlRpcPublicPatchesSetOntologyOwnersResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceSetOntologyOwnersRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesSetOntologyOwnersRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceSetOntologyOwnersRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceSetOntologyOwnersRequest$Outbound,
    OntologyManagementServiceSetOntologyOwnersRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicPatchesSetOntologyOwnersRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceSetOntologyOwnersRequestToJSON(
  ontologyManagementServiceSetOntologyOwnersRequest:
    OntologyManagementServiceSetOntologyOwnersRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceSetOntologyOwnersRequest$outboundSchema.parse(
      ontologyManagementServiceSetOntologyOwnersRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceSetOntologyOwnersResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceSetOntologyOwnersResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesSetOntologyOwnersResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceSetOntologyOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceSetOntologyOwnersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceSetOntologyOwnersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceSetOntologyOwnersResponse' from JSON`,
  );
}
