/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceRenameOntologyFileRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesRenameOntologyFileRequest;
};

export type OntologyManagementServiceRenameOntologyFileResponse =
  | models.TextqlRpcPublicPatchesRenameOntologyFileResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceRenameOntologyFileRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesRenameOntologyFileRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceRenameOntologyFileRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceRenameOntologyFileRequest$Outbound,
    OntologyManagementServiceRenameOntologyFileRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicPatchesRenameOntologyFileRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceRenameOntologyFileRequestToJSON(
  ontologyManagementServiceRenameOntologyFileRequest:
    OntologyManagementServiceRenameOntologyFileRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceRenameOntologyFileRequest$outboundSchema.parse(
      ontologyManagementServiceRenameOntologyFileRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceRenameOntologyFileResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceRenameOntologyFileResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesRenameOntologyFileResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceRenameOntologyFileResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceRenameOntologyFileResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceRenameOntologyFileResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceRenameOntologyFileResponse' from JSON`,
  );
}
