/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServicePullOntologyFromRemoteRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesPullOntologyFromRemoteRequest;
};

export type OntologyManagementServicePullOntologyFromRemoteResponse =
  | models.GoogleProtobufEmpty
  | models.ConnectError;

/** @internal */
export type OntologyManagementServicePullOntologyFromRemoteRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesPullOntologyFromRemoteRequest$Outbound;
};

/** @internal */
export const OntologyManagementServicePullOntologyFromRemoteRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServicePullOntologyFromRemoteRequest$Outbound,
    OntologyManagementServicePullOntologyFromRemoteRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPatchesPullOntologyFromRemoteRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServicePullOntologyFromRemoteRequestToJSON(
  ontologyManagementServicePullOntologyFromRemoteRequest:
    OntologyManagementServicePullOntologyFromRemoteRequest,
): string {
  return JSON.stringify(
    OntologyManagementServicePullOntologyFromRemoteRequest$outboundSchema.parse(
      ontologyManagementServicePullOntologyFromRemoteRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServicePullOntologyFromRemoteResponse$inboundSchema:
  z.ZodMiniType<
    OntologyManagementServicePullOntologyFromRemoteResponse,
    unknown
  > = smartUnion([
    models.GoogleProtobufEmpty$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function ontologyManagementServicePullOntologyFromRemoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServicePullOntologyFromRemoteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServicePullOntologyFromRemoteResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OntologyManagementServicePullOntologyFromRemoteResponse' from JSON`,
  );
}
