/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceGetPatchByNumberRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetPatchByNumberRequest;
};

export type OntologyManagementServiceGetPatchByNumberResponse =
  | models.TextqlRpcPublicPatchesPatch
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceGetPatchByNumberRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPatchesGetPatchByNumberRequest$Outbound;
};

/** @internal */
export const OntologyManagementServiceGetPatchByNumberRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceGetPatchByNumberRequest$Outbound,
    OntologyManagementServiceGetPatchByNumberRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicPatchesGetPatchByNumberRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceGetPatchByNumberRequestToJSON(
  ontologyManagementServiceGetPatchByNumberRequest:
    OntologyManagementServiceGetPatchByNumberRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceGetPatchByNumberRequest$outboundSchema.parse(
      ontologyManagementServiceGetPatchByNumberRequest,
    ),
  );
}

/** @internal */
export const OntologyManagementServiceGetPatchByNumberResponse$inboundSchema:
  z.ZodMiniType<OntologyManagementServiceGetPatchByNumberResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicPatchesPatch$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function ontologyManagementServiceGetPatchByNumberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceGetPatchByNumberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceGetPatchByNumberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OntologyManagementServiceGetPatchByNumberResponse' from JSON`,
  );
}
