/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest =
  {
    connectProtocolVersion?: 1 | undefined;
    connectTimeoutMs?: number | undefined;
    body: models.TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleRequest;
  };

export type OntologyManagementServiceCreateContextPatchAutoApproveRuleResponse =
  | models.TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleResponse
  | models.ConnectError;

/** @internal */
export type OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest$Outbound =
  {
    "Connect-Protocol-Version": 1;
    "Connect-Timeout-Ms"?: number | undefined;
    body:
      models.TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleRequest$Outbound;
  };

/** @internal */
export const OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest$outboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest$Outbound,
    OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function ontologyManagementServiceCreateContextPatchAutoApproveRuleRequestToJSON(
  ontologyManagementServiceCreateContextPatchAutoApproveRuleRequest:
    OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest,
): string {
  return JSON.stringify(
    OntologyManagementServiceCreateContextPatchAutoApproveRuleRequest$outboundSchema
      .parse(ontologyManagementServiceCreateContextPatchAutoApproveRuleRequest),
  );
}

/** @internal */
export const OntologyManagementServiceCreateContextPatchAutoApproveRuleResponse$inboundSchema:
  z.ZodMiniType<
    OntologyManagementServiceCreateContextPatchAutoApproveRuleResponse,
    unknown
  > = smartUnion([
    models
      .TextqlRpcPublicPatchesCreateContextPatchAutoApproveRuleResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function ontologyManagementServiceCreateContextPatchAutoApproveRuleResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OntologyManagementServiceCreateContextPatchAutoApproveRuleResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OntologyManagementServiceCreateContextPatchAutoApproveRuleResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OntologyManagementServiceCreateContextPatchAutoApproveRuleResponse' from JSON`,
  );
}
