/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PlaybookServiceUnsetTeamsChannelContextPlaybookRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPlaybookUnsetTeamsChannelContextPlaybookRequest;
};

export type PlaybookServiceUnsetTeamsChannelContextPlaybookResponse =
  | models.TextqlRpcPublicPlaybookUnsetTeamsChannelContextPlaybookResponse
  | models.ConnectError;

/** @internal */
export type PlaybookServiceUnsetTeamsChannelContextPlaybookRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body:
    models.TextqlRpcPublicPlaybookUnsetTeamsChannelContextPlaybookRequest$Outbound;
};

/** @internal */
export const PlaybookServiceUnsetTeamsChannelContextPlaybookRequest$outboundSchema:
  z.ZodMiniType<
    PlaybookServiceUnsetTeamsChannelContextPlaybookRequest$Outbound,
    PlaybookServiceUnsetTeamsChannelContextPlaybookRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPlaybookUnsetTeamsChannelContextPlaybookRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function playbookServiceUnsetTeamsChannelContextPlaybookRequestToJSON(
  playbookServiceUnsetTeamsChannelContextPlaybookRequest:
    PlaybookServiceUnsetTeamsChannelContextPlaybookRequest,
): string {
  return JSON.stringify(
    PlaybookServiceUnsetTeamsChannelContextPlaybookRequest$outboundSchema.parse(
      playbookServiceUnsetTeamsChannelContextPlaybookRequest,
    ),
  );
}

/** @internal */
export const PlaybookServiceUnsetTeamsChannelContextPlaybookResponse$inboundSchema:
  z.ZodMiniType<
    PlaybookServiceUnsetTeamsChannelContextPlaybookResponse,
    unknown
  > = smartUnion([
    models
      .TextqlRpcPublicPlaybookUnsetTeamsChannelContextPlaybookResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function playbookServiceUnsetTeamsChannelContextPlaybookResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PlaybookServiceUnsetTeamsChannelContextPlaybookResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlaybookServiceUnsetTeamsChannelContextPlaybookResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PlaybookServiceUnsetTeamsChannelContextPlaybookResponse' from JSON`,
  );
}
