/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PlaybookServiceAttachDashboardRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPlaybookPlaybookAttachDashboardRequest;
};

export type PlaybookServiceAttachDashboardResponse =
  | models.TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse
  | models.ConnectError;

/** @internal */
export type PlaybookServiceAttachDashboardRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPlaybookPlaybookAttachDashboardRequest$Outbound;
};

/** @internal */
export const PlaybookServiceAttachDashboardRequest$outboundSchema:
  z.ZodMiniType<
    PlaybookServiceAttachDashboardRequest$Outbound,
    PlaybookServiceAttachDashboardRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPlaybookPlaybookAttachDashboardRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function playbookServiceAttachDashboardRequestToJSON(
  playbookServiceAttachDashboardRequest: PlaybookServiceAttachDashboardRequest,
): string {
  return JSON.stringify(
    PlaybookServiceAttachDashboardRequest$outboundSchema.parse(
      playbookServiceAttachDashboardRequest,
    ),
  );
}

/** @internal */
export const PlaybookServiceAttachDashboardResponse$inboundSchema:
  z.ZodMiniType<PlaybookServiceAttachDashboardResponse, unknown> = smartUnion([
    models.TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function playbookServiceAttachDashboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlaybookServiceAttachDashboardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PlaybookServiceAttachDashboardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlaybookServiceAttachDashboardResponse' from JSON`,
  );
}
