/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PowerBIServiceExportPowerBIReportImageRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPowerbiExportPowerBIReportImageRequest;
};

export type PowerBIServiceExportPowerBIReportImageResponse =
  | models.TextqlRpcPublicPowerbiExportPowerBIReportImageResponse
  | models.ConnectError;

/** @internal */
export type PowerBIServiceExportPowerBIReportImageRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPowerbiExportPowerBIReportImageRequest$Outbound;
};

/** @internal */
export const PowerBIServiceExportPowerBIReportImageRequest$outboundSchema:
  z.ZodMiniType<
    PowerBIServiceExportPowerBIReportImageRequest$Outbound,
    PowerBIServiceExportPowerBIReportImageRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPowerbiExportPowerBIReportImageRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function powerBIServiceExportPowerBIReportImageRequestToJSON(
  powerBIServiceExportPowerBIReportImageRequest:
    PowerBIServiceExportPowerBIReportImageRequest,
): string {
  return JSON.stringify(
    PowerBIServiceExportPowerBIReportImageRequest$outboundSchema.parse(
      powerBIServiceExportPowerBIReportImageRequest,
    ),
  );
}

/** @internal */
export const PowerBIServiceExportPowerBIReportImageResponse$inboundSchema:
  z.ZodMiniType<PowerBIServiceExportPowerBIReportImageResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicPowerbiExportPowerBIReportImageResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function powerBIServiceExportPowerBIReportImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PowerBIServiceExportPowerBIReportImageResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PowerBIServiceExportPowerBIReportImageResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PowerBIServiceExportPowerBIReportImageResponse' from JSON`,
  );
}
