/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PowerBIServiceGeneratePowerBIEmbedTokenRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest;
};

export type PowerBIServiceGeneratePowerBIEmbedTokenResponse =
  | models.TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenResponse
  | models.ConnectError;

/** @internal */
export type PowerBIServiceGeneratePowerBIEmbedTokenRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest$Outbound;
};

/** @internal */
export const PowerBIServiceGeneratePowerBIEmbedTokenRequest$outboundSchema:
  z.ZodMiniType<
    PowerBIServiceGeneratePowerBIEmbedTokenRequest$Outbound,
    PowerBIServiceGeneratePowerBIEmbedTokenRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function powerBIServiceGeneratePowerBIEmbedTokenRequestToJSON(
  powerBIServiceGeneratePowerBIEmbedTokenRequest:
    PowerBIServiceGeneratePowerBIEmbedTokenRequest,
): string {
  return JSON.stringify(
    PowerBIServiceGeneratePowerBIEmbedTokenRequest$outboundSchema.parse(
      powerBIServiceGeneratePowerBIEmbedTokenRequest,
    ),
  );
}

/** @internal */
export const PowerBIServiceGeneratePowerBIEmbedTokenResponse$inboundSchema:
  z.ZodMiniType<PowerBIServiceGeneratePowerBIEmbedTokenResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function powerBIServiceGeneratePowerBIEmbedTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PowerBIServiceGeneratePowerBIEmbedTokenResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PowerBIServiceGeneratePowerBIEmbedTokenResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PowerBIServiceGeneratePowerBIEmbedTokenResponse' from JSON`,
  );
}
