/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RBACServiceExportRolePermissionsRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicRbacExportRolePermissionsRequest;
};

export type RBACServiceExportRolePermissionsResponse =
  | models.TextqlRpcPublicRbacExportRolePermissionsResponse
  | models.ConnectError;

/** @internal */
export type RBACServiceExportRolePermissionsRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicRbacExportRolePermissionsRequest$Outbound;
};

/** @internal */
export const RBACServiceExportRolePermissionsRequest$outboundSchema:
  z.ZodMiniType<
    RBACServiceExportRolePermissionsRequest$Outbound,
    RBACServiceExportRolePermissionsRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicRbacExportRolePermissionsRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function rbacServiceExportRolePermissionsRequestToJSON(
  rbacServiceExportRolePermissionsRequest:
    RBACServiceExportRolePermissionsRequest,
): string {
  return JSON.stringify(
    RBACServiceExportRolePermissionsRequest$outboundSchema.parse(
      rbacServiceExportRolePermissionsRequest,
    ),
  );
}

/** @internal */
export const RBACServiceExportRolePermissionsResponse$inboundSchema:
  z.ZodMiniType<RBACServiceExportRolePermissionsResponse, unknown> = smartUnion(
    [
      models.TextqlRpcPublicRbacExportRolePermissionsResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ],
  );

export function rbacServiceExportRolePermissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  RBACServiceExportRolePermissionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RBACServiceExportRolePermissionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RBACServiceExportRolePermissionsResponse' from JSON`,
  );
}
