/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RBACServiceGenerateShareLinkRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicRbacGenerateShareLinkRequest;
};

export type RBACServiceGenerateShareLinkResponse =
  | models.TextqlRpcPublicRbacGenerateShareLinkResponse
  | models.ConnectError;

/** @internal */
export type RBACServiceGenerateShareLinkRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicRbacGenerateShareLinkRequest$Outbound;
};

/** @internal */
export const RBACServiceGenerateShareLinkRequest$outboundSchema: z.ZodMiniType<
  RBACServiceGenerateShareLinkRequest$Outbound,
  RBACServiceGenerateShareLinkRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicRbacGenerateShareLinkRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function rbacServiceGenerateShareLinkRequestToJSON(
  rbacServiceGenerateShareLinkRequest: RBACServiceGenerateShareLinkRequest,
): string {
  return JSON.stringify(
    RBACServiceGenerateShareLinkRequest$outboundSchema.parse(
      rbacServiceGenerateShareLinkRequest,
    ),
  );
}

/** @internal */
export const RBACServiceGenerateShareLinkResponse$inboundSchema: z.ZodMiniType<
  RBACServiceGenerateShareLinkResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicRbacGenerateShareLinkResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function rbacServiceGenerateShareLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<RBACServiceGenerateShareLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RBACServiceGenerateShareLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RBACServiceGenerateShareLinkResponse' from JSON`,
  );
}
