/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RBACServiceUpdateObjectVisibilityRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicRbacUpdateObjectVisibilityRequest;
};

export type RBACServiceUpdateObjectVisibilityResponse =
  | models.TextqlRpcPublicRbacUpdateObjectVisibilityResponse
  | models.ConnectError;

/** @internal */
export type RBACServiceUpdateObjectVisibilityRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicRbacUpdateObjectVisibilityRequest$Outbound;
};

/** @internal */
export const RBACServiceUpdateObjectVisibilityRequest$outboundSchema:
  z.ZodMiniType<
    RBACServiceUpdateObjectVisibilityRequest$Outbound,
    RBACServiceUpdateObjectVisibilityRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicRbacUpdateObjectVisibilityRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function rbacServiceUpdateObjectVisibilityRequestToJSON(
  rbacServiceUpdateObjectVisibilityRequest:
    RBACServiceUpdateObjectVisibilityRequest,
): string {
  return JSON.stringify(
    RBACServiceUpdateObjectVisibilityRequest$outboundSchema.parse(
      rbacServiceUpdateObjectVisibilityRequest,
    ),
  );
}

/** @internal */
export const RBACServiceUpdateObjectVisibilityResponse$inboundSchema:
  z.ZodMiniType<RBACServiceUpdateObjectVisibilityResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicRbacUpdateObjectVisibilityResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function rbacServiceUpdateObjectVisibilityResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  RBACServiceUpdateObjectVisibilityResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RBACServiceUpdateObjectVisibilityResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RBACServiceUpdateObjectVisibilityResponse' from JSON`,
  );
}
