/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RBACServiceGetMemberGroupsRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicRbacGetMemberGroupsRequest;
};

export type RBACServiceGetMemberGroupsResponse =
  | models.TextqlRpcPublicRbacGetMemberGroupsResponse
  | models.ConnectError;

/** @internal */
export type RBACServiceGetMemberGroupsRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicRbacGetMemberGroupsRequest$Outbound;
};

/** @internal */
export const RBACServiceGetMemberGroupsRequest$outboundSchema: z.ZodMiniType<
  RBACServiceGetMemberGroupsRequest$Outbound,
  RBACServiceGetMemberGroupsRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z.literal(1),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicRbacGetMemberGroupsRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function rbacServiceGetMemberGroupsRequestToJSON(
  rbacServiceGetMemberGroupsRequest: RBACServiceGetMemberGroupsRequest,
): string {
  return JSON.stringify(
    RBACServiceGetMemberGroupsRequest$outboundSchema.parse(
      rbacServiceGetMemberGroupsRequest,
    ),
  );
}

/** @internal */
export const RBACServiceGetMemberGroupsResponse$inboundSchema: z.ZodMiniType<
  RBACServiceGetMemberGroupsResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicRbacGetMemberGroupsResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function rbacServiceGetMemberGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<RBACServiceGetMemberGroupsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RBACServiceGetMemberGroupsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RBACServiceGetMemberGroupsResponse' from JSON`,
  );
}
