/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RBACServiceCreateGroupRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicRbacCreateGroupRequest;
};

export type RBACServiceCreateGroupResponse =
  | models.TextqlRpcPublicRbacCreateGroupResponse
  | models.ConnectError;

/** @internal */
export type RBACServiceCreateGroupRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicRbacCreateGroupRequest$Outbound;
};

/** @internal */
export const RBACServiceCreateGroupRequest$outboundSchema: z.ZodMiniType<
  RBACServiceCreateGroupRequest$Outbound,
  RBACServiceCreateGroupRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z.literal(1),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicRbacCreateGroupRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function rbacServiceCreateGroupRequestToJSON(
  rbacServiceCreateGroupRequest: RBACServiceCreateGroupRequest,
): string {
  return JSON.stringify(
    RBACServiceCreateGroupRequest$outboundSchema.parse(
      rbacServiceCreateGroupRequest,
    ),
  );
}

/** @internal */
export const RBACServiceCreateGroupResponse$inboundSchema: z.ZodMiniType<
  RBACServiceCreateGroupResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicRbacCreateGroupResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function rbacServiceCreateGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<RBACServiceCreateGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RBACServiceCreateGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RBACServiceCreateGroupResponse' from JSON`,
  );
}
