/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type RBACServiceRotateApiKeyRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicRbacRotateApiKeyRequest;
};

export type RBACServiceRotateApiKeyResponse =
  | models.TextqlRpcPublicRbacRotateApiKeyResponse
  | models.ConnectError;

/** @internal */
export type RBACServiceRotateApiKeyRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicRbacRotateApiKeyRequest$Outbound;
};

/** @internal */
export const RBACServiceRotateApiKeyRequest$outboundSchema: z.ZodMiniType<
  RBACServiceRotateApiKeyRequest$Outbound,
  RBACServiceRotateApiKeyRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z.literal(1),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicRbacRotateApiKeyRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function rbacServiceRotateApiKeyRequestToJSON(
  rbacServiceRotateApiKeyRequest: RBACServiceRotateApiKeyRequest,
): string {
  return JSON.stringify(
    RBACServiceRotateApiKeyRequest$outboundSchema.parse(
      rbacServiceRotateApiKeyRequest,
    ),
  );
}

/** @internal */
export const RBACServiceRotateApiKeyResponse$inboundSchema: z.ZodMiniType<
  RBACServiceRotateApiKeyResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicRbacRotateApiKeyResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function rbacServiceRotateApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<RBACServiceRotateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RBACServiceRotateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RBACServiceRotateApiKeyResponse' from JSON`,
  );
}
