/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SandboxAdminServiceStopSandboxRequest = {
  connectProtocolVersion: 1;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicSandboxAdminStopSandboxRequest;
};

export type SandboxAdminServiceStopSandboxResponse =
  | models.TextqlRpcPublicSandboxAdminStopSandboxResponse
  | models.ConnectError;

/** @internal */
export type SandboxAdminServiceStopSandboxRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicSandboxAdminStopSandboxRequest$Outbound;
};

/** @internal */
export const SandboxAdminServiceStopSandboxRequest$outboundSchema:
  z.ZodMiniType<
    SandboxAdminServiceStopSandboxRequest$Outbound,
    SandboxAdminServiceStopSandboxRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z.literal(1),
      connectTimeoutMs: z.optional(z.number()),
      body: models.TextqlRpcPublicSandboxAdminStopSandboxRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function sandboxAdminServiceStopSandboxRequestToJSON(
  sandboxAdminServiceStopSandboxRequest: SandboxAdminServiceStopSandboxRequest,
): string {
  return JSON.stringify(
    SandboxAdminServiceStopSandboxRequest$outboundSchema.parse(
      sandboxAdminServiceStopSandboxRequest,
    ),
  );
}

/** @internal */
export const SandboxAdminServiceStopSandboxResponse$inboundSchema:
  z.ZodMiniType<SandboxAdminServiceStopSandboxResponse, unknown> = smartUnion([
    models.TextqlRpcPublicSandboxAdminStopSandboxResponse$inboundSchema,
    models.ConnectError$inboundSchema,
  ]);

export function sandboxAdminServiceStopSandboxResponseFromJSON(
  jsonString: string,
): SafeParseResult<SandboxAdminServiceStopSandboxResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SandboxAdminServiceStopSandboxResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SandboxAdminServiceStopSandboxResponse' from JSON`,
  );
}
