/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ScimServiceCreateScimTokenRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicScimCreateScimTokenRequest;
};

export type ScimServiceCreateScimTokenResponse =
  | models.TextqlRpcPublicScimCreateScimTokenResponse
  | models.ConnectError;

/** @internal */
export type ScimServiceCreateScimTokenRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicScimCreateScimTokenRequest$Outbound;
};

/** @internal */
export const ScimServiceCreateScimTokenRequest$outboundSchema: z.ZodMiniType<
  ScimServiceCreateScimTokenRequest$Outbound,
  ScimServiceCreateScimTokenRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicScimCreateScimTokenRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function scimServiceCreateScimTokenRequestToJSON(
  scimServiceCreateScimTokenRequest: ScimServiceCreateScimTokenRequest,
): string {
  return JSON.stringify(
    ScimServiceCreateScimTokenRequest$outboundSchema.parse(
      scimServiceCreateScimTokenRequest,
    ),
  );
}

/** @internal */
export const ScimServiceCreateScimTokenResponse$inboundSchema: z.ZodMiniType<
  ScimServiceCreateScimTokenResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicScimCreateScimTokenResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function scimServiceCreateScimTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<ScimServiceCreateScimTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ScimServiceCreateScimTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScimServiceCreateScimTokenResponse' from JSON`,
  );
}
