/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ScimServiceRevokeScimTokenRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicScimRevokeScimTokenRequest;
};

export type ScimServiceRevokeScimTokenResponse =
  | models.TextqlRpcPublicScimRevokeScimTokenResponse
  | models.ConnectError;

/** @internal */
export type ScimServiceRevokeScimTokenRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicScimRevokeScimTokenRequest$Outbound;
};

/** @internal */
export const ScimServiceRevokeScimTokenRequest$outboundSchema: z.ZodMiniType<
  ScimServiceRevokeScimTokenRequest$Outbound,
  ScimServiceRevokeScimTokenRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.TextqlRpcPublicScimRevokeScimTokenRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function scimServiceRevokeScimTokenRequestToJSON(
  scimServiceRevokeScimTokenRequest: ScimServiceRevokeScimTokenRequest,
): string {
  return JSON.stringify(
    ScimServiceRevokeScimTokenRequest$outboundSchema.parse(
      scimServiceRevokeScimTokenRequest,
    ),
  );
}

/** @internal */
export const ScimServiceRevokeScimTokenResponse$inboundSchema: z.ZodMiniType<
  ScimServiceRevokeScimTokenResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicScimRevokeScimTokenResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function scimServiceRevokeScimTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<ScimServiceRevokeScimTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ScimServiceRevokeScimTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScimServiceRevokeScimTokenResponse' from JSON`,
  );
}
