/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SettingsServiceDeleteOrganizationMemberRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicSettingsDeleteOrganizationMemberRequest;
};

export type SettingsServiceDeleteOrganizationMemberResponse =
  | models.TextqlRpcPublicSettingsDeleteOrganizationMemberResponse
  | models.ConnectError;

/** @internal */
export type SettingsServiceDeleteOrganizationMemberRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicSettingsDeleteOrganizationMemberRequest$Outbound;
};

/** @internal */
export const SettingsServiceDeleteOrganizationMemberRequest$outboundSchema:
  z.ZodMiniType<
    SettingsServiceDeleteOrganizationMemberRequest$Outbound,
    SettingsServiceDeleteOrganizationMemberRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicSettingsDeleteOrganizationMemberRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function settingsServiceDeleteOrganizationMemberRequestToJSON(
  settingsServiceDeleteOrganizationMemberRequest:
    SettingsServiceDeleteOrganizationMemberRequest,
): string {
  return JSON.stringify(
    SettingsServiceDeleteOrganizationMemberRequest$outboundSchema.parse(
      settingsServiceDeleteOrganizationMemberRequest,
    ),
  );
}

/** @internal */
export const SettingsServiceDeleteOrganizationMemberResponse$inboundSchema:
  z.ZodMiniType<SettingsServiceDeleteOrganizationMemberResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicSettingsDeleteOrganizationMemberResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function settingsServiceDeleteOrganizationMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SettingsServiceDeleteOrganizationMemberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SettingsServiceDeleteOrganizationMemberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SettingsServiceDeleteOrganizationMemberResponse' from JSON`,
  );
}
