/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SettingsServiceCheckMemberStatusRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicSettingsCheckMemberStatusRequest;
};

export type SettingsServiceCheckMemberStatusResponse =
  | models.TextqlRpcPublicSettingsCheckMemberStatusResponse
  | models.ConnectError;

/** @internal */
export type SettingsServiceCheckMemberStatusRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicSettingsCheckMemberStatusRequest$Outbound;
};

/** @internal */
export const SettingsServiceCheckMemberStatusRequest$outboundSchema:
  z.ZodMiniType<
    SettingsServiceCheckMemberStatusRequest$Outbound,
    SettingsServiceCheckMemberStatusRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models.TextqlRpcPublicSettingsCheckMemberStatusRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function settingsServiceCheckMemberStatusRequestToJSON(
  settingsServiceCheckMemberStatusRequest:
    SettingsServiceCheckMemberStatusRequest,
): string {
  return JSON.stringify(
    SettingsServiceCheckMemberStatusRequest$outboundSchema.parse(
      settingsServiceCheckMemberStatusRequest,
    ),
  );
}

/** @internal */
export const SettingsServiceCheckMemberStatusResponse$inboundSchema:
  z.ZodMiniType<SettingsServiceCheckMemberStatusResponse, unknown> = smartUnion(
    [
      models.TextqlRpcPublicSettingsCheckMemberStatusResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ],
  );

export function settingsServiceCheckMemberStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SettingsServiceCheckMemberStatusResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SettingsServiceCheckMemberStatusResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SettingsServiceCheckMemberStatusResponse' from JSON`,
  );
}
