/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SlackServiceHandleSlackOAuthCallbackRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicSlackHandleSlackOAuthCallbackRequest;
};

export type SlackServiceHandleSlackOAuthCallbackResponse =
  | models.TextqlRpcPublicSlackHandleSlackOAuthCallbackResponse
  | models.ConnectError;

/** @internal */
export type SlackServiceHandleSlackOAuthCallbackRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicSlackHandleSlackOAuthCallbackRequest$Outbound;
};

/** @internal */
export const SlackServiceHandleSlackOAuthCallbackRequest$outboundSchema:
  z.ZodMiniType<
    SlackServiceHandleSlackOAuthCallbackRequest$Outbound,
    SlackServiceHandleSlackOAuthCallbackRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicSlackHandleSlackOAuthCallbackRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function slackServiceHandleSlackOAuthCallbackRequestToJSON(
  slackServiceHandleSlackOAuthCallbackRequest:
    SlackServiceHandleSlackOAuthCallbackRequest,
): string {
  return JSON.stringify(
    SlackServiceHandleSlackOAuthCallbackRequest$outboundSchema.parse(
      slackServiceHandleSlackOAuthCallbackRequest,
    ),
  );
}

/** @internal */
export const SlackServiceHandleSlackOAuthCallbackResponse$inboundSchema:
  z.ZodMiniType<SlackServiceHandleSlackOAuthCallbackResponse, unknown> =
    smartUnion([
      models.TextqlRpcPublicSlackHandleSlackOAuthCallbackResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function slackServiceHandleSlackOAuthCallbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SlackServiceHandleSlackOAuthCallbackResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SlackServiceHandleSlackOAuthCallbackResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SlackServiceHandleSlackOAuthCallbackResponse' from JSON`,
  );
}
