/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SlackServiceListUsersRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.GoogleProtobufEmpty;
};

export type SlackServiceListUsersResponse =
  | models.TextqlRpcPublicSlackListUsersResponse
  | models.ConnectError;

/** @internal */
export type SlackServiceListUsersRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.GoogleProtobufEmpty$Outbound;
};

/** @internal */
export const SlackServiceListUsersRequest$outboundSchema: z.ZodMiniType<
  SlackServiceListUsersRequest$Outbound,
  SlackServiceListUsersRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.GoogleProtobufEmpty$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function slackServiceListUsersRequestToJSON(
  slackServiceListUsersRequest: SlackServiceListUsersRequest,
): string {
  return JSON.stringify(
    SlackServiceListUsersRequest$outboundSchema.parse(
      slackServiceListUsersRequest,
    ),
  );
}

/** @internal */
export const SlackServiceListUsersResponse$inboundSchema: z.ZodMiniType<
  SlackServiceListUsersResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicSlackListUsersResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function slackServiceListUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<SlackServiceListUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SlackServiceListUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SlackServiceListUsersResponse' from JSON`,
  );
}
