/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type TableauServiceRefreshTableauCollectionRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.TextqlRpcPublicTableauRefreshTableauCollectionRequest;
};

export type TableauServiceRefreshTableauCollectionResponse =
  | models.TextqlRpcPublicTableauRefreshTableauCollectionResponse
  | models.ConnectError;

/** @internal */
export type TableauServiceRefreshTableauCollectionRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.TextqlRpcPublicTableauRefreshTableauCollectionRequest$Outbound;
};

/** @internal */
export const TableauServiceRefreshTableauCollectionRequest$outboundSchema:
  z.ZodMiniType<
    TableauServiceRefreshTableauCollectionRequest$Outbound,
    TableauServiceRefreshTableauCollectionRequest
  > = z.pipe(
    z.object({
      connectProtocolVersion: z._default(z.literal(1), 1 as const),
      connectTimeoutMs: z.optional(z.number()),
      body:
        models
          .TextqlRpcPublicTableauRefreshTableauCollectionRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        connectProtocolVersion: "Connect-Protocol-Version",
        connectTimeoutMs: "Connect-Timeout-Ms",
      });
    }),
  );

export function tableauServiceRefreshTableauCollectionRequestToJSON(
  tableauServiceRefreshTableauCollectionRequest:
    TableauServiceRefreshTableauCollectionRequest,
): string {
  return JSON.stringify(
    TableauServiceRefreshTableauCollectionRequest$outboundSchema.parse(
      tableauServiceRefreshTableauCollectionRequest,
    ),
  );
}

/** @internal */
export const TableauServiceRefreshTableauCollectionResponse$inboundSchema:
  z.ZodMiniType<TableauServiceRefreshTableauCollectionResponse, unknown> =
    smartUnion([
      models
        .TextqlRpcPublicTableauRefreshTableauCollectionResponse$inboundSchema,
      models.ConnectError$inboundSchema,
    ]);

export function tableauServiceRefreshTableauCollectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TableauServiceRefreshTableauCollectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TableauServiceRefreshTableauCollectionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TableauServiceRefreshTableauCollectionResponse' from JSON`,
  );
}
