/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type TeamsServiceGetCurrentUserRequest = {
  connectProtocolVersion?: 1 | undefined;
  connectTimeoutMs?: number | undefined;
  body: models.GoogleProtobufEmpty;
};

export type TeamsServiceGetCurrentUserResponse =
  | models.TextqlRpcPublicTeamsTeamsGetCurrentUserResponse
  | models.ConnectError;

/** @internal */
export type TeamsServiceGetCurrentUserRequest$Outbound = {
  "Connect-Protocol-Version": 1;
  "Connect-Timeout-Ms"?: number | undefined;
  body: models.GoogleProtobufEmpty$Outbound;
};

/** @internal */
export const TeamsServiceGetCurrentUserRequest$outboundSchema: z.ZodMiniType<
  TeamsServiceGetCurrentUserRequest$Outbound,
  TeamsServiceGetCurrentUserRequest
> = z.pipe(
  z.object({
    connectProtocolVersion: z._default(z.literal(1), 1 as const),
    connectTimeoutMs: z.optional(z.number()),
    body: models.GoogleProtobufEmpty$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectProtocolVersion: "Connect-Protocol-Version",
      connectTimeoutMs: "Connect-Timeout-Ms",
    });
  }),
);

export function teamsServiceGetCurrentUserRequestToJSON(
  teamsServiceGetCurrentUserRequest: TeamsServiceGetCurrentUserRequest,
): string {
  return JSON.stringify(
    TeamsServiceGetCurrentUserRequest$outboundSchema.parse(
      teamsServiceGetCurrentUserRequest,
    ),
  );
}

/** @internal */
export const TeamsServiceGetCurrentUserResponse$inboundSchema: z.ZodMiniType<
  TeamsServiceGetCurrentUserResponse,
  unknown
> = smartUnion([
  models.TextqlRpcPublicTeamsTeamsGetCurrentUserResponse$inboundSchema,
  models.ConnectError$inboundSchema,
]);

export function teamsServiceGetCurrentUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<TeamsServiceGetCurrentUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TeamsServiceGetCurrentUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsServiceGetCurrentUserResponse' from JSON`,
  );
}
