/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPatchesAddLibrarySubmoduleResponse = {
  path?: string | undefined;
  url?: string | undefined;
  branch?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesAddLibrarySubmoduleResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesAddLibrarySubmoduleResponse, unknown> = z
    .object({
      path: types.optional(types.string()),
      url: types.optional(types.string()),
      branch: types.optional(types.string()),
    });

export function textqlRpcPublicPatchesAddLibrarySubmoduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesAddLibrarySubmoduleResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesAddLibrarySubmoduleResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesAddLibrarySubmoduleResponse' from JSON`,
  );
}
