/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicReportsSpacerBlock = {
  height?: number | null | undefined;
};

/** @internal */
export const TextqlRpcPublicReportsSpacerBlock$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicReportsSpacerBlock,
  unknown
> = z.object({
  height: z.optional(z.nullable(types.number())),
});
/** @internal */
export type TextqlRpcPublicReportsSpacerBlock$Outbound = {
  height?: number | null | undefined;
};

/** @internal */
export const TextqlRpcPublicReportsSpacerBlock$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicReportsSpacerBlock$Outbound,
  TextqlRpcPublicReportsSpacerBlock
> = z.object({
  height: z.optional(z.nullable(z.int())),
});

export function textqlRpcPublicReportsSpacerBlockToJSON(
  textqlRpcPublicReportsSpacerBlock: TextqlRpcPublicReportsSpacerBlock,
): string {
  return JSON.stringify(
    TextqlRpcPublicReportsSpacerBlock$outboundSchema.parse(
      textqlRpcPublicReportsSpacerBlock,
    ),
  );
}
export function textqlRpcPublicReportsSpacerBlockFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicReportsSpacerBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextqlRpcPublicReportsSpacerBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicReportsSpacerBlock' from JSON`,
  );
}
