/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicAuditLogS3AuthMode = {
  S3AuthModeUnspecified: "S3_AUTH_MODE_UNSPECIFIED",
  S3AuthModeAccessKey: "S3_AUTH_MODE_ACCESS_KEY",
  S3AuthModeAssumeRole: "S3_AUTH_MODE_ASSUME_ROLE",
} as const;
export type TextqlRpcPublicAuditLogS3AuthMode = OpenEnum<
  typeof TextqlRpcPublicAuditLogS3AuthMode
>;

/** @internal */
export const TextqlRpcPublicAuditLogS3AuthMode$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicAuditLogS3AuthMode,
  unknown
> = openEnums.inboundSchema(TextqlRpcPublicAuditLogS3AuthMode);
/** @internal */
export const TextqlRpcPublicAuditLogS3AuthMode$outboundSchema: z.ZodMiniType<
  string,
  TextqlRpcPublicAuditLogS3AuthMode
> = openEnums.outboundSchema(TextqlRpcPublicAuditLogS3AuthMode);
