/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPlaybookDemoPlaybookResponse = {};

/** @internal */
export const TextqlRpcPublicPlaybookDemoPlaybookResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPlaybookDemoPlaybookResponse, unknown> = z
    .object({});

export function textqlRpcPublicPlaybookDemoPlaybookResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPlaybookDemoPlaybookResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPlaybookDemoPlaybookResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPlaybookDemoPlaybookResponse' from JSON`,
  );
}
