/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesLibraryAnaConfig,
  TextqlRpcPublicPatchesLibraryAnaConfig$inboundSchema,
} from "./textql-rpc-public-patches-library-ana-config.js";

export type TextqlRpcPublicPatchesGetLibraryAnaConfigResponse = {
  config?: TextqlRpcPublicPatchesLibraryAnaConfig | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetLibraryAnaConfigResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesGetLibraryAnaConfigResponse, unknown> = z
    .object({
      config: types.optional(
        TextqlRpcPublicPatchesLibraryAnaConfig$inboundSchema,
      ),
    });

export function textqlRpcPublicPatchesGetLibraryAnaConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesGetLibraryAnaConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesGetLibraryAnaConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesGetLibraryAnaConfigResponse' from JSON`,
  );
}
