/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * SaveObjectAsConfig renders an existing DB object (object_type keyed like
 *
 * @remarks
 *  config_source: "playbook", later "dashboard", ...) as a config file and
 *  authors it as a new OPEN patch under the type's default ontology folder. The
 *  file can be moved/edited like any patch file before merging; on merge,
 *  reconcile takes over the original object when content and permissions allow.
 */
export type TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest = {
  objectType?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest$Outbound = {
  objectType?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest$Outbound,
    TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest
  > = z.object({
    objectType: z.optional(z.string()),
  });

export function textqlRpcPublicPatchesSaveAllObjectsAsConfigRequestToJSON(
  textqlRpcPublicPatchesSaveAllObjectsAsConfigRequest:
    TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesSaveAllObjectsAsConfigRequest$outboundSchema.parse(
      textqlRpcPublicPatchesSaveAllObjectsAsConfigRequest,
    ),
  );
}
