/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicConnectorQueryJoinInfo = {
  tables?: Array<string> | undefined;
  joinType?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorQueryJoinInfo$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicConnectorQueryJoinInfo,
  unknown
> = z.object({
  tables: types.optional(z.array(types.string())),
  joinType: types.optional(types.string()),
});

export function textqlRpcPublicConnectorQueryJoinInfoFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicConnectorQueryJoinInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorQueryJoinInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicConnectorQueryJoinInfo' from JSON`,
  );
}
