/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicConnectorRedshiftMetadata = {
  host?: string | undefined;
  port?: number | undefined;
  user?: string | undefined;
  password?: string | undefined;
  database?: string | undefined;
  schemas?: Array<string> | undefined;
  dialect?: string | undefined;
  sslMode?: boolean | undefined;
  /**
   * PASSWORD, IAM_ROLE
   */
  authType?: string | undefined;
  roleArn?: string | undefined;
  region?: string | undefined;
  clusterId?: string | undefined;
  groupFederation?: boolean | undefined;
  awsAccessKeyId?: string | undefined;
  awsSecretAccessKey?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorRedshiftMetadata$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicConnectorRedshiftMetadata, unknown> = z.object({
    host: types.optional(types.string()),
    port: types.optional(types.number()),
    user: types.optional(types.string()),
    password: types.optional(types.string()),
    database: types.optional(types.string()),
    schemas: types.optional(z.array(types.string())),
    dialect: types.optional(types.string()),
    sslMode: types.optional(types.boolean()),
    authType: types.optional(types.string()),
    roleArn: types.optional(types.string()),
    region: types.optional(types.string()),
    clusterId: types.optional(types.string()),
    groupFederation: types.optional(types.boolean()),
    awsAccessKeyId: types.optional(types.string()),
    awsSecretAccessKey: types.optional(types.string()),
  });
/** @internal */
export type TextqlRpcPublicConnectorRedshiftMetadata$Outbound = {
  host?: string | undefined;
  port?: number | undefined;
  user?: string | undefined;
  password?: string | undefined;
  database?: string | undefined;
  schemas?: Array<string> | undefined;
  dialect?: string | undefined;
  sslMode?: boolean | undefined;
  authType?: string | undefined;
  roleArn?: string | undefined;
  region?: string | undefined;
  clusterId?: string | undefined;
  groupFederation?: boolean | undefined;
  awsAccessKeyId?: string | undefined;
  awsSecretAccessKey?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorRedshiftMetadata$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorRedshiftMetadata$Outbound,
    TextqlRpcPublicConnectorRedshiftMetadata
  > = z.object({
    host: z.optional(z.string()),
    port: z.optional(z.int()),
    user: z.optional(z.string()),
    password: z.optional(z.string()),
    database: z.optional(z.string()),
    schemas: z.optional(z.array(z.string())),
    dialect: z.optional(z.string()),
    sslMode: z.optional(z.boolean()),
    authType: z.optional(z.string()),
    roleArn: z.optional(z.string()),
    region: z.optional(z.string()),
    clusterId: z.optional(z.string()),
    groupFederation: z.optional(z.boolean()),
    awsAccessKeyId: z.optional(z.string()),
    awsSecretAccessKey: z.optional(z.string()),
  });

export function textqlRpcPublicConnectorRedshiftMetadataToJSON(
  textqlRpcPublicConnectorRedshiftMetadata:
    TextqlRpcPublicConnectorRedshiftMetadata,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorRedshiftMetadata$outboundSchema.parse(
      textqlRpcPublicConnectorRedshiftMetadata,
    ),
  );
}
export function textqlRpcPublicConnectorRedshiftMetadataFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicConnectorRedshiftMetadata,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorRedshiftMetadata$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicConnectorRedshiftMetadata' from JSON`,
  );
}
