/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPlaybookTemplateDataReports,
  TextqlRpcPublicPlaybookTemplateDataReports$inboundSchema,
} from "./textql-rpc-public-playbook-template-data-reports.js";

/**
 * Batch response with reports grouped by template_data_id
 */
export type TextqlRpcPublicPlaybookGetPlaybookReportsBatchResponse = {
  templateDataReports?:
    | Array<TextqlRpcPublicPlaybookTemplateDataReports>
    | undefined;
};

/** @internal */
export const TextqlRpcPublicPlaybookGetPlaybookReportsBatchResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPlaybookGetPlaybookReportsBatchResponse,
    unknown
  > = z.object({
    templateDataReports: types.optional(
      z.array(TextqlRpcPublicPlaybookTemplateDataReports$inboundSchema),
    ),
  });

export function textqlRpcPublicPlaybookGetPlaybookReportsBatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPlaybookGetPlaybookReportsBatchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPlaybookGetPlaybookReportsBatchResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPlaybookGetPlaybookReportsBatchResponse' from JSON`,
  );
}
