/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesGetOntologyRemoteRequest = {};

/** @internal */
export type TextqlRpcPublicPatchesGetOntologyRemoteRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicPatchesGetOntologyRemoteRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesGetOntologyRemoteRequest$Outbound,
    TextqlRpcPublicPatchesGetOntologyRemoteRequest
  > = z.object({});

export function textqlRpcPublicPatchesGetOntologyRemoteRequestToJSON(
  textqlRpcPublicPatchesGetOntologyRemoteRequest:
    TextqlRpcPublicPatchesGetOntologyRemoteRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesGetOntologyRemoteRequest$outboundSchema.parse(
      textqlRpcPublicPatchesGetOntologyRemoteRequest,
    ),
  );
}
