/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacListRolesRequest = {};

/** @internal */
export type TextqlRpcPublicRbacListRolesRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicRbacListRolesRequest$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicRbacListRolesRequest$Outbound,
  TextqlRpcPublicRbacListRolesRequest
> = z.object({});

export function textqlRpcPublicRbacListRolesRequestToJSON(
  textqlRpcPublicRbacListRolesRequest: TextqlRpcPublicRbacListRolesRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacListRolesRequest$outboundSchema.parse(
      textqlRpcPublicRbacListRolesRequest,
    ),
  );
}
