/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicSettingsCheckMemberStatusRequest = {
  forceRefresh?: boolean | undefined;
};

/** @internal */
export type TextqlRpcPublicSettingsCheckMemberStatusRequest$Outbound = {
  forceRefresh?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicSettingsCheckMemberStatusRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicSettingsCheckMemberStatusRequest$Outbound,
    TextqlRpcPublicSettingsCheckMemberStatusRequest
  > = z.object({
    forceRefresh: z.optional(z.boolean()),
  });

export function textqlRpcPublicSettingsCheckMemberStatusRequestToJSON(
  textqlRpcPublicSettingsCheckMemberStatusRequest:
    TextqlRpcPublicSettingsCheckMemberStatusRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicSettingsCheckMemberStatusRequest$outboundSchema.parse(
      textqlRpcPublicSettingsCheckMemberStatusRequest,
    ),
  );
}
