/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesApprovalRule,
  TextqlRpcPublicPatchesApprovalRule$inboundSchema,
} from "./textql-rpc-public-patches-approval-rule.js";

export type TextqlRpcPublicPatchesCreateApprovalRuleResponse = {
  rule?: TextqlRpcPublicPatchesApprovalRule | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesCreateApprovalRuleResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesCreateApprovalRuleResponse, unknown> = z
    .object({
      rule: types.optional(TextqlRpcPublicPatchesApprovalRule$inboundSchema),
    });

export function textqlRpcPublicPatchesCreateApprovalRuleResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesCreateApprovalRuleResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesCreateApprovalRuleResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesCreateApprovalRuleResponse' from JSON`,
  );
}
