/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicTeamsTeamsUser = {
  id?: string | undefined;
  name?: string | null | undefined;
  email?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicTeamsTeamsUser$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicTeamsTeamsUser,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: z.optional(z.nullable(types.string())),
  email: z.optional(z.nullable(types.string())),
});

export function textqlRpcPublicTeamsTeamsUserFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicTeamsTeamsUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextqlRpcPublicTeamsTeamsUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicTeamsTeamsUser' from JSON`,
  );
}
