/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicDashboardDashboard,
  TextqlRpcPublicDashboardDashboard$inboundSchema,
} from "./textql-rpc-public-dashboard-dashboard.js";

export type TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse = {
  dashboard?: TextqlRpcPublicDashboardDashboard | undefined;
};

/** @internal */
export const TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse,
    unknown
  > = z.object({
    dashboard: types.optional(TextqlRpcPublicDashboardDashboard$inboundSchema),
  });

export function textqlRpcPublicPlaybookPlaybookAttachDashboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPlaybookPlaybookAttachDashboardResponse' from JSON`,
  );
}
