/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicChatChat,
  TextqlRpcPublicChatChat$inboundSchema,
} from "./textql-rpc-public-chat-chat.js";

export type TextqlRpcPublicChatUpdateChatResponse = {
  chat?: TextqlRpcPublicChatChat | undefined;
};

/** @internal */
export const TextqlRpcPublicChatUpdateChatResponse$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicChatUpdateChatResponse,
  unknown
> = z.object({
  chat: types.optional(TextqlRpcPublicChatChat$inboundSchema),
});

export function textqlRpcPublicChatUpdateChatResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicChatUpdateChatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatUpdateChatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicChatUpdateChatResponse' from JSON`,
  );
}
