/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesOntologyOwners,
  TextqlRpcPublicPatchesOntologyOwners$inboundSchema,
} from "./textql-rpc-public-patches-ontology-owners.js";

export type TextqlRpcPublicPatchesSetOntologyOwnersResponse = {
  owners?: TextqlRpcPublicPatchesOntologyOwners | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesSetOntologyOwnersResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesSetOntologyOwnersResponse, unknown> = z
    .object({
      owners: types.optional(
        TextqlRpcPublicPatchesOntologyOwners$inboundSchema,
      ),
    });

export function textqlRpcPublicPatchesSetOntologyOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesSetOntologyOwnersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesSetOntologyOwnersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesSetOntologyOwnersResponse' from JSON`,
  );
}
