/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Version history (mirrors dashboard.DashboardVersion). A snapshot of the
 *
 * @remarks
 *  published app at publish time; restore writes it back into the draft.
 */
export type TextqlRpcPublicAppGetAppVersionRequest = {
  appId?: string | undefined;
  versionNumber?: number | undefined;
};

/** @internal */
export type TextqlRpcPublicAppGetAppVersionRequest$Outbound = {
  appId?: string | undefined;
  versionNumber?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicAppGetAppVersionRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicAppGetAppVersionRequest$Outbound,
    TextqlRpcPublicAppGetAppVersionRequest
  > = z.object({
    appId: z.optional(z.string()),
    versionNumber: z.optional(z.int()),
  });

export function textqlRpcPublicAppGetAppVersionRequestToJSON(
  textqlRpcPublicAppGetAppVersionRequest:
    TextqlRpcPublicAppGetAppVersionRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicAppGetAppVersionRequest$outboundSchema.parse(
      textqlRpcPublicAppGetAppVersionRequest,
    ),
  );
}
