/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesLibrarySyncRun,
  TextqlRpcPublicPatchesLibrarySyncRun$inboundSchema,
} from "./textql-rpc-public-patches-library-sync-run.js";

export type TextqlRpcPublicPatchesListLibrarySyncRunsResponse = {
  runs?: Array<TextqlRpcPublicPatchesLibrarySyncRun> | undefined;
  nextPageToken?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesListLibrarySyncRunsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesListLibrarySyncRunsResponse, unknown> = z
    .object({
      runs: types.optional(
        z.array(TextqlRpcPublicPatchesLibrarySyncRun$inboundSchema),
      ),
      nextPageToken: z.optional(z.nullable(types.string())),
    });

export function textqlRpcPublicPatchesListLibrarySyncRunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesListLibrarySyncRunsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesListLibrarySyncRunsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesListLibrarySyncRunsResponse' from JSON`,
  );
}
