/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TextqlRpcPublicCellsReportCell,
  TextqlRpcPublicCellsReportCell$Outbound,
  TextqlRpcPublicCellsReportCell$outboundSchema,
} from "./textql-rpc-public-cells-report-cell.js";

export type TextqlRpcPublicPlaybookPreviewSlackReportRequest = {
  playbookId?: string | undefined;
  cell?: TextqlRpcPublicCellsReportCell | undefined;
  chatId?: string | undefined;
  slackChannelId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPlaybookPreviewSlackReportRequest$Outbound = {
  playbookId?: string | undefined;
  cell?: TextqlRpcPublicCellsReportCell$Outbound | undefined;
  chatId?: string | undefined;
  slackChannelId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPlaybookPreviewSlackReportRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPlaybookPreviewSlackReportRequest$Outbound,
    TextqlRpcPublicPlaybookPreviewSlackReportRequest
  > = z.object({
    playbookId: z.optional(z.string()),
    cell: z.optional(TextqlRpcPublicCellsReportCell$outboundSchema),
    chatId: z.optional(z.string()),
    slackChannelId: z.optional(z.string()),
  });

export function textqlRpcPublicPlaybookPreviewSlackReportRequestToJSON(
  textqlRpcPublicPlaybookPreviewSlackReportRequest:
    TextqlRpcPublicPlaybookPreviewSlackReportRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPlaybookPreviewSlackReportRequest$outboundSchema.parse(
      textqlRpcPublicPlaybookPreviewSlackReportRequest,
    ),
  );
}
