/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesListGoldenFilesRequest = {};

/** @internal */
export type TextqlRpcPublicPatchesListGoldenFilesRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicPatchesListGoldenFilesRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesListGoldenFilesRequest$Outbound,
    TextqlRpcPublicPatchesListGoldenFilesRequest
  > = z.object({});

export function textqlRpcPublicPatchesListGoldenFilesRequestToJSON(
  textqlRpcPublicPatchesListGoldenFilesRequest:
    TextqlRpcPublicPatchesListGoldenFilesRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesListGoldenFilesRequest$outboundSchema.parse(
      textqlRpcPublicPatchesListGoldenFilesRequest,
    ),
  );
}
