/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicMcpInitiateOAuthFlowRequest = {
  serverId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicMcpInitiateOAuthFlowRequest$Outbound = {
  serverId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicMcpInitiateOAuthFlowRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicMcpInitiateOAuthFlowRequest$Outbound,
    TextqlRpcPublicMcpInitiateOAuthFlowRequest
  > = z.object({
    serverId: z.optional(z.string()),
  });

export function textqlRpcPublicMcpInitiateOAuthFlowRequestToJSON(
  textqlRpcPublicMcpInitiateOAuthFlowRequest:
    TextqlRpcPublicMcpInitiateOAuthFlowRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicMcpInitiateOAuthFlowRequest$outboundSchema.parse(
      textqlRpcPublicMcpInitiateOAuthFlowRequest,
    ),
  );
}
