/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacGenerateShareLinkRequest = {
  objectType?: string | undefined;
  objectId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacGenerateShareLinkRequest$Outbound = {
  objectType?: string | undefined;
  objectId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacGenerateShareLinkRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicRbacGenerateShareLinkRequest$Outbound,
    TextqlRpcPublicRbacGenerateShareLinkRequest
  > = z.object({
    objectType: z.optional(z.string()),
    objectId: z.optional(z.string()),
  });

export function textqlRpcPublicRbacGenerateShareLinkRequestToJSON(
  textqlRpcPublicRbacGenerateShareLinkRequest:
    TextqlRpcPublicRbacGenerateShareLinkRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacGenerateShareLinkRequest$outboundSchema.parse(
      textqlRpcPublicRbacGenerateShareLinkRequest,
    ),
  );
}
