/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicChatArtifactSummary,
  TextqlRpcPublicChatArtifactSummary$inboundSchema,
} from "./textql-rpc-public-chat-artifact-summary.js";

export type TextqlRpcPublicChatGetChatArtifactsSummaryResponse = {
  /**
   * Flat list, sorted by created_at DESC
   */
  artifacts?: Array<TextqlRpcPublicChatArtifactSummary> | undefined;
};

/** @internal */
export const TextqlRpcPublicChatGetChatArtifactsSummaryResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicChatGetChatArtifactsSummaryResponse, unknown> = z
    .object({
      artifacts: types.optional(
        z.array(TextqlRpcPublicChatArtifactSummary$inboundSchema),
      ),
    });

export function textqlRpcPublicChatGetChatArtifactsSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicChatGetChatArtifactsSummaryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatGetChatArtifactsSummaryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicChatGetChatArtifactsSummaryResponse' from JSON`,
  );
}
