/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicSandboxAdminListSandboxSpendRequest = {
  sandboxId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicSandboxAdminListSandboxSpendRequest$Outbound = {
  sandboxId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicSandboxAdminListSandboxSpendRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicSandboxAdminListSandboxSpendRequest$Outbound,
    TextqlRpcPublicSandboxAdminListSandboxSpendRequest
  > = z.object({
    sandboxId: z.optional(z.string()),
  });

export function textqlRpcPublicSandboxAdminListSandboxSpendRequestToJSON(
  textqlRpcPublicSandboxAdminListSandboxSpendRequest:
    TextqlRpcPublicSandboxAdminListSandboxSpendRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicSandboxAdminListSandboxSpendRequest$outboundSchema.parse(
      textqlRpcPublicSandboxAdminListSandboxSpendRequest,
    ),
  );
}
