/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicRbacPipelinePermissionAction = {
  PipelineActionUnspecified: "PIPELINE_ACTION_UNSPECIFIED",
  PipelineActionRead: "PIPELINE_ACTION_READ",
  PipelineActionRun: "PIPELINE_ACTION_RUN",
  PipelineActionWrite: "PIPELINE_ACTION_WRITE",
} as const;
export type TextqlRpcPublicRbacPipelinePermissionAction = OpenEnum<
  typeof TextqlRpcPublicRbacPipelinePermissionAction
>;

/** @internal */
export const TextqlRpcPublicRbacPipelinePermissionAction$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacPipelinePermissionAction, unknown> =
    openEnums.inboundSchema(TextqlRpcPublicRbacPipelinePermissionAction);
/** @internal */
export const TextqlRpcPublicRbacPipelinePermissionAction$outboundSchema:
  z.ZodMiniType<string, TextqlRpcPublicRbacPipelinePermissionAction> = openEnums
    .outboundSchema(TextqlRpcPublicRbacPipelinePermissionAction);
