/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicOntologyIntermediateJoin = {
  tableName?: string | undefined;
  leftColumn?: string | undefined;
  rightColumn?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicOntologyIntermediateJoin$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicOntologyIntermediateJoin, unknown> = z.object({
    tableName: types.optional(types.string()),
    leftColumn: types.optional(types.string()),
    rightColumn: types.optional(types.string()),
  });

export function textqlRpcPublicOntologyIntermediateJoinFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicOntologyIntermediateJoin,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicOntologyIntermediateJoin$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicOntologyIntermediateJoin' from JSON`,
  );
}
