/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicAppAppMemberActivityRow,
  TextqlRpcPublicAppAppMemberActivityRow$inboundSchema,
} from "./textql-rpc-public-app-app-member-activity-row.js";

export type TextqlRpcPublicAppListMyAppMemberActivityResponse = {
  rows?: Array<TextqlRpcPublicAppAppMemberActivityRow> | undefined;
};

/** @internal */
export const TextqlRpcPublicAppListMyAppMemberActivityResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicAppListMyAppMemberActivityResponse, unknown> = z
    .object({
      rows: types.optional(
        z.array(TextqlRpcPublicAppAppMemberActivityRow$inboundSchema),
      ),
    });

export function textqlRpcPublicAppListMyAppMemberActivityResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicAppListMyAppMemberActivityResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicAppListMyAppMemberActivityResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicAppListMyAppMemberActivityResponse' from JSON`,
  );
}
