/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesLibraryOwnerEntry,
  TextqlRpcPublicPatchesLibraryOwnerEntry$inboundSchema,
} from "./textql-rpc-public-patches-library-owner-entry.js";

export type TextqlRpcPublicPatchesGetEffectiveLibraryOwnersResponse = {
  path?: string | undefined;
  entries?: Array<TextqlRpcPublicPatchesLibraryOwnerEntry> | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetEffectiveLibraryOwnersResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesGetEffectiveLibraryOwnersResponse,
    unknown
  > = z.object({
    path: types.optional(types.string()),
    entries: types.optional(
      z.array(TextqlRpcPublicPatchesLibraryOwnerEntry$inboundSchema),
    ),
  });

export function textqlRpcPublicPatchesGetEffectiveLibraryOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesGetEffectiveLibraryOwnersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesGetEffectiveLibraryOwnersResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPatchesGetEffectiveLibraryOwnersResponse' from JSON`,
  );
}
