/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicChatWarningCategory = {
  WarningCategoryUnspecified: "WARNING_CATEGORY_UNSPECIFIED",
  WarningCategoryCause: "WARNING_CATEGORY_CAUSE",
  WarningCategorySymptom: "WARNING_CATEGORY_SYMPTOM",
  WarningCategoryOutcome: "WARNING_CATEGORY_OUTCOME",
} as const;
export type TextqlRpcPublicChatWarningCategory = OpenEnum<
  typeof TextqlRpcPublicChatWarningCategory
>;

/** @internal */
export const TextqlRpcPublicChatWarningCategory$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicChatWarningCategory,
  unknown
> = openEnums.inboundSchema(TextqlRpcPublicChatWarningCategory);
