/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicChatChat,
  TextqlRpcPublicChatChat$inboundSchema,
} from "./textql-rpc-public-chat-chat.js";

export type TextqlRpcPublicChatGetPlaybookChatsResponse = {
  chats?: Array<TextqlRpcPublicChatChat> | undefined;
};

/** @internal */
export const TextqlRpcPublicChatGetPlaybookChatsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicChatGetPlaybookChatsResponse, unknown> = z
    .object({
      chats: types.optional(z.array(TextqlRpcPublicChatChat$inboundSchema)),
    });

export function textqlRpcPublicChatGetPlaybookChatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicChatGetPlaybookChatsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatGetPlaybookChatsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicChatGetPlaybookChatsResponse' from JSON`,
  );
}
