/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest = {
  path?: string | undefined;
  commitMessage?: string | null | undefined;
  /**
   * When true, delete the directory and all of its contents (files and
   *
   * @remarks
   *  subdirectories) in a single atomic commit. The caller must have write
   *  access to every nested subdirectory. When false (default), the directory
   *  must be empty of non-reserved entries.
   */
  recursive?: boolean | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest$Outbound = {
  path?: string | undefined;
  commitMessage?: string | null | undefined;
  recursive?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest$Outbound,
    TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest
  > = z.object({
    path: z.optional(z.string()),
    commitMessage: z.optional(z.nullable(z.string())),
    recursive: z.optional(z.boolean()),
  });

export function textqlRpcPublicPatchesDeleteOntologyDirectoryRequestToJSON(
  textqlRpcPublicPatchesDeleteOntologyDirectoryRequest:
    TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesDeleteOntologyDirectoryRequest$outboundSchema.parse(
      textqlRpcPublicPatchesDeleteOntologyDirectoryRequest,
    ),
  );
}
