/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicDashboardDashboardCreator = {
  memberId?: string | undefined;
  memberEmail?: string | null | undefined;
  memberName?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicDashboardDashboardCreator$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicDashboardDashboardCreator, unknown> = z.object({
    memberId: types.optional(types.string()),
    memberEmail: z.optional(z.nullable(types.string())),
    memberName: z.optional(z.nullable(types.string())),
  });

export function textqlRpcPublicDashboardDashboardCreatorFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicDashboardDashboardCreator,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicDashboardDashboardCreator$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicDashboardDashboardCreator' from JSON`,
  );
}
