/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicRbacAssignRoleToMemberResponse = {
  success?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacAssignRoleToMemberResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacAssignRoleToMemberResponse, unknown> = z
    .object({
      success: types.optional(types.boolean()),
    });

export function textqlRpcPublicRbacAssignRoleToMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicRbacAssignRoleToMemberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicRbacAssignRoleToMemberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicRbacAssignRoleToMemberResponse' from JSON`,
  );
}
