/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicCellsContextPromptChangeStatus = {
  StatusUnknown: "STATUS_UNKNOWN",
  StatusDraft: "STATUS_DRAFT",
  StatusPending: "STATUS_PENDING",
  StatusRejected: "STATUS_REJECTED",
  StatusApplied: "STATUS_APPLIED",
} as const;
export type TextqlRpcPublicCellsContextPromptChangeStatus = OpenEnum<
  typeof TextqlRpcPublicCellsContextPromptChangeStatus
>;

/** @internal */
export const TextqlRpcPublicCellsContextPromptChangeStatus$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicCellsContextPromptChangeStatus, unknown> =
    openEnums.inboundSchema(TextqlRpcPublicCellsContextPromptChangeStatus);
