/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest = {
  mappingId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest$Outbound = {
  mappingId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest$Outbound,
    TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest
  > = z.object({
    mappingId: z.optional(z.string()),
  });

export function textqlRpcPublicRbacRevertScimGroupMappingToRoleRequestToJSON(
  textqlRpcPublicRbacRevertScimGroupMappingToRoleRequest:
    TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacRevertScimGroupMappingToRoleRequest$outboundSchema.parse(
      textqlRpcPublicRbacRevertScimGroupMappingToRoleRequest,
    ),
  );
}
