/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TextqlRpcPublicCellsQuestionAnswer,
  TextqlRpcPublicCellsQuestionAnswer$Outbound,
  TextqlRpcPublicCellsQuestionAnswer$outboundSchema,
} from "./textql-rpc-public-cells-question-answer.js";

export type TextqlRpcPublicChatDismissQuestionsRequest = {
  /**
   * UUID
   */
  cellId?: string | undefined;
  /**
   * partial answers
   */
  answers?: Array<TextqlRpcPublicCellsQuestionAnswer> | undefined;
};

/** @internal */
export type TextqlRpcPublicChatDismissQuestionsRequest$Outbound = {
  cellId?: string | undefined;
  answers?: Array<TextqlRpcPublicCellsQuestionAnswer$Outbound> | undefined;
};

/** @internal */
export const TextqlRpcPublicChatDismissQuestionsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatDismissQuestionsRequest$Outbound,
    TextqlRpcPublicChatDismissQuestionsRequest
  > = z.object({
    cellId: z.optional(z.string()),
    answers: z.optional(
      z.array(TextqlRpcPublicCellsQuestionAnswer$outboundSchema),
    ),
  });

export function textqlRpcPublicChatDismissQuestionsRequestToJSON(
  textqlRpcPublicChatDismissQuestionsRequest:
    TextqlRpcPublicChatDismissQuestionsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatDismissQuestionsRequest$outboundSchema.parse(
      textqlRpcPublicChatDismissQuestionsRequest,
    ),
  );
}
