/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicRbacMemoryPermissionAction = {
  MemoryActionUnspecified: "MEMORY_ACTION_UNSPECIFIED",
  MemoryActionWrite: "MEMORY_ACTION_WRITE",
} as const;
export type TextqlRpcPublicRbacMemoryPermissionAction = OpenEnum<
  typeof TextqlRpcPublicRbacMemoryPermissionAction
>;

/** @internal */
export const TextqlRpcPublicRbacMemoryPermissionAction$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacMemoryPermissionAction, unknown> = openEnums
    .inboundSchema(TextqlRpcPublicRbacMemoryPermissionAction);
/** @internal */
export const TextqlRpcPublicRbacMemoryPermissionAction$outboundSchema:
  z.ZodMiniType<string, TextqlRpcPublicRbacMemoryPermissionAction> = openEnums
    .outboundSchema(TextqlRpcPublicRbacMemoryPermissionAction);
