/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesListLibraryImportsRequest = {};

/** @internal */
export type TextqlRpcPublicPatchesListLibraryImportsRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicPatchesListLibraryImportsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesListLibraryImportsRequest$Outbound,
    TextqlRpcPublicPatchesListLibraryImportsRequest
  > = z.object({});

export function textqlRpcPublicPatchesListLibraryImportsRequestToJSON(
  textqlRpcPublicPatchesListLibraryImportsRequest:
    TextqlRpcPublicPatchesListLibraryImportsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesListLibraryImportsRequest$outboundSchema.parse(
      textqlRpcPublicPatchesListLibraryImportsRequest,
    ),
  );
}
