/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicChatDashboardArtifactData = {
  dashboardId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicChatDashboardArtifactData$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicChatDashboardArtifactData, unknown> = z.object({
    dashboardId: types.optional(types.string()),
  });

export function textqlRpcPublicChatDashboardArtifactDataFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicChatDashboardArtifactData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatDashboardArtifactData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicChatDashboardArtifactData' from JSON`,
  );
}
