/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest = {
  connectorId?: number | undefined;
  workspaceId?: string | undefined;
  reportId?: string | undefined;
  datasetId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest$Outbound = {
  connectorId?: number | undefined;
  workspaceId?: string | undefined;
  reportId?: string | undefined;
  datasetId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest$Outbound,
    TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest
  > = z.object({
    connectorId: z.optional(z.int()),
    workspaceId: z.optional(z.string()),
    reportId: z.optional(z.string()),
    datasetId: z.optional(z.string()),
  });

export function textqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequestToJSON(
  textqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest:
    TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest$outboundSchema.parse(
      textqlRpcPublicPowerbiGeneratePowerBIEmbedTokenRequest,
    ),
  );
}
