/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicChatThreadWarningType,
  TextqlRpcPublicChatThreadWarningType$inboundSchema,
} from "./textql-rpc-public-chat-thread-warning-type.js";

export type TextqlRpcPublicObserveWarningTypeCount = {
  /**
   * ThreadWarningType is the canonical set of thread warning types
   */
  warningType?: TextqlRpcPublicChatThreadWarningType | undefined;
  total?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicObserveWarningTypeCount$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicObserveWarningTypeCount, unknown> = z.object({
    warningType: types.optional(
      TextqlRpcPublicChatThreadWarningType$inboundSchema,
    ),
    total: types.optional(types.number()),
  });

export function textqlRpcPublicObserveWarningTypeCountFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicObserveWarningTypeCount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicObserveWarningTypeCount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicObserveWarningTypeCount' from JSON`,
  );
}
