/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesConfigureOntologyRemoteRequest = {
  remoteUrl?: string | undefined;
  authType?: string | undefined;
  token?: string | null | undefined;
  sshPrivateKey?: string | null | undefined;
  sshKeyPassword?: string | null | undefined;
  defaultBranch?: string | null | undefined;
  githubAppId?: string | null | undefined;
  githubAppInstallationId?: string | null | undefined;
  githubAppPrivateKey?: string | null | undefined;
  signingKeyType?: string | null | undefined;
  signingKey?: string | null | undefined;
  pushMode?: string | null | undefined;
  useHostedGithubApp?: boolean | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesConfigureOntologyRemoteRequest$Outbound = {
  remoteUrl?: string | undefined;
  authType?: string | undefined;
  token?: string | null | undefined;
  sshPrivateKey?: string | null | undefined;
  sshKeyPassword?: string | null | undefined;
  defaultBranch?: string | null | undefined;
  githubAppId?: string | null | undefined;
  githubAppInstallationId?: string | null | undefined;
  githubAppPrivateKey?: string | null | undefined;
  signingKeyType?: string | null | undefined;
  signingKey?: string | null | undefined;
  pushMode?: string | null | undefined;
  useHostedGithubApp?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesConfigureOntologyRemoteRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesConfigureOntologyRemoteRequest$Outbound,
    TextqlRpcPublicPatchesConfigureOntologyRemoteRequest
  > = z.object({
    remoteUrl: z.optional(z.string()),
    authType: z.optional(z.string()),
    token: z.optional(z.nullable(z.string())),
    sshPrivateKey: z.optional(z.nullable(z.string())),
    sshKeyPassword: z.optional(z.nullable(z.string())),
    defaultBranch: z.optional(z.nullable(z.string())),
    githubAppId: z.optional(z.nullable(z.string())),
    githubAppInstallationId: z.optional(z.nullable(z.string())),
    githubAppPrivateKey: z.optional(z.nullable(z.string())),
    signingKeyType: z.optional(z.nullable(z.string())),
    signingKey: z.optional(z.nullable(z.string())),
    pushMode: z.optional(z.nullable(z.string())),
    useHostedGithubApp: z.optional(z.boolean()),
  });

export function textqlRpcPublicPatchesConfigureOntologyRemoteRequestToJSON(
  textqlRpcPublicPatchesConfigureOntologyRemoteRequest:
    TextqlRpcPublicPatchesConfigureOntologyRemoteRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesConfigureOntologyRemoteRequest$outboundSchema.parse(
      textqlRpcPublicPatchesConfigureOntologyRemoteRequest,
    ),
  );
}
