/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicApiOauthPollDeviceCodeTokenResponse = {
  /**
   * "pending", "slow_down", "success", "expired", "denied", "error"
   */
  status?: string | undefined;
  /**
   * only on "success"
   */
  displayName?: string | undefined;
  errorDescription?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicApiOauthPollDeviceCodeTokenResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicApiOauthPollDeviceCodeTokenResponse, unknown> = z
    .object({
      status: types.optional(types.string()),
      displayName: types.optional(types.string()),
      errorDescription: types.optional(types.string()),
    });

export function textqlRpcPublicApiOauthPollDeviceCodeTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicApiOauthPollDeviceCodeTokenResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicApiOauthPollDeviceCodeTokenResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicApiOauthPollDeviceCodeTokenResponse' from JSON`,
  );
}
