/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacListAccessRequestsRequest = {
  objectType?: string | null | undefined;
  objectId?: string | null | undefined;
  /**
   * pending, approved, rejected
   */
  status?: string | null | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacListAccessRequestsRequest$Outbound = {
  objectType?: string | null | undefined;
  objectId?: string | null | undefined;
  status?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacListAccessRequestsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicRbacListAccessRequestsRequest$Outbound,
    TextqlRpcPublicRbacListAccessRequestsRequest
  > = z.object({
    objectType: z.optional(z.nullable(z.string())),
    objectId: z.optional(z.nullable(z.string())),
    status: z.optional(z.nullable(z.string())),
  });

export function textqlRpcPublicRbacListAccessRequestsRequestToJSON(
  textqlRpcPublicRbacListAccessRequestsRequest:
    TextqlRpcPublicRbacListAccessRequestsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacListAccessRequestsRequest$outboundSchema.parse(
      textqlRpcPublicRbacListAccessRequestsRequest,
    ),
  );
}
