/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicChatAttachDashboardRequest = {
  chatId: string;
  /**
   * uses latest version
   */
  dashboardId: string;
};

/** @internal */
export type TextqlRpcPublicChatAttachDashboardRequest$Outbound = {
  chatId: string;
  dashboardId: string;
};

/** @internal */
export const TextqlRpcPublicChatAttachDashboardRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatAttachDashboardRequest$Outbound,
    TextqlRpcPublicChatAttachDashboardRequest
  > = z.object({
    chatId: z.string(),
    dashboardId: z.string(),
  });

export function textqlRpcPublicChatAttachDashboardRequestToJSON(
  textqlRpcPublicChatAttachDashboardRequest:
    TextqlRpcPublicChatAttachDashboardRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatAttachDashboardRequest$outboundSchema.parse(
      textqlRpcPublicChatAttachDashboardRequest,
    ),
  );
}
