/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicObservePlaybookBillingStat = {
  playbookId?: string | undefined;
  playbookName?: string | undefined;
  ownerId?: string | undefined;
  ownerName?: string | undefined;
  totalAcu?: number | undefined;
  llmAcu?: number | undefined;
  computeAcu?: number | undefined;
  runCount?: number | undefined;
  dailyRunCounts?: Array<number> | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicObservePlaybookBillingStat$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicObservePlaybookBillingStat, unknown> = z.object({
    playbookId: types.optional(types.string()),
    playbookName: types.optional(types.string()),
    ownerId: types.optional(types.string()),
    ownerName: types.optional(types.string()),
    totalAcu: types.optional(types.number()),
    llmAcu: types.optional(types.number()),
    computeAcu: types.optional(types.number()),
    runCount: types.optional(types.number()),
    dailyRunCounts: types.optional(z.array(types.number())),
    isActive: types.optional(types.boolean()),
  });

export function textqlRpcPublicObservePlaybookBillingStatFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicObservePlaybookBillingStat,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicObservePlaybookBillingStat$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicObservePlaybookBillingStat' from JSON`,
  );
}
