/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicDashboardDashboardFolder,
  TextqlRpcPublicDashboardDashboardFolder$inboundSchema,
} from "./textql-rpc-public-dashboard-dashboard-folder.js";

export type TextqlRpcPublicDashboardCreateDashboardFolderResponse = {
  /**
   * Dashboard folder for hierarchical organization
   */
  folder?: TextqlRpcPublicDashboardDashboardFolder | undefined;
};

/** @internal */
export const TextqlRpcPublicDashboardCreateDashboardFolderResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicDashboardCreateDashboardFolderResponse,
    unknown
  > = z.object({
    folder: types.optional(
      TextqlRpcPublicDashboardDashboardFolder$inboundSchema,
    ),
  });

export function textqlRpcPublicDashboardCreateDashboardFolderResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicDashboardCreateDashboardFolderResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicDashboardCreateDashboardFolderResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicDashboardCreateDashboardFolderResponse' from JSON`,
  );
}
