/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponse = {
  count?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponse,
    unknown
  > = z.object({
    count: types.optional(types.number()),
  });

export function textqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPlaybookGetActiveSubscribedPlaybooksCountResponse' from JSON`,
  );
}
