/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request full artifact data when item is selected
 */
export type TextqlRpcPublicChatGetArtifactRequest = {
  /**
   * Cell ID or composite "cellId:type:url" for multi-artifact cells
   */
  artifactId: string;
  chatId: string;
};

/** @internal */
export type TextqlRpcPublicChatGetArtifactRequest$Outbound = {
  artifactId: string;
  chatId: string;
};

/** @internal */
export const TextqlRpcPublicChatGetArtifactRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatGetArtifactRequest$Outbound,
    TextqlRpcPublicChatGetArtifactRequest
  > = z.object({
    artifactId: z.string(),
    chatId: z.string(),
  });

export function textqlRpcPublicChatGetArtifactRequestToJSON(
  textqlRpcPublicChatGetArtifactRequest: TextqlRpcPublicChatGetArtifactRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatGetArtifactRequest$outboundSchema.parse(
      textqlRpcPublicChatGetArtifactRequest,
    ),
  );
}
