/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPowerbiExportPowerBIReportImageResponse = {
  imageData?: string | undefined;
  imageUrl?: string | undefined;
  error?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicPowerbiExportPowerBIReportImageResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPowerbiExportPowerBIReportImageResponse,
    unknown
  > = z.object({
    imageData: types.optional(types.string()),
    imageUrl: types.optional(types.string()),
    error: z.optional(z.nullable(types.string())),
  });

export function textqlRpcPublicPowerbiExportPowerBIReportImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPowerbiExportPowerBIReportImageResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPowerbiExportPowerBIReportImageResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPowerbiExportPowerBIReportImageResponse' from JSON`,
  );
}
