/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicMetricsExportTriggerMetricsPushResponse = {
  triggered?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicMetricsExportTriggerMetricsPushResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicMetricsExportTriggerMetricsPushResponse,
    unknown
  > = z.object({
    triggered: types.optional(types.boolean()),
  });

export function textqlRpcPublicMetricsExportTriggerMetricsPushResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicMetricsExportTriggerMetricsPushResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicMetricsExportTriggerMetricsPushResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicMetricsExportTriggerMetricsPushResponse' from JSON`,
  );
}
