/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse = {
  success?: boolean | undefined;
  errorMessage?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse,
    unknown
  > = z.object({
    success: types.optional(types.boolean()),
    errorMessage: types.optional(types.string()),
  });

export function textqlRpcPublicMetricsExportTestMetricsExportConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicMetricsExportTestMetricsExportConnectionResponse' from JSON`,
  );
}
