/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesGetOntologyAnaConfigRequest = {
  path?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesGetOntologyAnaConfigRequest$Outbound = {
  path?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetOntologyAnaConfigRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesGetOntologyAnaConfigRequest$Outbound,
    TextqlRpcPublicPatchesGetOntologyAnaConfigRequest
  > = z.object({
    path: z.optional(z.string()),
  });

export function textqlRpcPublicPatchesGetOntologyAnaConfigRequestToJSON(
  textqlRpcPublicPatchesGetOntologyAnaConfigRequest:
    TextqlRpcPublicPatchesGetOntologyAnaConfigRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesGetOntologyAnaConfigRequest$outboundSchema.parse(
      textqlRpcPublicPatchesGetOntologyAnaConfigRequest,
    ),
  );
}
