/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicAuditLogTriggerOtlpExportRequest = {};

/** @internal */
export type TextqlRpcPublicAuditLogTriggerOtlpExportRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicAuditLogTriggerOtlpExportRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicAuditLogTriggerOtlpExportRequest$Outbound,
    TextqlRpcPublicAuditLogTriggerOtlpExportRequest
  > = z.object({});

export function textqlRpcPublicAuditLogTriggerOtlpExportRequestToJSON(
  textqlRpcPublicAuditLogTriggerOtlpExportRequest:
    TextqlRpcPublicAuditLogTriggerOtlpExportRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicAuditLogTriggerOtlpExportRequest$outboundSchema.parse(
      textqlRpcPublicAuditLogTriggerOtlpExportRequest,
    ),
  );
}
