/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * PatchObject is one config object parsed from a patch ref.
 */
export type TextqlRpcPublicPatchesGetPatchCapabilitiesRequest = {
  /**
   * Library path of the file that defines the object
   */
  patchId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesGetPatchCapabilitiesRequest$Outbound = {
  patchId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetPatchCapabilitiesRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesGetPatchCapabilitiesRequest$Outbound,
    TextqlRpcPublicPatchesGetPatchCapabilitiesRequest
  > = z.object({
    patchId: z.optional(z.string()),
  });

export function textqlRpcPublicPatchesGetPatchCapabilitiesRequestToJSON(
  textqlRpcPublicPatchesGetPatchCapabilitiesRequest:
    TextqlRpcPublicPatchesGetPatchCapabilitiesRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesGetPatchCapabilitiesRequest$outboundSchema.parse(
      textqlRpcPublicPatchesGetPatchCapabilitiesRequest,
    ),
  );
}
