/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicConnectorMicrosoft365Metadata = {
  tenantId?: string | undefined;
  clientId?: string | undefined;
  clientSecret?: string | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  memberId?: string | undefined;
  /**
   * ISO 8601 timestamp
   */
  tokenExpiry?: string | undefined;
  /**
   * When true, only email metadata is accessible (no body content)
   */
  metadataOnly?: boolean | undefined;
  scopes?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorMicrosoft365Metadata$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicConnectorMicrosoft365Metadata, unknown> = z
    .object({
      tenantId: types.optional(types.string()),
      clientId: types.optional(types.string()),
      clientSecret: types.optional(types.string()),
      accessToken: types.optional(types.string()),
      refreshToken: types.optional(types.string()),
      memberId: types.optional(types.string()),
      tokenExpiry: types.optional(types.string()),
      metadataOnly: types.optional(types.boolean()),
      scopes: types.optional(z.array(types.string())),
    });
/** @internal */
export type TextqlRpcPublicConnectorMicrosoft365Metadata$Outbound = {
  tenantId?: string | undefined;
  clientId?: string | undefined;
  clientSecret?: string | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  memberId?: string | undefined;
  tokenExpiry?: string | undefined;
  metadataOnly?: boolean | undefined;
  scopes?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorMicrosoft365Metadata$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorMicrosoft365Metadata$Outbound,
    TextqlRpcPublicConnectorMicrosoft365Metadata
  > = z.object({
    tenantId: z.optional(z.string()),
    clientId: z.optional(z.string()),
    clientSecret: z.optional(z.string()),
    accessToken: z.optional(z.string()),
    refreshToken: z.optional(z.string()),
    memberId: z.optional(z.string()),
    tokenExpiry: z.optional(z.string()),
    metadataOnly: z.optional(z.boolean()),
    scopes: z.optional(z.array(z.string())),
  });

export function textqlRpcPublicConnectorMicrosoft365MetadataToJSON(
  textqlRpcPublicConnectorMicrosoft365Metadata:
    TextqlRpcPublicConnectorMicrosoft365Metadata,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorMicrosoft365Metadata$outboundSchema.parse(
      textqlRpcPublicConnectorMicrosoft365Metadata,
    ),
  );
}
export function textqlRpcPublicConnectorMicrosoft365MetadataFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicConnectorMicrosoft365Metadata,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorMicrosoft365Metadata$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicConnectorMicrosoft365Metadata' from JSON`,
  );
}
