/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicRbacGroupPermissionAction = {
  GroupActionUnspecified: "GROUP_ACTION_UNSPECIFIED",
  GroupActionRead: "GROUP_ACTION_READ",
  GroupActionWrite: "GROUP_ACTION_WRITE",
} as const;
export type TextqlRpcPublicRbacGroupPermissionAction = OpenEnum<
  typeof TextqlRpcPublicRbacGroupPermissionAction
>;

/** @internal */
export const TextqlRpcPublicRbacGroupPermissionAction$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacGroupPermissionAction, unknown> = openEnums
    .inboundSchema(TextqlRpcPublicRbacGroupPermissionAction);
/** @internal */
export const TextqlRpcPublicRbacGroupPermissionAction$outboundSchema:
  z.ZodMiniType<string, TextqlRpcPublicRbacGroupPermissionAction> = openEnums
    .outboundSchema(TextqlRpcPublicRbacGroupPermissionAction);
