/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TextqlRpcPublicAgentSlackAgentTrigger,
  TextqlRpcPublicAgentSlackAgentTrigger$Outbound,
  TextqlRpcPublicAgentSlackAgentTrigger$outboundSchema,
} from "./textql-rpc-public-agent-slack-agent-trigger.js";
import {
  TextqlRpcPublicChatLlmModel,
  TextqlRpcPublicChatLlmModel$outboundSchema,
} from "./textql-rpc-public-chat-llm-model.js";
import {
  TextqlRpcPublicParadigmParadigmOptions,
  TextqlRpcPublicParadigmParadigmOptions$Outbound,
  TextqlRpcPublicParadigmParadigmOptions$outboundSchema,
} from "./textql-rpc-public-paradigm-paradigm-options.js";

export type TextqlRpcPublicAgentCreateAgentRequest = {
  name?: string | undefined;
  prompt?: string | undefined;
  paradigmOptions?: TextqlRpcPublicParadigmParadigmOptions | undefined;
  sourceSuggestionId?: string | undefined;
  slackChannelId?: string | null | undefined;
  slackDmUserIds?: Array<string> | undefined;
  skipOrgDefaultChannel?: boolean | undefined;
  llmModel?: TextqlRpcPublicChatLlmModel | undefined;
  fastMode?: boolean | null | undefined;
  isStateful?: boolean | null | undefined;
  postingFrequencyCrons?: Array<string> | undefined;
  emailRecipientMemberIds?: Array<string> | undefined;
  channelIds?: Array<string> | undefined;
  teamsChannelId?: string | null | undefined;
  teamsDmUserAadIds?: Array<string> | undefined;
  slackTrigger?: TextqlRpcPublicAgentSlackAgentTrigger | undefined;
  /**
   * Index-aligned with posting_frequency_crons. A non-empty cadence
   *
   * @remarks
   *  (HOURLY/FOUR-HOUR/EIGHT-HOUR/DAILY/WEEKLY) marks a flexible schedule whose
   *  cron the backend generates; "" (or an empty list) means exact.
   */
  postingFrequencyCadences?: Array<string> | undefined;
};

/** @internal */
export type TextqlRpcPublicAgentCreateAgentRequest$Outbound = {
  name?: string | undefined;
  prompt?: string | undefined;
  paradigmOptions?: TextqlRpcPublicParadigmParadigmOptions$Outbound | undefined;
  sourceSuggestionId?: string | undefined;
  slackChannelId?: string | null | undefined;
  slackDmUserIds?: Array<string> | undefined;
  skipOrgDefaultChannel?: boolean | undefined;
  llmModel?: string | undefined;
  fastMode?: boolean | null | undefined;
  isStateful?: boolean | null | undefined;
  postingFrequencyCrons?: Array<string> | undefined;
  emailRecipientMemberIds?: Array<string> | undefined;
  channelIds?: Array<string> | undefined;
  teamsChannelId?: string | null | undefined;
  teamsDmUserAadIds?: Array<string> | undefined;
  slackTrigger?: TextqlRpcPublicAgentSlackAgentTrigger$Outbound | undefined;
  postingFrequencyCadences?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicAgentCreateAgentRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicAgentCreateAgentRequest$Outbound,
    TextqlRpcPublicAgentCreateAgentRequest
  > = z.object({
    name: z.optional(z.string()),
    prompt: z.optional(z.string()),
    paradigmOptions: z.optional(
      TextqlRpcPublicParadigmParadigmOptions$outboundSchema,
    ),
    sourceSuggestionId: z.optional(z.string()),
    slackChannelId: z.optional(z.nullable(z.string())),
    slackDmUserIds: z.optional(z.array(z.string())),
    skipOrgDefaultChannel: z.optional(z.boolean()),
    llmModel: z.optional(TextqlRpcPublicChatLlmModel$outboundSchema),
    fastMode: z.optional(z.nullable(z.boolean())),
    isStateful: z.optional(z.nullable(z.boolean())),
    postingFrequencyCrons: z.optional(z.array(z.string())),
    emailRecipientMemberIds: z.optional(z.array(z.string())),
    channelIds: z.optional(z.array(z.string())),
    teamsChannelId: z.optional(z.nullable(z.string())),
    teamsDmUserAadIds: z.optional(z.array(z.string())),
    slackTrigger: z.optional(
      TextqlRpcPublicAgentSlackAgentTrigger$outboundSchema,
    ),
    postingFrequencyCadences: z.optional(z.array(z.string())),
  });

export function textqlRpcPublicAgentCreateAgentRequestToJSON(
  textqlRpcPublicAgentCreateAgentRequest:
    TextqlRpcPublicAgentCreateAgentRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicAgentCreateAgentRequest$outboundSchema.parse(
      textqlRpcPublicAgentCreateAgentRequest,
    ),
  );
}
