/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TextqlRpcPublicCellsQuestionAnswer,
  TextqlRpcPublicCellsQuestionAnswer$Outbound,
  TextqlRpcPublicCellsQuestionAnswer$outboundSchema,
} from "./textql-rpc-public-cells-question-answer.js";

export type TextqlRpcPublicChatSubmitQuestionsRequest = {
  /**
   * UUID
   */
  cellId?: string | undefined;
  answers?: Array<TextqlRpcPublicCellsQuestionAnswer> | undefined;
};

/** @internal */
export type TextqlRpcPublicChatSubmitQuestionsRequest$Outbound = {
  cellId?: string | undefined;
  answers?: Array<TextqlRpcPublicCellsQuestionAnswer$Outbound> | undefined;
};

/** @internal */
export const TextqlRpcPublicChatSubmitQuestionsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatSubmitQuestionsRequest$Outbound,
    TextqlRpcPublicChatSubmitQuestionsRequest
  > = z.object({
    cellId: z.optional(z.string()),
    answers: z.optional(
      z.array(TextqlRpcPublicCellsQuestionAnswer$outboundSchema),
    ),
  });

export function textqlRpcPublicChatSubmitQuestionsRequestToJSON(
  textqlRpcPublicChatSubmitQuestionsRequest:
    TextqlRpcPublicChatSubmitQuestionsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatSubmitQuestionsRequest$outboundSchema.parse(
      textqlRpcPublicChatSubmitQuestionsRequest,
    ),
  );
}
