/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicObserveAccessMethodCount = {
  method?: string | undefined;
  total?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicObserveAccessMethodCount$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicObserveAccessMethodCount, unknown> = z.object({
    method: types.optional(types.string()),
    total: types.optional(types.number()),
  });

export function textqlRpcPublicObserveAccessMethodCountFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicObserveAccessMethodCount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicObserveAccessMethodCount$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicObserveAccessMethodCount' from JSON`,
  );
}
