/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Preview cell reference for report history
 */
export type TextqlRpcPublicCellsPreviewCellRef = {
  target?: string | undefined;
  previewType?: string | undefined;
  name?: string | undefined;
  url?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicCellsPreviewCellRef$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicCellsPreviewCellRef,
  unknown
> = z.object({
  target: types.optional(types.string()),
  previewType: types.optional(types.string()),
  name: types.optional(types.string()),
  url: z.optional(z.nullable(types.string())),
});

export function textqlRpcPublicCellsPreviewCellRefFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicCellsPreviewCellRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicCellsPreviewCellRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicCellsPreviewCellRef' from JSON`,
  );
}
