/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicMCPToggleMCPServerRequest = {
  id?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicMCPToggleMCPServerRequest$Outbound = {
  id?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicMCPToggleMCPServerRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicMCPToggleMCPServerRequest$Outbound,
    TextqlRpcPublicMCPToggleMCPServerRequest
  > = z.object({
    id: z.optional(z.string()),
  });

export function textqlRpcPublicMCPToggleMCPServerRequestToJSON(
  textqlRpcPublicMCPToggleMCPServerRequest:
    TextqlRpcPublicMCPToggleMCPServerRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicMCPToggleMCPServerRequest$outboundSchema.parse(
      textqlRpcPublicMCPToggleMCPServerRequest,
    ),
  );
}
