/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesGetPatchByNumberRequest = {
  number?: number | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesGetPatchByNumberRequest$Outbound = {
  number?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetPatchByNumberRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesGetPatchByNumberRequest$Outbound,
    TextqlRpcPublicPatchesGetPatchByNumberRequest
  > = z.object({
    number: z.optional(z.int()),
  });

export function textqlRpcPublicPatchesGetPatchByNumberRequestToJSON(
  textqlRpcPublicPatchesGetPatchByNumberRequest:
    TextqlRpcPublicPatchesGetPatchByNumberRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesGetPatchByNumberRequest$outboundSchema.parse(
      textqlRpcPublicPatchesGetPatchByNumberRequest,
    ),
  );
}
