/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicCellsContextPromptChangeStatus,
  TextqlRpcPublicCellsContextPromptChangeStatus$inboundSchema,
} from "./textql-rpc-public-cells-context-prompt-change-status.js";

export type TextqlRpcPublicChatApproveContextPromptChangeResponse = {
  success?: boolean | undefined;
  /**
   * range: [0, 1]
   */
  message?: string | undefined;
  status?: TextqlRpcPublicCellsContextPromptChangeStatus | undefined;
  /**
   * Estimated sandbox/compute cost for this chat (USD): chat sandbox-seconds →
   *
   * @remarks
   *  ACUs → USD at the org's effective rate. Add to estimated_cost for the
   *  thread's total cost. Requires the console rate (0/omitted if unavailable).
   */
  resumed?: boolean | undefined;
  /**
   * The chat's sandbox id ({orgID}-{chatID}), set when the thread used any
   *
   * @remarks
   *  sandbox compute. Lets the UI deep-link to the sandbox detail. Empty/omitted
   *  when the thread had no sandbox usage.
   */
  resumeError?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicChatApproveContextPromptChangeResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatApproveContextPromptChangeResponse,
    unknown
  > = z.object({
    success: types.optional(types.boolean()),
    message: types.optional(types.string()),
    status: types.optional(
      TextqlRpcPublicCellsContextPromptChangeStatus$inboundSchema,
    ),
    resumed: types.optional(types.boolean()),
    resumeError: types.optional(types.string()),
  });

export function textqlRpcPublicChatApproveContextPromptChangeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicChatApproveContextPromptChangeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatApproveContextPromptChangeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicChatApproveContextPromptChangeResponse' from JSON`,
  );
}
