/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesOntologyAnaConfig,
  TextqlRpcPublicPatchesOntologyAnaConfig$inboundSchema,
} from "./textql-rpc-public-patches-ontology-ana-config.js";

export type TextqlRpcPublicPatchesGetOntologyAnaConfigResponse = {
  config?: TextqlRpcPublicPatchesOntologyAnaConfig | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetOntologyAnaConfigResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesGetOntologyAnaConfigResponse, unknown> = z
    .object({
      config: types.optional(
        TextqlRpcPublicPatchesOntologyAnaConfig$inboundSchema,
      ),
    });

export function textqlRpcPublicPatchesGetOntologyAnaConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesGetOntologyAnaConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesGetOntologyAnaConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesGetOntologyAnaConfigResponse' from JSON`,
  );
}
