/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPowerbiPowerBITablePreviewTotalRows =
  | number
  | string;

export type TextqlRpcPublicPowerbiPowerBITablePreview = {
  tableName?: string | undefined;
  arrowData?: string | undefined;
  totalRows?: number | string | undefined;
  error?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicPowerbiPowerBITablePreviewTotalRows$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPowerbiPowerBITablePreviewTotalRows, unknown> =
    smartUnion([types.number(), types.string()]);

export function textqlRpcPublicPowerbiPowerBITablePreviewTotalRowsFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPowerbiPowerBITablePreviewTotalRows,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPowerbiPowerBITablePreviewTotalRows$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPowerbiPowerBITablePreviewTotalRows' from JSON`,
  );
}

/** @internal */
export const TextqlRpcPublicPowerbiPowerBITablePreview$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPowerbiPowerBITablePreview, unknown> = z.object({
    tableName: types.optional(types.string()),
    arrowData: types.optional(types.string()),
    totalRows: types.optional(smartUnion([types.number(), types.string()])),
    error: z.optional(z.nullable(types.string())),
  });

export function textqlRpcPublicPowerbiPowerBITablePreviewFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPowerbiPowerBITablePreview,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPowerbiPowerBITablePreview$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPowerbiPowerBITablePreview' from JSON`,
  );
}
