/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicConnectorConnectorContext,
  TextqlRpcPublicConnectorConnectorContext$inboundSchema,
} from "./textql-rpc-public-connector-connector-context.js";
import {
  TextqlRpcPublicConnectorFeatureType,
  TextqlRpcPublicConnectorFeatureType$inboundSchema,
} from "./textql-rpc-public-connector-feature-type.js";
import {
  TextqlRpcPublicConnectorMessageSegment,
  TextqlRpcPublicConnectorMessageSegment$inboundSchema,
} from "./textql-rpc-public-connector-message-segment.js";

export type TextqlRpcPublicConnectorExampleQuery = {
  /**
   * dataset IDs for selected Tableau collections
   */
  id?: string | undefined;
  label?: string | undefined;
  message?: string | undefined;
  isMultiSource?: boolean | undefined;
  requiredConnectorIds?: Array<number> | undefined;
  category?: string | undefined;
  segments?: Array<TextqlRpcPublicConnectorMessageSegment> | undefined;
  requiredFeatures?: Array<TextqlRpcPublicConnectorFeatureType> | undefined;
  sourceContext?: TextqlRpcPublicConnectorConnectorContext | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorExampleQuery$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicConnectorExampleQuery,
  unknown
> = z.object({
  id: types.optional(types.string()),
  label: types.optional(types.string()),
  message: types.optional(types.string()),
  isMultiSource: types.optional(types.boolean()),
  requiredConnectorIds: types.optional(z.array(types.number())),
  category: types.optional(types.string()),
  segments: types.optional(
    z.array(TextqlRpcPublicConnectorMessageSegment$inboundSchema),
  ),
  requiredFeatures: types.optional(
    z.array(TextqlRpcPublicConnectorFeatureType$inboundSchema),
  ),
  sourceContext: types.optional(
    TextqlRpcPublicConnectorConnectorContext$inboundSchema,
  ),
});

export function textqlRpcPublicConnectorExampleQueryFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicConnectorExampleQuery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorExampleQuery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicConnectorExampleQuery' from JSON`,
  );
}
