/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicConnectorTableauConnectorContext = {
  /**
   * dataset IDs for selected Tableau collections
   */
  collectionIds?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorTableauConnectorContext$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicConnectorTableauConnectorContext, unknown> = z
    .object({
      collectionIds: types.optional(z.array(types.string())),
    });
/** @internal */
export type TextqlRpcPublicConnectorTableauConnectorContext$Outbound = {
  collectionIds?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorTableauConnectorContext$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorTableauConnectorContext$Outbound,
    TextqlRpcPublicConnectorTableauConnectorContext
  > = z.object({
    collectionIds: z.optional(z.array(z.string())),
  });

export function textqlRpcPublicConnectorTableauConnectorContextToJSON(
  textqlRpcPublicConnectorTableauConnectorContext:
    TextqlRpcPublicConnectorTableauConnectorContext,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorTableauConnectorContext$outboundSchema.parse(
      textqlRpcPublicConnectorTableauConnectorContext,
    ),
  );
}
export function textqlRpcPublicConnectorTableauConnectorContextFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicConnectorTableauConnectorContext,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorTableauConnectorContext$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicConnectorTableauConnectorContext' from JSON`,
  );
}
