/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicCellsBashCell = {
  script?: string | undefined;
  stdout?: string | undefined;
  stderr?: string | undefined;
  exitCode?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicCellsBashCell$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicCellsBashCell,
  unknown
> = z.object({
  script: types.optional(types.string()),
  stdout: types.optional(types.string()),
  stderr: types.optional(types.string()),
  exitCode: types.optional(types.number()),
});

export function textqlRpcPublicCellsBashCellFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicCellsBashCell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextqlRpcPublicCellsBashCell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicCellsBashCell' from JSON`,
  );
}
