/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicTeamsTeamsSyncWorkspaceResponse = {
  queued?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicTeamsTeamsSyncWorkspaceResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicTeamsTeamsSyncWorkspaceResponse, unknown> = z
    .object({
      queued: types.optional(types.boolean()),
      message: types.optional(types.string()),
    });

export function textqlRpcPublicTeamsTeamsSyncWorkspaceResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicTeamsTeamsSyncWorkspaceResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicTeamsTeamsSyncWorkspaceResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicTeamsTeamsSyncWorkspaceResponse' from JSON`,
  );
}
