/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TextqlRpcPublicDashboardDataSource,
  TextqlRpcPublicDashboardDataSource$Outbound,
  TextqlRpcPublicDashboardDataSource$outboundSchema,
} from "./textql-rpc-public-dashboard-data-source.js";

export type TextqlRpcPublicDashboardDataSourcesPatch = {
  sources?: Array<TextqlRpcPublicDashboardDataSource> | undefined;
};

/** @internal */
export type TextqlRpcPublicDashboardDataSourcesPatch$Outbound = {
  sources?: Array<TextqlRpcPublicDashboardDataSource$Outbound> | undefined;
};

/** @internal */
export const TextqlRpcPublicDashboardDataSourcesPatch$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicDashboardDataSourcesPatch$Outbound,
    TextqlRpcPublicDashboardDataSourcesPatch
  > = z.object({
    sources: z.optional(
      z.array(TextqlRpcPublicDashboardDataSource$outboundSchema),
    ),
  });

export function textqlRpcPublicDashboardDataSourcesPatchToJSON(
  textqlRpcPublicDashboardDataSourcesPatch:
    TextqlRpcPublicDashboardDataSourcesPatch,
): string {
  return JSON.stringify(
    TextqlRpcPublicDashboardDataSourcesPatch$outboundSchema.parse(
      textqlRpcPublicDashboardDataSourcesPatch,
    ),
  );
}
