/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicCellsQuestionsStatus = {
  QuestionsStatusUnknown: "QUESTIONS_STATUS_UNKNOWN",
  QuestionsStatusPending: "QUESTIONS_STATUS_PENDING",
  QuestionsStatusAnswered: "QUESTIONS_STATUS_ANSWERED",
  QuestionsStatusDismissed: "QUESTIONS_STATUS_DISMISSED",
} as const;
export type TextqlRpcPublicCellsQuestionsStatus = OpenEnum<
  typeof TextqlRpcPublicCellsQuestionsStatus
>;

/** @internal */
export const TextqlRpcPublicCellsQuestionsStatus$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicCellsQuestionsStatus,
  unknown
> = openEnums.inboundSchema(TextqlRpcPublicCellsQuestionsStatus);
