/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicConnectorPowerBIConnectorContext = {
  /**
   * PowerBI report IDs
   */
  reportIds?: Array<string> | undefined;
  /**
   * PowerBI dataset IDs (PowerBI datasets, not internal dataset_source)
   */
  datasetIds?: Array<string> | undefined;
  /**
   * workspace dataset_source IDs (cache key, like Tableau collections)
   */
  collectionIds?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorPowerBIConnectorContext$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicConnectorPowerBIConnectorContext, unknown> = z
    .object({
      reportIds: types.optional(z.array(types.string())),
      datasetIds: types.optional(z.array(types.string())),
      collectionIds: types.optional(z.array(types.string())),
    });
/** @internal */
export type TextqlRpcPublicConnectorPowerBIConnectorContext$Outbound = {
  reportIds?: Array<string> | undefined;
  datasetIds?: Array<string> | undefined;
  collectionIds?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorPowerBIConnectorContext$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorPowerBIConnectorContext$Outbound,
    TextqlRpcPublicConnectorPowerBIConnectorContext
  > = z.object({
    reportIds: z.optional(z.array(z.string())),
    datasetIds: z.optional(z.array(z.string())),
    collectionIds: z.optional(z.array(z.string())),
  });

export function textqlRpcPublicConnectorPowerBIConnectorContextToJSON(
  textqlRpcPublicConnectorPowerBIConnectorContext:
    TextqlRpcPublicConnectorPowerBIConnectorContext,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorPowerBIConnectorContext$outboundSchema.parse(
      textqlRpcPublicConnectorPowerBIConnectorContext,
    ),
  );
}
export function textqlRpcPublicConnectorPowerBIConnectorContextFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicConnectorPowerBIConnectorContext,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorPowerBIConnectorContext$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicConnectorPowerBIConnectorContext' from JSON`,
  );
}
