/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicChatDuplicateChatRequest = {
  chatId?: string | undefined;
  onlyIfDifferentOwner?: boolean | null | undefined;
};

/** @internal */
export type TextqlRpcPublicChatDuplicateChatRequest$Outbound = {
  chatId?: string | undefined;
  onlyIfDifferentOwner?: boolean | null | undefined;
};

/** @internal */
export const TextqlRpcPublicChatDuplicateChatRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatDuplicateChatRequest$Outbound,
    TextqlRpcPublicChatDuplicateChatRequest
  > = z.object({
    chatId: z.optional(z.string()),
    onlyIfDifferentOwner: z.optional(z.nullable(z.boolean())),
  });

export function textqlRpcPublicChatDuplicateChatRequestToJSON(
  textqlRpcPublicChatDuplicateChatRequest:
    TextqlRpcPublicChatDuplicateChatRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatDuplicateChatRequest$outboundSchema.parse(
      textqlRpcPublicChatDuplicateChatRequest,
    ),
  );
}
