/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesOntologyFile,
  TextqlRpcPublicPatchesOntologyFile$inboundSchema,
} from "./textql-rpc-public-patches-ontology-file.js";

export type TextqlRpcPublicPatchesUpsertOntologyFileResponse = {
  file?: TextqlRpcPublicPatchesOntologyFile | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesUpsertOntologyFileResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesUpsertOntologyFileResponse, unknown> = z
    .object({
      file: types.optional(TextqlRpcPublicPatchesOntologyFile$inboundSchema),
    });

export function textqlRpcPublicPatchesUpsertOntologyFileResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesUpsertOntologyFileResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesUpsertOntologyFileResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesUpsertOntologyFileResponse' from JSON`,
  );
}
