/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesListPatchObjectsRequest = {
  /**
   * path is the config file the finding is attributed to.
   */
  patchRef?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesListPatchObjectsRequest$Outbound = {
  patchRef?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesListPatchObjectsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesListPatchObjectsRequest$Outbound,
    TextqlRpcPublicPatchesListPatchObjectsRequest
  > = z.object({
    patchRef: z.optional(z.string()),
  });

export function textqlRpcPublicPatchesListPatchObjectsRequestToJSON(
  textqlRpcPublicPatchesListPatchObjectsRequest:
    TextqlRpcPublicPatchesListPatchObjectsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesListPatchObjectsRequest$outboundSchema.parse(
      textqlRpcPublicPatchesListPatchObjectsRequest,
    ),
  );
}
