/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicTableauTestTableauConnectionResponse = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicTableauTestTableauConnectionResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicTableauTestTableauConnectionResponse, unknown> =
    z.object({
      success: types.optional(types.boolean()),
      error: types.optional(types.string()),
    });

export function textqlRpcPublicTableauTestTableauConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicTableauTestTableauConnectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicTableauTestTableauConnectionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicTableauTestTableauConnectionResponse' from JSON`,
  );
}
