/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest = {
  id?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest$Outbound =
  {
    id?: string | undefined;
  };

/** @internal */
export const TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest$Outbound,
    TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest
  > = z.object({
    id: z.optional(z.string()),
  });

export function textqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequestToJSON(
  textqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest:
    TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest$outboundSchema
      .parse(textqlRpcPublicPatchesDeleteContextPatchAutoApproveRuleRequest),
  );
}
