/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPowerbiPowerBIReport,
  TextqlRpcPublicPowerbiPowerBIReport$inboundSchema,
} from "./textql-rpc-public-powerbi-power-bi-report.js";

export type TextqlRpcPublicPowerbiListPowerBIReportsResponse = {
  reports?: Array<TextqlRpcPublicPowerbiPowerBIReport> | undefined;
  error?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicPowerbiListPowerBIReportsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPowerbiListPowerBIReportsResponse, unknown> = z
    .object({
      reports: types.optional(
        z.array(TextqlRpcPublicPowerbiPowerBIReport$inboundSchema),
      ),
      error: z.optional(z.nullable(types.string())),
    });

export function textqlRpcPublicPowerbiListPowerBIReportsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPowerbiListPowerBIReportsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPowerbiListPowerBIReportsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPowerbiListPowerBIReportsResponse' from JSON`,
  );
}
