/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcIdentityMemberPreview,
  TextqlRpcIdentityMemberPreview$inboundSchema,
} from "./textql-rpc-identity-member-preview.js";

export type TextqlRpcPublicChatGetMembersWithChatsResponse = {
  /**
   * All creators of chats user can see
   */
  members?: Array<TextqlRpcIdentityMemberPreview> | undefined;
};

/** @internal */
export const TextqlRpcPublicChatGetMembersWithChatsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicChatGetMembersWithChatsResponse, unknown> = z
    .object({
      members: types.optional(
        z.array(TextqlRpcIdentityMemberPreview$inboundSchema),
      ),
    });

export function textqlRpcPublicChatGetMembersWithChatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicChatGetMembersWithChatsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatGetMembersWithChatsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicChatGetMembersWithChatsResponse' from JSON`,
  );
}
