/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicAgentAgent,
  TextqlRpcPublicAgentAgent$inboundSchema,
} from "./textql-rpc-public-agent-agent.js";

export type TextqlRpcPublicAgentDuplicateAgentResponse = {
  agent?: TextqlRpcPublicAgentAgent | undefined;
};

/** @internal */
export const TextqlRpcPublicAgentDuplicateAgentResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicAgentDuplicateAgentResponse, unknown> = z.object(
    {
      agent: types.optional(TextqlRpcPublicAgentAgent$inboundSchema),
    },
  );

export function textqlRpcPublicAgentDuplicateAgentResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicAgentDuplicateAgentResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicAgentDuplicateAgentResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicAgentDuplicateAgentResponse' from JSON`,
  );
}
