/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest = {
  mappingId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest$Outbound =
  {
    mappingId?: string | undefined;
  };

/** @internal */
export const TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest$Outbound,
    TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest
  > = z.object({
    mappingId: z.optional(z.string()),
  });

export function textqlRpcPublicRbacMigrateScimGroupMappingToGroupRequestToJSON(
  textqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest:
    TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest$outboundSchema
      .parse(textqlRpcPublicRbacMigrateScimGroupMappingToGroupRequest),
  );
}
