/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicTableauUnstarTableauItemResponse = {
  success?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicTableauUnstarTableauItemResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicTableauUnstarTableauItemResponse, unknown> = z
    .object({
      success: types.optional(types.boolean()),
    });

export function textqlRpcPublicTableauUnstarTableauItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicTableauUnstarTableauItemResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicTableauUnstarTableauItemResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicTableauUnstarTableauItemResponse' from JSON`,
  );
}
