/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request to list batch runs for a playbook
 */
export type TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest = {
  /**
   * UUID
   */
  playbookId?: string | undefined;
  /**
   * Max number of results (default: 50)
   */
  limit?: number | null | undefined;
  /**
   * Offset for pagination (default: 0)
   */
  offset?: number | null | undefined;
};

/** @internal */
export type TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest$Outbound = {
  playbookId?: string | undefined;
  limit?: number | null | undefined;
  offset?: number | null | undefined;
};

/** @internal */
export const TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest$Outbound,
    TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest
  > = z.object({
    playbookId: z.optional(z.string()),
    limit: z.optional(z.nullable(z.int())),
    offset: z.optional(z.nullable(z.int())),
  });

export function textqlRpcPublicPlaybookListPlaybookBatchRunsRequestToJSON(
  textqlRpcPublicPlaybookListPlaybookBatchRunsRequest:
    TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPlaybookListPlaybookBatchRunsRequest$outboundSchema.parse(
      textqlRpcPublicPlaybookListPlaybookBatchRunsRequest,
    ),
  );
}
