/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * FormCell is the v2 form editor cell. It only references a form_v5 row by id;
 *
 * @remarks
 *  the frontend loads the full form via FormService (no chat-cell scanning). The
 *  cached fields let the inline chat cell render without a round-trip.
 */
export type TextqlRpcPublicCellsOrgMemberRef = {
  /**
   * list | info | create | edit | view | update | test
   */
  email?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicCellsOrgMemberRef$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicCellsOrgMemberRef,
  unknown
> = z.object({
  email: types.optional(types.string()),
  name: types.optional(types.string()),
});

export function textqlRpcPublicCellsOrgMemberRefFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicCellsOrgMemberRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextqlRpcPublicCellsOrgMemberRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicCellsOrgMemberRef' from JSON`,
  );
}
