/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicChatChat,
  TextqlRpcPublicChatChat$inboundSchema,
} from "./textql-rpc-public-chat-chat.js";

export type TextqlRpcPublicChatGetChatsResponse = {
  chats?: Array<TextqlRpcPublicChatChat> | undefined;
  totalCount?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicChatGetChatsResponse$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicChatGetChatsResponse,
  unknown
> = z.object({
  chats: types.optional(z.array(TextqlRpcPublicChatChat$inboundSchema)),
  totalCount: types.optional(types.number()),
});

export function textqlRpcPublicChatGetChatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicChatGetChatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatGetChatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicChatGetChatsResponse' from JSON`,
  );
}
