/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicAppAppVersion,
  TextqlRpcPublicAppAppVersion$inboundSchema,
} from "./textql-rpc-public-app-app-version.js";

export type TextqlRpcPublicAppGetAppVersionResponse = {
  version?: TextqlRpcPublicAppAppVersion | undefined;
};

/** @internal */
export const TextqlRpcPublicAppGetAppVersionResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicAppGetAppVersionResponse, unknown> = z.object({
    version: types.optional(TextqlRpcPublicAppAppVersion$inboundSchema),
  });

export function textqlRpcPublicAppGetAppVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicAppGetAppVersionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicAppGetAppVersionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicAppGetAppVersionResponse' from JSON`,
  );
}
