/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicRbacAuditLogPermissionAction = {
  AuditLogActionUnspecified: "AUDIT_LOG_ACTION_UNSPECIFIED",
  AuditLogActionRead: "AUDIT_LOG_ACTION_READ",
} as const;
export type TextqlRpcPublicRbacAuditLogPermissionAction = OpenEnum<
  typeof TextqlRpcPublicRbacAuditLogPermissionAction
>;

/** @internal */
export const TextqlRpcPublicRbacAuditLogPermissionAction$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacAuditLogPermissionAction, unknown> =
    openEnums.inboundSchema(TextqlRpcPublicRbacAuditLogPermissionAction);
/** @internal */
export const TextqlRpcPublicRbacAuditLogPermissionAction$outboundSchema:
  z.ZodMiniType<string, TextqlRpcPublicRbacAuditLogPermissionAction> = openEnums
    .outboundSchema(TextqlRpcPublicRbacAuditLogPermissionAction);
