/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicTableauGenerateEmbedTokenResponse = {
  token?: string | undefined;
  embedUrl?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicTableauGenerateEmbedTokenResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicTableauGenerateEmbedTokenResponse, unknown> = z
    .object({
      token: types.optional(types.string()),
      embedUrl: types.optional(types.string()),
    });

export function textqlRpcPublicTableauGenerateEmbedTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicTableauGenerateEmbedTokenResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicTableauGenerateEmbedTokenResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicTableauGenerateEmbedTokenResponse' from JSON`,
  );
}
