/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacUpdateRoleRequest = {
  roleId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  /**
   * Wrapper message for `int32`.
   *
   * @remarks
   *
   *  The JSON representation for `Int32Value` is JSON number.
   *
   *  Not recommended for use in new APIs, but still useful for legacy APIs and
   *  has no plan to be removed.
   */
  defaultModelId?: number | undefined;
  allowedModelIds?: Array<number> | undefined;
  /**
   * Wrapper message for `bool`.
   *
   * @remarks
   *
   *  The JSON representation for `BoolValue` is JSON `true` and `false`.
   *
   *  Not recommended for use in new APIs, but still useful for legacy APIs and
   *  has no plan to be removed.
   */
  allowModelChoice?: boolean | undefined;
  /**
   * Set to true to clear allowed_model_ids back to "all models allowed".
   *
   * @remarks
   *  Proto3 cannot distinguish an empty repeated field from an absent one,
   *  so this explicit flag is required.
   */
  clearAllowedModelIds?: boolean | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacUpdateRoleRequest$Outbound = {
  roleId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  defaultModelId?: number | undefined;
  allowedModelIds?: Array<number> | undefined;
  allowModelChoice?: boolean | undefined;
  clearAllowedModelIds?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacUpdateRoleRequest$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicRbacUpdateRoleRequest$Outbound,
  TextqlRpcPublicRbacUpdateRoleRequest
> = z.object({
  roleId: z.optional(z.string()),
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  defaultModelId: z.optional(z.number()),
  allowedModelIds: z.optional(z.array(z.int())),
  allowModelChoice: z.optional(z.boolean()),
  clearAllowedModelIds: z.optional(z.boolean()),
});

export function textqlRpcPublicRbacUpdateRoleRequestToJSON(
  textqlRpcPublicRbacUpdateRoleRequest: TextqlRpcPublicRbacUpdateRoleRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacUpdateRoleRequest$outboundSchema.parse(
      textqlRpcPublicRbacUpdateRoleRequest,
    ),
  );
}
