/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicObserveGetObservabilityStatsRequest = {
  /**
   * time window: 7, 14, 30, 90
   */
  days?: number | undefined;
};

/** @internal */
export type TextqlRpcPublicObserveGetObservabilityStatsRequest$Outbound = {
  days?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicObserveGetObservabilityStatsRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicObserveGetObservabilityStatsRequest$Outbound,
    TextqlRpcPublicObserveGetObservabilityStatsRequest
  > = z.object({
    days: z.optional(z.int()),
  });

export function textqlRpcPublicObserveGetObservabilityStatsRequestToJSON(
  textqlRpcPublicObserveGetObservabilityStatsRequest:
    TextqlRpcPublicObserveGetObservabilityStatsRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicObserveGetObservabilityStatsRequest$outboundSchema.parse(
      textqlRpcPublicObserveGetObservabilityStatsRequest,
    ),
  );
}
