/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicConnectorGetTablePreviewRequest = {
  connectorId?: number | undefined;
  tableDatabase?: string | undefined;
  tableSchema?: string | undefined;
  tableName?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export type TextqlRpcPublicConnectorGetTablePreviewRequest$Outbound = {
  connectorId?: number | undefined;
  tableDatabase?: string | undefined;
  tableSchema?: string | undefined;
  tableName?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorGetTablePreviewRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorGetTablePreviewRequest$Outbound,
    TextqlRpcPublicConnectorGetTablePreviewRequest
  > = z.object({
    connectorId: z.optional(z.int()),
    tableDatabase: z.optional(z.string()),
    tableSchema: z.optional(z.string()),
    tableName: z.optional(z.string()),
    limit: z.optional(z.int()),
  });

export function textqlRpcPublicConnectorGetTablePreviewRequestToJSON(
  textqlRpcPublicConnectorGetTablePreviewRequest:
    TextqlRpcPublicConnectorGetTablePreviewRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorGetTablePreviewRequest$outboundSchema.parse(
      textqlRpcPublicConnectorGetTablePreviewRequest,
    ),
  );
}
