/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Starred items
 */
export const TextqlRpcPublicTableauTableauItemType = {
  ItemTypeUnknown: "ITEM_TYPE_UNKNOWN",
  ItemTypeProject: "ITEM_TYPE_PROJECT",
  ItemTypeWorkbook: "ITEM_TYPE_WORKBOOK",
  ItemTypeView: "ITEM_TYPE_VIEW",
  ItemTypeDatasource: "ITEM_TYPE_DATASOURCE",
} as const;
/**
 * Starred items
 */
export type TextqlRpcPublicTableauTableauItemType = OpenEnum<
  typeof TextqlRpcPublicTableauTableauItemType
>;

/** @internal */
export const TextqlRpcPublicTableauTableauItemType$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicTableauTableauItemType,
  unknown
> = openEnums.inboundSchema(TextqlRpcPublicTableauTableauItemType);
/** @internal */
export const TextqlRpcPublicTableauTableauItemType$outboundSchema:
  z.ZodMiniType<string, TextqlRpcPublicTableauTableauItemType> = openEnums
    .outboundSchema(TextqlRpcPublicTableauTableauItemType);
