/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicAppCapabilityParam,
  TextqlRpcPublicAppCapabilityParam$inboundSchema,
  TextqlRpcPublicAppCapabilityParam$Outbound,
  TextqlRpcPublicAppCapabilityParam$outboundSchema,
} from "./textql-rpc-public-app-capability-param.js";

export type TextqlRpcPublicAppCapability = {
  type?: string | undefined;
  /**
   * string | number | boolean | object | array
   */
  name?: string | null | undefined;
  connectorId?: number | null | undefined;
  statement?: string | null | undefined;
  scope?: string | null | undefined;
  subject?: string | null | undefined;
  body?: string | null | undefined;
  parameters?: Array<TextqlRpcPublicAppCapabilityParam> | undefined;
};

/** @internal */
export const TextqlRpcPublicAppCapability$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicAppCapability,
  unknown
> = z.object({
  type: types.optional(types.string()),
  name: z.optional(z.nullable(types.string())),
  connectorId: z.optional(z.nullable(types.number())),
  statement: z.optional(z.nullable(types.string())),
  scope: z.optional(z.nullable(types.string())),
  subject: z.optional(z.nullable(types.string())),
  body: z.optional(z.nullable(types.string())),
  parameters: types.optional(
    z.array(TextqlRpcPublicAppCapabilityParam$inboundSchema),
  ),
});
/** @internal */
export type TextqlRpcPublicAppCapability$Outbound = {
  type?: string | undefined;
  name?: string | null | undefined;
  connectorId?: number | null | undefined;
  statement?: string | null | undefined;
  scope?: string | null | undefined;
  subject?: string | null | undefined;
  body?: string | null | undefined;
  parameters?: Array<TextqlRpcPublicAppCapabilityParam$Outbound> | undefined;
};

/** @internal */
export const TextqlRpcPublicAppCapability$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicAppCapability$Outbound,
  TextqlRpcPublicAppCapability
> = z.object({
  type: z.optional(z.string()),
  name: z.optional(z.nullable(z.string())),
  connectorId: z.optional(z.nullable(z.int())),
  statement: z.optional(z.nullable(z.string())),
  scope: z.optional(z.nullable(z.string())),
  subject: z.optional(z.nullable(z.string())),
  body: z.optional(z.nullable(z.string())),
  parameters: z.optional(
    z.array(TextqlRpcPublicAppCapabilityParam$outboundSchema),
  ),
});

export function textqlRpcPublicAppCapabilityToJSON(
  textqlRpcPublicAppCapability: TextqlRpcPublicAppCapability,
): string {
  return JSON.stringify(
    TextqlRpcPublicAppCapability$outboundSchema.parse(
      textqlRpcPublicAppCapability,
    ),
  );
}
export function textqlRpcPublicAppCapabilityFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicAppCapability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextqlRpcPublicAppCapability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicAppCapability' from JSON`,
  );
}
