/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesMigrateOntologyToLibraryResult,
  TextqlRpcPublicPatchesMigrateOntologyToLibraryResult$inboundSchema,
} from "./textql-rpc-public-patches-migrate-ontology-to-library-result.js";

export type TextqlRpcPublicPatchesMigrateOntologyToLibraryResponse = {
  results?:
    | Array<TextqlRpcPublicPatchesMigrateOntologyToLibraryResult>
    | undefined;
  totalCreated?: number | undefined;
  totalSkipped?: number | undefined;
  dryRun?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesMigrateOntologyToLibraryResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesMigrateOntologyToLibraryResponse,
    unknown
  > = z.object({
    results: types.optional(
      z.array(
        TextqlRpcPublicPatchesMigrateOntologyToLibraryResult$inboundSchema,
      ),
    ),
    totalCreated: types.optional(types.number()),
    totalSkipped: types.optional(types.number()),
    dryRun: types.optional(types.boolean()),
  });

export function textqlRpcPublicPatchesMigrateOntologyToLibraryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesMigrateOntologyToLibraryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesMigrateOntologyToLibraryResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPatchesMigrateOntologyToLibraryResponse' from JSON`,
  );
}
