/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacRemoveRoleFromMemberRequest = {
  memberId?: string | undefined;
  roleId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacRemoveRoleFromMemberRequest$Outbound = {
  memberId?: string | undefined;
  roleId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacRemoveRoleFromMemberRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicRbacRemoveRoleFromMemberRequest$Outbound,
    TextqlRpcPublicRbacRemoveRoleFromMemberRequest
  > = z.object({
    memberId: z.optional(z.string()),
    roleId: z.optional(z.string()),
  });

export function textqlRpcPublicRbacRemoveRoleFromMemberRequestToJSON(
  textqlRpcPublicRbacRemoveRoleFromMemberRequest:
    TextqlRpcPublicRbacRemoveRoleFromMemberRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacRemoveRoleFromMemberRequest$outboundSchema.parse(
      textqlRpcPublicRbacRemoveRoleFromMemberRequest,
    ),
  );
}
