/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest = {
  name?: string | undefined;
  agentId?: string | undefined;
  prompt?: string | undefined;
  appDb?: string | undefined;
  /**
   * ask id of an earlier base-agent ask to follow up in; empty starts a new thread
   */
  continueAskId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest$Outbound = {
  name?: string | undefined;
  agentId?: string | undefined;
  prompt?: string | undefined;
  appDb?: string | undefined;
  continueAskId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest$Outbound,
    TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest
  > = z.object({
    name: z.optional(z.string()),
    agentId: z.optional(z.string()),
    prompt: z.optional(z.string()),
    appDb: z.optional(z.string()),
    continueAskId: z.optional(z.string()),
  });

export function textqlRpcPublicSandboxCapabilitySandboxStartAskRequestToJSON(
  textqlRpcPublicSandboxCapabilitySandboxStartAskRequest:
    TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicSandboxCapabilitySandboxStartAskRequest$outboundSchema.parse(
      textqlRpcPublicSandboxCapabilitySandboxStartAskRequest,
    ),
  );
}
