/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicChatGetChatExecutionTimingRequest = {
  chatId: string;
};

/** @internal */
export type TextqlRpcPublicChatGetChatExecutionTimingRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const TextqlRpcPublicChatGetChatExecutionTimingRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatGetChatExecutionTimingRequest$Outbound,
    TextqlRpcPublicChatGetChatExecutionTimingRequest
  > = z.object({
    chatId: z.string(),
  });

export function textqlRpcPublicChatGetChatExecutionTimingRequestToJSON(
  textqlRpcPublicChatGetChatExecutionTimingRequest:
    TextqlRpcPublicChatGetChatExecutionTimingRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatGetChatExecutionTimingRequest$outboundSchema.parse(
      textqlRpcPublicChatGetChatExecutionTimingRequest,
    ),
  );
}
