/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicChatHealthStatus,
  TextqlRpcPublicChatHealthStatus$inboundSchema,
} from "./textql-rpc-public-chat-health-status.js";

export type TextqlRpcPublicChatCheckHealthResponse = {
  llmStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  webStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  ontologyStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  valkeyStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  tableauStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  sandboxStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  llmExecutionStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  sandboxExecutionStatus?: TextqlRpcPublicChatHealthStatus | undefined;
  consoleStatus?: TextqlRpcPublicChatHealthStatus | undefined;
};

/** @internal */
export const TextqlRpcPublicChatCheckHealthResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicChatCheckHealthResponse, unknown> = z.object({
    llmStatus: types.optional(TextqlRpcPublicChatHealthStatus$inboundSchema),
    webStatus: types.optional(TextqlRpcPublicChatHealthStatus$inboundSchema),
    ontologyStatus: types.optional(
      TextqlRpcPublicChatHealthStatus$inboundSchema,
    ),
    valkeyStatus: types.optional(TextqlRpcPublicChatHealthStatus$inboundSchema),
    tableauStatus: types.optional(
      TextqlRpcPublicChatHealthStatus$inboundSchema,
    ),
    sandboxStatus: types.optional(
      TextqlRpcPublicChatHealthStatus$inboundSchema,
    ),
    llmExecutionStatus: types.optional(
      TextqlRpcPublicChatHealthStatus$inboundSchema,
    ),
    sandboxExecutionStatus: types.optional(
      TextqlRpcPublicChatHealthStatus$inboundSchema,
    ),
    consoleStatus: types.optional(
      TextqlRpcPublicChatHealthStatus$inboundSchema,
    ),
  });

export function textqlRpcPublicChatCheckHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicChatCheckHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatCheckHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicChatCheckHealthResponse' from JSON`,
  );
}
