/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TextqlRpcPublicPatchesContextPatchAutoApproveRuleInput,
  TextqlRpcPublicPatchesContextPatchAutoApproveRuleInput$Outbound,
  TextqlRpcPublicPatchesContextPatchAutoApproveRuleInput$outboundSchema,
} from "./textql-rpc-public-patches-context-patch-auto-approve-rule-input.js";

export type TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest = {
  id?: string | undefined;
  rule?: TextqlRpcPublicPatchesContextPatchAutoApproveRuleInput | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest$Outbound =
  {
    id?: string | undefined;
    rule?:
      | TextqlRpcPublicPatchesContextPatchAutoApproveRuleInput$Outbound
      | undefined;
  };

/** @internal */
export const TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest$Outbound,
    TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest
  > = z.object({
    id: z.optional(z.string()),
    rule: z.optional(
      TextqlRpcPublicPatchesContextPatchAutoApproveRuleInput$outboundSchema,
    ),
  });

export function textqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequestToJSON(
  textqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest:
    TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest$outboundSchema
      .parse(textqlRpcPublicPatchesUpdateContextPatchAutoApproveRuleRequest),
  );
}
