/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicTableauTableauStarredItem,
  TextqlRpcPublicTableauTableauStarredItem$inboundSchema,
} from "./textql-rpc-public-tableau-tableau-starred-item.js";

export type TextqlRpcPublicTableauGetStarredTableauItemsResponse = {
  items?: Array<TextqlRpcPublicTableauTableauStarredItem> | undefined;
};

/** @internal */
export const TextqlRpcPublicTableauGetStarredTableauItemsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicTableauGetStarredTableauItemsResponse, unknown> =
    z.object({
      items: types.optional(
        z.array(TextqlRpcPublicTableauTableauStarredItem$inboundSchema),
      ),
    });

export function textqlRpcPublicTableauGetStarredTableauItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicTableauGetStarredTableauItemsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicTableauGetStarredTableauItemsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicTableauGetStarredTableauItemsResponse' from JSON`,
  );
}
