/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicRbacShareObjectResponse = {
  success?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacShareObjectResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacShareObjectResponse, unknown> = z.object({
    success: types.optional(types.boolean()),
  });

export function textqlRpcPublicRbacShareObjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicRbacShareObjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicRbacShareObjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicRbacShareObjectResponse' from JSON`,
  );
}
