/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicChatGetLlmUsageRequest = {
  chatId?: string | undefined;
  includeCosts?: boolean | undefined;
};

/** @internal */
export type TextqlRpcPublicChatGetLlmUsageRequest$Outbound = {
  chatId?: string | undefined;
  includeCosts?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicChatGetLlmUsageRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicChatGetLlmUsageRequest$Outbound,
    TextqlRpcPublicChatGetLlmUsageRequest
  > = z.object({
    chatId: z.optional(z.string()),
    includeCosts: z.optional(z.boolean()),
  });

export function textqlRpcPublicChatGetLlmUsageRequestToJSON(
  textqlRpcPublicChatGetLlmUsageRequest: TextqlRpcPublicChatGetLlmUsageRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatGetLlmUsageRequest$outboundSchema.parse(
      textqlRpcPublicChatGetLlmUsageRequest,
    ),
  );
}
