/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicChatDeleteChatRequest = {
  chatId: string;
};

/** @internal */
export type TextqlRpcPublicChatDeleteChatRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const TextqlRpcPublicChatDeleteChatRequest$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicChatDeleteChatRequest$Outbound,
  TextqlRpcPublicChatDeleteChatRequest
> = z.object({
  chatId: z.string(),
});

export function textqlRpcPublicChatDeleteChatRequestToJSON(
  textqlRpcPublicChatDeleteChatRequest: TextqlRpcPublicChatDeleteChatRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicChatDeleteChatRequest$outboundSchema.parse(
      textqlRpcPublicChatDeleteChatRequest,
    ),
  );
}
