/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicChatWatchOpenedEvent = {};

/** @internal */
export const TextqlRpcPublicChatWatchOpenedEvent$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicChatWatchOpenedEvent,
  unknown
> = z.object({});

export function textqlRpcPublicChatWatchOpenedEventFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicChatWatchOpenedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicChatWatchOpenedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicChatWatchOpenedEvent' from JSON`,
  );
}
