/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicObserveCustomTopic,
  TextqlRpcPublicObserveCustomTopic$inboundSchema,
} from "./textql-rpc-public-observe-custom-topic.js";

export type TextqlRpcPublicObserveListCustomTopicsResponse = {
  topics?: Array<TextqlRpcPublicObserveCustomTopic> | undefined;
};

/** @internal */
export const TextqlRpcPublicObserveListCustomTopicsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicObserveListCustomTopicsResponse, unknown> = z
    .object({
      topics: types.optional(
        z.array(TextqlRpcPublicObserveCustomTopic$inboundSchema),
      ),
    });

export function textqlRpcPublicObserveListCustomTopicsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicObserveListCustomTopicsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicObserveListCustomTopicsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicObserveListCustomTopicsResponse' from JSON`,
  );
}
