/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicRbacPermission,
  TextqlRpcPublicRbacPermission$inboundSchema,
} from "./textql-rpc-public-rbac-permission.js";

export type TextqlRpcPublicRbacGetRolePermissionsResponse = {
  permissions?: Array<TextqlRpcPublicRbacPermission> | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacGetRolePermissionsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacGetRolePermissionsResponse, unknown> = z
    .object({
      permissions: types.optional(
        z.array(TextqlRpcPublicRbacPermission$inboundSchema),
      ),
    });

export function textqlRpcPublicRbacGetRolePermissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicRbacGetRolePermissionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicRbacGetRolePermissionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicRbacGetRolePermissionsResponse' from JSON`,
  );
}
