/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicSecretSecret,
  TextqlRpcPublicSecretSecret$inboundSchema,
} from "./textql-rpc-public-secret-secret.js";

export type TextqlRpcPublicSecretListSecretsResponse = {
  secrets?: Array<TextqlRpcPublicSecretSecret> | undefined;
};

/** @internal */
export const TextqlRpcPublicSecretListSecretsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicSecretListSecretsResponse, unknown> = z.object({
    secrets: types.optional(z.array(TextqlRpcPublicSecretSecret$inboundSchema)),
  });

export function textqlRpcPublicSecretListSecretsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicSecretListSecretsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicSecretListSecretsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicSecretListSecretsResponse' from JSON`,
  );
}
