/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesGithubInstallationRepo,
  TextqlRpcPublicPatchesGithubInstallationRepo$inboundSchema,
} from "./textql-rpc-public-patches-github-installation-repo.js";

export type TextqlRpcPublicPatchesGithubInstallation = {
  id?: string | undefined;
  account?: string | undefined;
  repos?: Array<TextqlRpcPublicPatchesGithubInstallationRepo> | undefined;
  reposError?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGithubInstallation$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesGithubInstallation, unknown> = z.object({
    id: types.optional(types.string()),
    account: types.optional(types.string()),
    repos: types.optional(
      z.array(TextqlRpcPublicPatchesGithubInstallationRepo$inboundSchema),
    ),
    reposError: types.optional(types.string()),
  });

export function textqlRpcPublicPatchesGithubInstallationFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesGithubInstallation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesGithubInstallation$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesGithubInstallation' from JSON`,
  );
}
