/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicSettingsCheckMemberStatusResponse = {
  isSuspended?: boolean | undefined;
  consoleAccess?: boolean | undefined;
  isSuspendedManual?: boolean | undefined;
  isSuspendedOverage?: boolean | undefined;
  isSuspendedUsage?: boolean | undefined;
  isSuspendedMemberUsage?: boolean | undefined;
  suspensionMessage?: string | undefined;
  suspendedCostCenters?: Array<string> | undefined;
  isSuspendedOrgLimit?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicSettingsCheckMemberStatusResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicSettingsCheckMemberStatusResponse, unknown> = z
    .object({
      isSuspended: types.optional(types.boolean()),
      consoleAccess: types.optional(types.boolean()),
      isSuspendedManual: types.optional(types.boolean()),
      isSuspendedOverage: types.optional(types.boolean()),
      isSuspendedUsage: types.optional(types.boolean()),
      isSuspendedMemberUsage: types.optional(types.boolean()),
      suspensionMessage: types.optional(types.string()),
      suspendedCostCenters: types.optional(z.array(types.string())),
      isSuspendedOrgLimit: types.optional(types.boolean()),
    });

export function textqlRpcPublicSettingsCheckMemberStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicSettingsCheckMemberStatusResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicSettingsCheckMemberStatusResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicSettingsCheckMemberStatusResponse' from JSON`,
  );
}
