/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Member role management messages
 */
export type TextqlRpcPublicRbacAssignRoleToMemberRequest = {
  memberId?: string | undefined;
  roleId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicRbacAssignRoleToMemberRequest$Outbound = {
  memberId?: string | undefined;
  roleId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacAssignRoleToMemberRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicRbacAssignRoleToMemberRequest$Outbound,
    TextqlRpcPublicRbacAssignRoleToMemberRequest
  > = z.object({
    memberId: z.optional(z.string()),
    roleId: z.optional(z.string()),
  });

export function textqlRpcPublicRbacAssignRoleToMemberRequestToJSON(
  textqlRpcPublicRbacAssignRoleToMemberRequest:
    TextqlRpcPublicRbacAssignRoleToMemberRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacAssignRoleToMemberRequest$outboundSchema.parse(
      textqlRpcPublicRbacAssignRoleToMemberRequest,
    ),
  );
}
