/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPatchesMigratedLegacyContextPrompt = {
  legacyContextPromptId?: string | undefined;
  name?: string | undefined;
  folderPath?: string | undefined;
  filePath?: string | undefined;
  created?: boolean | undefined;
  skipped?: boolean | undefined;
  skipReason?: string | null | undefined;
  isPublic?: boolean | undefined;
  autoAttach?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesMigratedLegacyContextPrompt$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesMigratedLegacyContextPrompt, unknown> = z
    .object({
      legacyContextPromptId: types.optional(types.string()),
      name: types.optional(types.string()),
      folderPath: types.optional(types.string()),
      filePath: types.optional(types.string()),
      created: types.optional(types.boolean()),
      skipped: types.optional(types.boolean()),
      skipReason: z.optional(z.nullable(types.string())),
      isPublic: types.optional(types.boolean()),
      autoAttach: types.optional(types.boolean()),
    });

export function textqlRpcPublicPatchesMigratedLegacyContextPromptFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesMigratedLegacyContextPrompt,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesMigratedLegacyContextPrompt$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesMigratedLegacyContextPrompt' from JSON`,
  );
}
