/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicAppAppViewerInfo,
  TextqlRpcPublicAppAppViewerInfo$inboundSchema,
} from "./textql-rpc-public-app-app-viewer-info.js";

/**
 * View analytics
 */
export type TextqlRpcPublicAppGetAppViewStatsResponse = {
  totalViews?: number | undefined;
  uniqueViewers?: number | undefined;
  recentViewers?: Array<TextqlRpcPublicAppAppViewerInfo> | undefined;
};

/** @internal */
export const TextqlRpcPublicAppGetAppViewStatsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicAppGetAppViewStatsResponse, unknown> = z.object({
    totalViews: types.optional(types.number()),
    uniqueViewers: types.optional(types.number()),
    recentViewers: types.optional(
      z.array(TextqlRpcPublicAppAppViewerInfo$inboundSchema),
    ),
  });

export function textqlRpcPublicAppGetAppViewStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicAppGetAppViewStatsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicAppGetAppViewStatsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicAppGetAppViewStatsResponse' from JSON`,
  );
}
