/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicPatchesLibrarySyncRunStatus = {
  LibrarySyncRunStatusUnspecified: "LIBRARY_SYNC_RUN_STATUS_UNSPECIFIED",
  LibrarySyncRunStatusInProgress: "LIBRARY_SYNC_RUN_STATUS_IN_PROGRESS",
  LibrarySyncRunStatusSucceeded: "LIBRARY_SYNC_RUN_STATUS_SUCCEEDED",
  LibrarySyncRunStatusFailed: "LIBRARY_SYNC_RUN_STATUS_FAILED",
  LibrarySyncRunStatusConflicts: "LIBRARY_SYNC_RUN_STATUS_CONFLICTS",
} as const;
export type TextqlRpcPublicPatchesLibrarySyncRunStatus = OpenEnum<
  typeof TextqlRpcPublicPatchesLibrarySyncRunStatus
>;

/** @internal */
export const TextqlRpcPublicPatchesLibrarySyncRunStatus$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesLibrarySyncRunStatus, unknown> = openEnums
    .inboundSchema(TextqlRpcPublicPatchesLibrarySyncRunStatus);
