/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicConnectorPrimaryKeyMetadata = {
  columns?: Array<string> | undefined;
  descriptions?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorPrimaryKeyMetadata$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicConnectorPrimaryKeyMetadata, unknown> = z.object(
    {
      columns: types.optional(z.array(types.string())),
      descriptions: types.optional(z.array(types.string())),
    },
  );

export function textqlRpcPublicConnectorPrimaryKeyMetadataFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicConnectorPrimaryKeyMetadata,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorPrimaryKeyMetadata$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicConnectorPrimaryKeyMetadata' from JSON`,
  );
}
