/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest = {
  path?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest$Outbound = {
  path?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest$Outbound,
    TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest
  > = z.object({
    path: z.optional(z.string()),
  });

export function textqlRpcPublicPatchesRemoveLibrarySubmoduleRequestToJSON(
  textqlRpcPublicPatchesRemoveLibrarySubmoduleRequest:
    TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicPatchesRemoveLibrarySubmoduleRequest$outboundSchema.parse(
      textqlRpcPublicPatchesRemoveLibrarySubmoduleRequest,
    ),
  );
}
