/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesLibraryRemote,
  TextqlRpcPublicPatchesLibraryRemote$inboundSchema,
} from "./textql-rpc-public-patches-library-remote.js";

export type TextqlRpcPublicPatchesConfigureLibraryRemoteResponse = {
  remote?: TextqlRpcPublicPatchesLibraryRemote | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesConfigureLibraryRemoteResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesConfigureLibraryRemoteResponse, unknown> =
    z.object({
      remote: types.optional(TextqlRpcPublicPatchesLibraryRemote$inboundSchema),
    });

export function textqlRpcPublicPatchesConfigureLibraryRemoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesConfigureLibraryRemoteResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesConfigureLibraryRemoteResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesConfigureLibraryRemoteResponse' from JSON`,
  );
}
