/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesGithubInstallation,
  TextqlRpcPublicPatchesGithubInstallation$inboundSchema,
} from "./textql-rpc-public-patches-github-installation.js";

export type TextqlRpcPublicPatchesExchangeOntologyGithubCodeResponse = {
  success?: boolean | undefined;
  installations?: Array<TextqlRpcPublicPatchesGithubInstallation> | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesExchangeOntologyGithubCodeResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesExchangeOntologyGithubCodeResponse,
    unknown
  > = z.object({
    success: types.optional(types.boolean()),
    installations: types.optional(
      z.array(TextqlRpcPublicPatchesGithubInstallation$inboundSchema),
    ),
  });

export function textqlRpcPublicPatchesExchangeOntologyGithubCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesExchangeOntologyGithubCodeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesExchangeOntologyGithubCodeResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicPatchesExchangeOntologyGithubCodeResponse' from JSON`,
  );
}
