/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicSandboxAdminSandboxDataframe,
  TextqlRpcPublicSandboxAdminSandboxDataframe$inboundSchema,
} from "./textql-rpc-public-sandbox-admin-sandbox-dataframe.js";
import {
  TextqlRpcPublicSandboxAdminSandboxSummary,
  TextqlRpcPublicSandboxAdminSandboxSummary$inboundSchema,
} from "./textql-rpc-public-sandbox-admin-sandbox-summary.js";

export type TextqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytes =
  | number
  | string;

export type TextqlRpcPublicSandboxAdminGetSandboxResponse = {
  sandbox?: TextqlRpcPublicSandboxAdminSandboxSummary | undefined;
  liveAvailable?: boolean | undefined;
  memoryUsageBytes?: number | string | undefined;
  dataframes?: Array<TextqlRpcPublicSandboxAdminSandboxDataframe> | undefined;
};

/** @internal */
export const TextqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytes$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytes,
    unknown
  > = smartUnion([types.number(), types.string()]);

export function textqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytesFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytes,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytes$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicSandboxAdminGetSandboxResponseMemoryUsageBytes' from JSON`,
  );
}

/** @internal */
export const TextqlRpcPublicSandboxAdminGetSandboxResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicSandboxAdminGetSandboxResponse, unknown> = z
    .object({
      sandbox: types.optional(
        TextqlRpcPublicSandboxAdminSandboxSummary$inboundSchema,
      ),
      liveAvailable: types.optional(types.boolean()),
      memoryUsageBytes: types.optional(
        smartUnion([types.number(), types.string()]),
      ),
      dataframes: types.optional(
        z.array(TextqlRpcPublicSandboxAdminSandboxDataframe$inboundSchema),
      ),
    });

export function textqlRpcPublicSandboxAdminGetSandboxResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicSandboxAdminGetSandboxResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicSandboxAdminGetSandboxResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicSandboxAdminGetSandboxResponse' from JSON`,
  );
}
