/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPatchesPreviewOntologyPullFolderRow = {
  folderPath?: string | undefined;
  fileCount?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesPreviewOntologyPullFolderRow$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesPreviewOntologyPullFolderRow, unknown> = z
    .object({
      folderPath: types.optional(types.string()),
      fileCount: types.optional(types.number()),
    });

export function textqlRpcPublicPatchesPreviewOntologyPullFolderRowFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesPreviewOntologyPullFolderRow,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesPreviewOntologyPullFolderRow$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesPreviewOntologyPullFolderRow' from JSON`,
  );
}
