/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicAppRefreshAppRequest = {
  appId?: string | undefined;
};

/** @internal */
export type TextqlRpcPublicAppRefreshAppRequest$Outbound = {
  appId?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicAppRefreshAppRequest$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicAppRefreshAppRequest$Outbound,
  TextqlRpcPublicAppRefreshAppRequest
> = z.object({
  appId: z.optional(z.string()),
});

export function textqlRpcPublicAppRefreshAppRequestToJSON(
  textqlRpcPublicAppRefreshAppRequest: TextqlRpcPublicAppRefreshAppRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicAppRefreshAppRequest$outboundSchema.parse(
      textqlRpcPublicAppRefreshAppRequest,
    ),
  );
}
