/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicDataframeInt64ValuesValue = number | string;

export type TextqlRpcPublicDataframeInt64Values = {
  values?: Array<number | string> | undefined;
};

/** @internal */
export const TextqlRpcPublicDataframeInt64ValuesValue$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicDataframeInt64ValuesValue, unknown> = smartUnion(
    [types.number(), types.string()],
  );

export function textqlRpcPublicDataframeInt64ValuesValueFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicDataframeInt64ValuesValue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicDataframeInt64ValuesValue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicDataframeInt64ValuesValue' from JSON`,
  );
}

/** @internal */
export const TextqlRpcPublicDataframeInt64Values$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicDataframeInt64Values,
  unknown
> = z.object({
  values: types.optional(z.array(smartUnion([types.number(), types.string()]))),
});

export function textqlRpcPublicDataframeInt64ValuesFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicDataframeInt64Values, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicDataframeInt64Values$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicDataframeInt64Values' from JSON`,
  );
}
