/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicRbacExportRolePermissionsResponse = {
  fileName?: string | undefined;
  contentType?: string | undefined;
  data?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacExportRolePermissionsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacExportRolePermissionsResponse, unknown> = z
    .object({
      fileName: types.optional(types.string()),
      contentType: types.optional(types.string()),
      data: types.optional(types.string()),
    });

export function textqlRpcPublicRbacExportRolePermissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicRbacExportRolePermissionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicRbacExportRolePermissionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicRbacExportRolePermissionsResponse' from JSON`,
  );
}
