/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPlaybookPlaybook,
  TextqlRpcPublicPlaybookPlaybook$inboundSchema,
} from "./textql-rpc-public-playbook-playbook.js";

export type TextqlRpcPublicPlaybookCreatePlaybookResponse = {
  playbook?: TextqlRpcPublicPlaybookPlaybook | undefined;
};

/** @internal */
export const TextqlRpcPublicPlaybookCreatePlaybookResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPlaybookCreatePlaybookResponse, unknown> = z
    .object({
      playbook: types.optional(TextqlRpcPublicPlaybookPlaybook$inboundSchema),
    });

export function textqlRpcPublicPlaybookCreatePlaybookResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPlaybookCreatePlaybookResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPlaybookCreatePlaybookResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPlaybookCreatePlaybookResponse' from JSON`,
  );
}
