/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicCellsTeamsChannelRef,
  TextqlRpcPublicCellsTeamsChannelRef$inboundSchema,
} from "./textql-rpc-public-cells-teams-channel-ref.js";

export type TextqlRpcPublicTeamsTeamsListChannelsResponse = {
  channels?: Array<TextqlRpcPublicCellsTeamsChannelRef> | undefined;
};

/** @internal */
export const TextqlRpcPublicTeamsTeamsListChannelsResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicTeamsTeamsListChannelsResponse, unknown> = z
    .object({
      channels: types.optional(
        z.array(TextqlRpcPublicCellsTeamsChannelRef$inboundSchema),
      ),
    });

export function textqlRpcPublicTeamsTeamsListChannelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicTeamsTeamsListChannelsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicTeamsTeamsListChannelsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicTeamsTeamsListChannelsResponse' from JSON`,
  );
}
