/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicAgentAgentRunDeliveryChannel,
  TextqlRpcPublicAgentAgentRunDeliveryChannel$inboundSchema,
} from "./textql-rpc-public-agent-agent-run-delivery-channel.js";

export type TextqlRpcPublicAgentAgentRunDelivery = {
  slackChannelId?: string | null | undefined;
  teamsChannelId?: string | null | undefined;
  slackDmUserIds?: Array<string> | undefined;
  teamsDmUserAadIds?: Array<string> | undefined;
  emailRecipientMemberIds?: Array<string> | undefined;
  feedChannelIds?: Array<string> | undefined;
  channels?: Array<TextqlRpcPublicAgentAgentRunDeliveryChannel> | undefined;
};

/** @internal */
export const TextqlRpcPublicAgentAgentRunDelivery$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicAgentAgentRunDelivery,
  unknown
> = z.object({
  slackChannelId: z.optional(z.nullable(types.string())),
  teamsChannelId: z.optional(z.nullable(types.string())),
  slackDmUserIds: types.optional(z.array(types.string())),
  teamsDmUserAadIds: types.optional(z.array(types.string())),
  emailRecipientMemberIds: types.optional(z.array(types.string())),
  feedChannelIds: types.optional(z.array(types.string())),
  channels: types.optional(
    z.array(TextqlRpcPublicAgentAgentRunDeliveryChannel$inboundSchema),
  ),
});

export function textqlRpcPublicAgentAgentRunDeliveryFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicAgentAgentRunDelivery, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicAgentAgentRunDelivery$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicAgentAgentRunDelivery' from JSON`,
  );
}
