/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicObserveEngagementTierCount,
  TextqlRpcPublicObserveEngagementTierCount$inboundSchema,
} from "./textql-rpc-public-observe-engagement-tier-count.js";

export type TextqlRpcPublicObserveGetEngagementSpectrumResponse = {
  tiers?: Array<TextqlRpcPublicObserveEngagementTierCount> | undefined;
  totalPeople?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicObserveGetEngagementSpectrumResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicObserveGetEngagementSpectrumResponse, unknown> =
    z.object({
      tiers: types.optional(
        z.array(TextqlRpcPublicObserveEngagementTierCount$inboundSchema),
      ),
      totalPeople: types.optional(types.number()),
    });

export function textqlRpcPublicObserveGetEngagementSpectrumResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicObserveGetEngagementSpectrumResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicObserveGetEngagementSpectrumResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicObserveGetEngagementSpectrumResponse' from JSON`,
  );
}
