/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicCellsFeedExplorerCell = {
  /**
   * "get_feed", "get_post", "get_comments"
   */
  operation?: string | undefined;
  postId?: string | null | undefined;
  filter?: string | null | undefined;
  limit?: number | null | undefined;
  /**
   * JSON-serialized result
   */
  result?: string | undefined;
  /**
   * when set, get results for specific feed channel
   */
  channelId?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicCellsFeedExplorerCell$inboundSchema: z.ZodMiniType<
  TextqlRpcPublicCellsFeedExplorerCell,
  unknown
> = z.object({
  operation: types.optional(types.string()),
  postId: z.optional(z.nullable(types.string())),
  filter: z.optional(z.nullable(types.string())),
  limit: z.optional(z.nullable(types.number())),
  result: types.optional(types.string()),
  channelId: z.optional(z.nullable(types.string())),
});

export function textqlRpcPublicCellsFeedExplorerCellFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicCellsFeedExplorerCell, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicCellsFeedExplorerCell$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicCellsFeedExplorerCell' from JSON`,
  );
}
