/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicConnectorListQueryTemplatesRequest = {
  connectorId?: number | undefined;
  /**
   * Display name (e.g., "Explore Data")
   */
  limit?: number | undefined;
  /**
   * Query text to send (plain text, no formatting)
   */
  offset?: number | undefined;
  /**
   * True if requires multiple connectors
   */
  days?: number | undefined;
};

/** @internal */
export type TextqlRpcPublicConnectorListQueryTemplatesRequest$Outbound = {
  connectorId?: number | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  days?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorListQueryTemplatesRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorListQueryTemplatesRequest$Outbound,
    TextqlRpcPublicConnectorListQueryTemplatesRequest
  > = z.object({
    connectorId: z.optional(z.int()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    days: z.optional(z.int()),
  });

export function textqlRpcPublicConnectorListQueryTemplatesRequestToJSON(
  textqlRpcPublicConnectorListQueryTemplatesRequest:
    TextqlRpcPublicConnectorListQueryTemplatesRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorListQueryTemplatesRequest$outboundSchema.parse(
      textqlRpcPublicConnectorListQueryTemplatesRequest,
    ),
  );
}
