/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicRbacAddGroupMemberResponse = {
  success?: boolean | undefined;
};

/** @internal */
export const TextqlRpcPublicRbacAddGroupMemberResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacAddGroupMemberResponse, unknown> = z.object({
    success: types.optional(types.boolean()),
  });

export function textqlRpcPublicRbacAddGroupMemberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicRbacAddGroupMemberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicRbacAddGroupMemberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicRbacAddGroupMemberResponse' from JSON`,
  );
}
