/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicScimListScimTokensRequest = {};

/** @internal */
export type TextqlRpcPublicScimListScimTokensRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicScimListScimTokensRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicScimListScimTokensRequest$Outbound,
    TextqlRpcPublicScimListScimTokensRequest
  > = z.object({});

export function textqlRpcPublicScimListScimTokensRequestToJSON(
  textqlRpcPublicScimListScimTokensRequest:
    TextqlRpcPublicScimListScimTokensRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicScimListScimTokensRequest$outboundSchema.parse(
      textqlRpcPublicScimListScimTokensRequest,
    ),
  );
}
