/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest = {};

/** @internal */
export type TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest$Outbound =
  {};

/** @internal */
export const TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest$Outbound,
    TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest
  > = z.object({});

export function textqlRpcPublicMetricsExportGetMetricsExportConfigRequestToJSON(
  textqlRpcPublicMetricsExportGetMetricsExportConfigRequest:
    TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicMetricsExportGetMetricsExportConfigRequest$outboundSchema
      .parse(textqlRpcPublicMetricsExportGetMetricsExportConfigRequest),
  );
}
