/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesOntologyAnaConfig,
  TextqlRpcPublicPatchesOntologyAnaConfig$inboundSchema,
} from "./textql-rpc-public-patches-ontology-ana-config.js";

export type TextqlRpcPublicPatchesUpsertOntologyAnaConfigResponse = {
  config?: TextqlRpcPublicPatchesOntologyAnaConfig | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesUpsertOntologyAnaConfigResponse$inboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicPatchesUpsertOntologyAnaConfigResponse,
    unknown
  > = z.object({
    config: types.optional(
      TextqlRpcPublicPatchesOntologyAnaConfig$inboundSchema,
    ),
  });

export function textqlRpcPublicPatchesUpsertOntologyAnaConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesUpsertOntologyAnaConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesUpsertOntologyAnaConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesUpsertOntologyAnaConfigResponse' from JSON`,
  );
}
