/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPatchesMigratedOntologyNoun = {
  nounId?: string | undefined;
  nounName?: string | undefined;
  filePath?: string | undefined;
  created?: boolean | undefined;
  skipped?: boolean | undefined;
  skipReason?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesMigratedOntologyNoun$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesMigratedOntologyNoun, unknown> = z.object(
    {
      nounId: types.optional(types.string()),
      nounName: types.optional(types.string()),
      filePath: types.optional(types.string()),
      created: types.optional(types.boolean()),
      skipped: types.optional(types.boolean()),
      skipReason: z.optional(z.nullable(types.string())),
    },
  );

export function textqlRpcPublicPatchesMigratedOntologyNounFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesMigratedOntologyNoun,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesMigratedOntologyNoun$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesMigratedOntologyNoun' from JSON`,
  );
}
