/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * TemplateOptions configures the one-shot TYPE_TEMPLATE paradigm.
 */
export type TextqlRpcPublicParadigmTemplateOptions = {
  /**
   * capture_tools selects which capture-cell tool ids the paradigm exposes to
   *
   * @remarks
   *  the model (e.g. "generate_example_queries"). Empty means expose every
   *  registered capture cell.
   */
  captureTools?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicParadigmTemplateOptions$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicParadigmTemplateOptions, unknown> = z.object({
    captureTools: types.optional(z.array(types.string())),
  });
/** @internal */
export type TextqlRpcPublicParadigmTemplateOptions$Outbound = {
  captureTools?: Array<string> | undefined;
};

/** @internal */
export const TextqlRpcPublicParadigmTemplateOptions$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicParadigmTemplateOptions$Outbound,
    TextqlRpcPublicParadigmTemplateOptions
  > = z.object({
    captureTools: z.optional(z.array(z.string())),
  });

export function textqlRpcPublicParadigmTemplateOptionsToJSON(
  textqlRpcPublicParadigmTemplateOptions:
    TextqlRpcPublicParadigmTemplateOptions,
): string {
  return JSON.stringify(
    TextqlRpcPublicParadigmTemplateOptions$outboundSchema.parse(
      textqlRpcPublicParadigmTemplateOptions,
    ),
  );
}
export function textqlRpcPublicParadigmTemplateOptionsFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicParadigmTemplateOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicParadigmTemplateOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicParadigmTemplateOptions' from JSON`,
  );
}
