/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicPatchesPatch,
  TextqlRpcPublicPatchesPatch$inboundSchema,
} from "./textql-rpc-public-patches-patch.js";
import {
  TextqlRpcPublicPatchesSkippedConfigExport,
  TextqlRpcPublicPatchesSkippedConfigExport$inboundSchema,
} from "./textql-rpc-public-patches-skipped-config-export.js";

export type TextqlRpcPublicPatchesSaveAllObjectsAsConfigResponse = {
  patch?: TextqlRpcPublicPatchesPatch | undefined;
  /**
   * Library-relative paths of the config files in the patch.
   */
  filePaths?: Array<string> | undefined;
  skipped?: Array<TextqlRpcPublicPatchesSkippedConfigExport> | undefined;
  /**
   * Objects excluded up front because a config file already manages them.
   */
  alreadyManagedCount?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesSaveAllObjectsAsConfigResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesSaveAllObjectsAsConfigResponse, unknown> =
    z.object({
      patch: types.optional(TextqlRpcPublicPatchesPatch$inboundSchema),
      filePaths: types.optional(z.array(types.string())),
      skipped: types.optional(
        z.array(TextqlRpcPublicPatchesSkippedConfigExport$inboundSchema),
      ),
      alreadyManagedCount: types.optional(types.number()),
    });

export function textqlRpcPublicPatchesSaveAllObjectsAsConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesSaveAllObjectsAsConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesSaveAllObjectsAsConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesSaveAllObjectsAsConfigResponse' from JSON`,
  );
}
