/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicRbacWhoAmIRequest = {};

/** @internal */
export type TextqlRpcPublicRbacWhoAmIRequest$Outbound = {};

/** @internal */
export const TextqlRpcPublicRbacWhoAmIRequest$outboundSchema: z.ZodMiniType<
  TextqlRpcPublicRbacWhoAmIRequest$Outbound,
  TextqlRpcPublicRbacWhoAmIRequest
> = z.object({});

export function textqlRpcPublicRbacWhoAmIRequestToJSON(
  textqlRpcPublicRbacWhoAmIRequest: TextqlRpcPublicRbacWhoAmIRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicRbacWhoAmIRequest$outboundSchema.parse(
      textqlRpcPublicRbacWhoAmIRequest,
    ),
  );
}
