/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TextqlRpcPublicConnectorDeleteConnectorRequest = {
  connectorId?: number | undefined;
};

/** @internal */
export type TextqlRpcPublicConnectorDeleteConnectorRequest$Outbound = {
  connectorId?: number | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorDeleteConnectorRequest$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicConnectorDeleteConnectorRequest$Outbound,
    TextqlRpcPublicConnectorDeleteConnectorRequest
  > = z.object({
    connectorId: z.optional(z.int()),
  });

export function textqlRpcPublicConnectorDeleteConnectorRequestToJSON(
  textqlRpcPublicConnectorDeleteConnectorRequest:
    TextqlRpcPublicConnectorDeleteConnectorRequest,
): string {
  return JSON.stringify(
    TextqlRpcPublicConnectorDeleteConnectorRequest$outboundSchema.parse(
      textqlRpcPublicConnectorDeleteConnectorRequest,
    ),
  );
}
