/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicParadigmResearchOptions = {
  connectorIds?: Array<number> | undefined;
  backgroundColor?: string | null | undefined;
  logo?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicParadigmResearchOptions$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicParadigmResearchOptions, unknown> = z.object({
    connectorIds: types.optional(z.array(types.number())),
    backgroundColor: z.optional(z.nullable(types.string())),
    logo: z.optional(z.nullable(types.string())),
  });
/** @internal */
export type TextqlRpcPublicParadigmResearchOptions$Outbound = {
  connectorIds?: Array<number> | undefined;
  backgroundColor?: string | null | undefined;
  logo?: string | null | undefined;
};

/** @internal */
export const TextqlRpcPublicParadigmResearchOptions$outboundSchema:
  z.ZodMiniType<
    TextqlRpcPublicParadigmResearchOptions$Outbound,
    TextqlRpcPublicParadigmResearchOptions
  > = z.object({
    connectorIds: z.optional(z.array(z.int())),
    backgroundColor: z.optional(z.nullable(z.string())),
    logo: z.optional(z.nullable(z.string())),
  });

export function textqlRpcPublicParadigmResearchOptionsToJSON(
  textqlRpcPublicParadigmResearchOptions:
    TextqlRpcPublicParadigmResearchOptions,
): string {
  return JSON.stringify(
    TextqlRpcPublicParadigmResearchOptions$outboundSchema.parse(
      textqlRpcPublicParadigmResearchOptions,
    ),
  );
}
export function textqlRpcPublicParadigmResearchOptionsFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicParadigmResearchOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicParadigmResearchOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicParadigmResearchOptions' from JSON`,
  );
}
