/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TextqlRpcPublicRbacRolePermissionAction = {
  RoleActionUnspecified: "ROLE_ACTION_UNSPECIFIED",
  RoleActionRead: "ROLE_ACTION_READ",
  RoleActionWrite: "ROLE_ACTION_WRITE",
} as const;
export type TextqlRpcPublicRbacRolePermissionAction = OpenEnum<
  typeof TextqlRpcPublicRbacRolePermissionAction
>;

/** @internal */
export const TextqlRpcPublicRbacRolePermissionAction$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicRbacRolePermissionAction, unknown> = openEnums
    .inboundSchema(TextqlRpcPublicRbacRolePermissionAction);
/** @internal */
export const TextqlRpcPublicRbacRolePermissionAction$outboundSchema:
  z.ZodMiniType<string, TextqlRpcPublicRbacRolePermissionAction> = openEnums
    .outboundSchema(TextqlRpcPublicRbacRolePermissionAction);
