/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  TextqlRpcPublicConnectorPrimaryKeyMetadata,
  TextqlRpcPublicConnectorPrimaryKeyMetadata$inboundSchema,
} from "./textql-rpc-public-connector-primary-key-metadata.js";
import {
  TextqlRpcPublicConnectorQueryResult,
  TextqlRpcPublicConnectorQueryResult$inboundSchema,
} from "./textql-rpc-public-connector-query-result.js";

export type TextqlRpcPublicConnectorConnectorTable = {
  tableDatabase?: string | undefined;
  tableSchema?: string | undefined;
  tableName?: string | undefined;
  preview?: TextqlRpcPublicConnectorQueryResult | undefined;
  primaryKeys?: Array<TextqlRpcPublicConnectorPrimaryKeyMetadata> | undefined;
  tableType?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicConnectorConnectorTable$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicConnectorConnectorTable, unknown> = z.object({
    tableDatabase: types.optional(types.string()),
    tableSchema: types.optional(types.string()),
    tableName: types.optional(types.string()),
    preview: types.optional(TextqlRpcPublicConnectorQueryResult$inboundSchema),
    primaryKeys: types.optional(
      z.array(TextqlRpcPublicConnectorPrimaryKeyMetadata$inboundSchema),
    ),
    tableType: types.optional(types.string()),
  });

export function textqlRpcPublicConnectorConnectorTableFromJSON(
  jsonString: string,
): SafeParseResult<TextqlRpcPublicConnectorConnectorTable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicConnectorConnectorTable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextqlRpcPublicConnectorConnectorTable' from JSON`,
  );
}
