/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type TextqlRpcPublicPatchesGetRawPatchResponse = {
  rawPatch?: string | undefined;
};

/** @internal */
export const TextqlRpcPublicPatchesGetRawPatchResponse$inboundSchema:
  z.ZodMiniType<TextqlRpcPublicPatchesGetRawPatchResponse, unknown> = z.object({
    rawPatch: types.optional(types.string()),
  });

export function textqlRpcPublicPatchesGetRawPatchResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TextqlRpcPublicPatchesGetRawPatchResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TextqlRpcPublicPatchesGetRawPatchResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TextqlRpcPublicPatchesGetRawPatchResponse' from JSON`,
  );
}
