import {
	ArrowDown,
	ArrowUp,
	ArrowUpDown,
	Calendar,
	Columns3,
	Download,
	Hash,
	ListFilter,
	Search,
	ToggleLeft,
	Type,
	X
} from 'lucide-react';
import {
	memo,
	useCallback,
	useDeferredValue,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
	type KeyboardEvent as ReactKeyboardEvent,
	type PointerEvent as ReactPointerEvent,
	type ReactNode
} from 'react';

import { NEW_BTN } from '@ui/components/pageStyles';
import { cx } from '@ui/lib/cx';
import { toast } from '@ui/primitives';

import {
	columnLetter,
	filterActive,
	filterRows,
	formatStat,
	isNull,
	ROW_LIMIT,
	sortedRows,
	summarize,
	toCsv,
	type ColumnStats,
	type ColumnType,
	type Filter,
	type Sheet,
	type Sort
} from '../lib/csv';
import { ColumnFilterPopover, Popover } from './ColumnFilter';

const ROW_H = 30;
const HEAD_H = 56;
const GUTTER_W = 56;
const OVERSCAN = 12;
const MIN_COL_W = 72;

const TYPE_ICON: Record<ColumnType, typeof Hash> = {
	number: Hash,
	date: Calendar,
	boolean: ToggleLeft,
	text: Type
};

function initialWidths(sheet: Sheet): number[] {
	return sheet.columns.map((name, c) => {
		let longest = 0;
		const step = Math.max(1, Math.floor(sheet.rows.length / 200));
		for (let r = 0; r < sheet.rows.length; r += step) {
			longest = Math.max(longest, (sheet.rows[r]![c] ?? '').length);
		}
		// The header also carries a letter, a type icon, and sort/filter controls.
		const header = name.length * 8.2 + 100;
		return Math.round(Math.min(340, Math.max(MIN_COL_W + 24, header, longest * 7.4 + 28)));
	});
}

function describeFilter(filter: Filter, type: ColumnType): string {
	switch (filter.kind) {
		case 'range': {
			const lo = filter.min !== undefined ? formatStat(filter.min, type, true) : '';
			const hi = filter.max !== undefined ? formatStat(filter.max, type, true) : '';
			if (lo && hi) return `${lo} – ${hi}`;
			return lo ? `≥ ${lo}` : `≤ ${hi}`;
		}
		case 'values': {
			const [first] = filter.values;
			return filter.values.size === 1 ? `= ${first || '(empty)'}` : `${filter.values.size} values`;
		}
		case 'contains':
			return `contains “${filter.text.trim()}”`;
		case 'nulls':
			return filter.only === 'empty' ? 'is empty' : 'not empty';
	}
}

function Highlight({ text, needle }: { text: string; needle: string }) {
	if (!needle) return <>{text}</>;
	const at = text.toLowerCase().indexOf(needle);
	if (at === -1) return <>{text}</>;
	return (
		<>
			{text.slice(0, at)}
			<mark className="rounded-[3px] bg-[color-mix(in_srgb,var(--color-accent)_26%,transparent)] text-ink">
				{text.slice(at, at + needle.length)}
			</mark>
			{text.slice(at + needle.length)}
		</>
	);
}

/** A column's shape at a glance: a histogram, or the share of its top values. */
const Sparkline = memo(function Sparkline({ stats, rows }: { stats: ColumnStats; rows: number }) {
	if (stats.bins && stats.bins.length > 1) {
		const peak = Math.max(...stats.bins.map((b) => b.count), 1);
		return (
			<div className="flex h-3.5 items-end gap-px" aria-hidden>
				{stats.bins.map((bin, i) => (
					<span
						key={i}
						className="min-w-0 flex-1 rounded-t-[1.5px] bg-[color-mix(in_srgb,var(--color-accent)_55%,transparent)]"
						style={{ height: `${Math.max(8, (bin.count / peak) * 100)}%` }}
					/>
				))}
			</div>
		);
	}
	const filled = Math.max(1, rows - stats.nulls);
	const shown = stats.top.slice(0, 4);
	const other = filled - shown.reduce((sum, v) => sum + v.count, 0);
	return (
		<div className="flex h-1.5 overflow-hidden rounded-[2px] bg-line/60" aria-hidden>
			{shown.map((v, i) => (
				<span
					key={v.value}
					className="h-full border-r border-elevate last:border-r-0"
					style={{
						width: `${(v.count / filled) * 100}%`,
						background: `color-mix(in srgb, var(--color-accent) ${78 - i * 16}%, transparent)`
					}}
				/>
			))}
			{other > 0 && <span className="h-full flex-1" />}
		</div>
	);
});

type Props = {
	sheet: Sheet;
	name: string;
	/** Extra toolbar content on the left, e.g. a "generated by" badge. */
	badge?: ReactNode;
};

type Selection = { row: number; col: number } | null;

/** Keyed by the parent on the sheet, so a new sheet starts with fresh view state. */
export const Spreadsheet = memo(function Spreadsheet({ sheet, name, badge }: Props) {
	const [filters, setFilters] = useState<Map<number, Filter>>(() => new Map());
	const [search, setSearch] = useState('');
	const [sort, setSort] = useState<Sort>(null);
	const [hidden, setHidden] = useState<Set<number>>(() => new Set());
	const [widths, setWidths] = useState<number[]>(() => initialWidths(sheet));
	const [selection, setSelection] = useState<Selection>(null);
	const [filterFor, setFilterFor] = useState<{ col: number; rect: DOMRect } | null>(null);
	const [columnsMenu, setColumnsMenu] = useState<DOMRect | null>(null);
	/** The first row in view; scrolling within a row does not re-render. */
	const [topRow, setTopRow] = useState(0);
	const [viewport, setViewport] = useState(600);
	const gridRef = useRef<HTMLDivElement | null>(null);

	useLayoutEffect(() => {
		const el = gridRef.current;
		if (!el) return;
		const observer = new ResizeObserver(() => setViewport(el.clientHeight));
		observer.observe(el);
		setViewport(el.clientHeight);
		return () => observer.disconnect();
	}, []);

	// Typing stays responsive on large sheets: filtering trails the input.
	const deferredSearch = useDeferredValue(search);
	const deferredFilters = useDeferredValue(filters);
	const needle = deferredSearch.trim().toLowerCase();
	const sorted = useMemo(() => sortedRows(sheet, sort), [sheet, sort]);
	const order = useMemo(
		() => filterRows(sheet, sorted, deferredFilters, deferredSearch),
		[sheet, sorted, deferredFilters, deferredSearch]
	);
	const shownColumns = useMemo(
		() => sheet.columns.map((_, c) => c).filter((c) => !hidden.has(c)),
		[sheet, hidden]
	);
	const totalWidth = GUTTER_W + shownColumns.reduce((sum, c) => sum + widths[c]!, 0);

	const first = Math.max(0, topRow - OVERSCAN);
	const last = Math.min(order.length, topRow + Math.ceil(viewport / ROW_H) + 1 + OVERSCAN);

	const activeFilters = [...filters];

	const setFilter = useCallback((col: number, filter: Filter | undefined) => {
		setFilters((current) => {
			const next = new Map(current);
			if (filter && filterActive(filter)) next.set(col, filter);
			else next.delete(col);
			return next;
		});
		setSelection(null);
	}, []);

	function cycleSort(col: number) {
		setSort((current) => {
			if (!current || current.column !== col) return { column: col, dir: 'asc' };
			if (current.dir === 'asc') return { column: col, dir: 'desc' };
			return null;
		});
	}

	function startResize(event: ReactPointerEvent, col: number) {
		event.preventDefault();
		event.stopPropagation();
		const startX = event.clientX;
		const startW = widths[col]!;
		const move = (e: PointerEvent) => {
			const w = Math.max(MIN_COL_W, startW + e.clientX - startX);
			setWidths((current) => current.map((value, i) => (i === col ? w : value)));
		};
		const up = () => {
			window.removeEventListener('pointermove', move);
			window.removeEventListener('pointerup', up);
			document.body.style.cursor = '';
		};
		document.body.style.cursor = 'col-resize';
		window.addEventListener('pointermove', move);
		window.addEventListener('pointerup', up);
	}

	function scrollIntoView(row: number, col: number) {
		const el = gridRef.current;
		if (!el) return;
		const top = row * ROW_H;
		const bodyH = el.clientHeight - HEAD_H;
		if (top < el.scrollTop) el.scrollTop = top;
		else if (top + ROW_H > el.scrollTop + bodyH) el.scrollTop = top + ROW_H - bodyH;
		const idx = shownColumns.indexOf(col);
		let left = GUTTER_W;
		for (let i = 0; i < idx; i++) left += widths[shownColumns[i]!]!;
		const right = left + widths[col]!;
		if (left - GUTTER_W < el.scrollLeft) el.scrollLeft = left - GUTTER_W;
		else if (right > el.scrollLeft + el.clientWidth) el.scrollLeft = right - el.clientWidth;
	}

	function onKeyDown(event: ReactKeyboardEvent) {
		if (!selection) return;
		const idx = shownColumns.indexOf(selection.col);
		let { row } = selection;
		let colIdx = idx;
		switch (event.key) {
			case 'ArrowDown':
				row = Math.min(order.length - 1, row + 1);
				break;
			case 'ArrowUp':
				row = Math.max(0, row - 1);
				break;
			case 'ArrowRight':
			case 'Tab':
				colIdx = Math.min(shownColumns.length - 1, idx + 1);
				break;
			case 'ArrowLeft':
				colIdx = Math.max(0, idx - 1);
				break;
			case 'PageDown':
				row = Math.min(order.length - 1, row + Math.floor(viewport / ROW_H) - 1);
				break;
			case 'PageUp':
				row = Math.max(0, row - Math.floor(viewport / ROW_H) + 1);
				break;
			case 'Home':
				colIdx = 0;
				if (event.metaKey || event.ctrlKey) row = 0;
				break;
			case 'End':
				colIdx = shownColumns.length - 1;
				if (event.metaKey || event.ctrlKey) row = order.length - 1;
				break;
			case 'Escape':
				setSelection(null);
				return;
			case 'c':
				if (event.metaKey || event.ctrlKey) {
					const value = sheet.rows[order[row]!]![selection.col] ?? '';
					void navigator.clipboard?.writeText(value).then(() => toast.success('Copied cell'));
				}
				return;
			default:
				return;
		}
		event.preventDefault();
		const col = shownColumns[colIdx]!;
		setSelection({ row, col });
		scrollIntoView(row, col);
	}

	function download() {
		const blob = new Blob([toCsv(sheet, order, shownColumns)], { type: 'text/csv' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		const filtered = order.length !== sheet.rows.length || hidden.size > 0;
		a.href = url;
		a.download = filtered ? name.replace(/(\.\w+)?$/, '.filtered.csv') : name;
		a.click();
		URL.revokeObjectURL(url);
	}

	const selectedCol = selection?.col ?? null;
	const selectedStats = useMemo(() => {
		if (selectedCol === null) return null;
		const type = sheet.stats[selectedCol]!.type;
		const numeric = sheet.numeric[selectedCol];
		if (type === 'number' && numeric) {
			const { sum, count, min, max } = summarize(numeric, order);
			const some = count > 0;
			return [
				['Sum', formatStat(sum, type)],
				['Avg', formatStat(some ? sum / count : undefined, type)],
				['Min', formatStat(some ? min : undefined, type)],
				['Max', formatStat(some ? max : undefined, type)],
				['Count', count.toLocaleString()]
			];
		}
		const seen = new Set<string>();
		let empty = 0;
		for (const r of order) {
			const v = sheet.rows[r]![selectedCol] ?? '';
			if (isNull(v)) empty++;
			else seen.add(v);
		}
		return [
			['Distinct', seen.size.toLocaleString()],
			['Empty', empty.toLocaleString()],
			['Count', (order.length - empty).toLocaleString()]
		];
	}, [selectedCol, sheet, order]);

	const selectedValue = selection ? (sheet.rows[order[selection.row]!]?.[selection.col] ?? '') : '';

	return (
		<div className="flex h-full min-h-0 flex-col">
			<div className="flex min-h-11 flex-wrap items-center gap-1.5 border-b border-line/80 px-3 py-2">
				{badge}
				<label className="relative flex h-7 w-[220px] items-center max-[700px]:w-[160px]">
					<Search size={13} className="pointer-events-none absolute left-2 text-muted" />
					<input
						value={search}
						onChange={(e) => {
							setSearch(e.target.value);
							setSelection(null);
						}}
						placeholder="Search all cells"
						className="h-full w-full rounded-sm border-0 bg-fill pr-6 pl-7 text-[12px] text-ink outline-0 placeholder:text-muted focus:bg-elevate focus:shadow-[inset_0_0_0_1px_var(--color-accent)]"
					/>
					{search && (
						<button
							type="button"
							aria-label="Clear search"
							className="absolute right-1 inline-flex size-5 cursor-pointer items-center justify-center rounded-xs border-0 bg-transparent text-muted hover:text-ink"
							onClick={() => setSearch('')}
						>
							<X size={12} />
						</button>
					)}
				</label>
				{activeFilters.map(([col, filter]) => {
					const Icon = TYPE_ICON[sheet.stats[col]!.type];
					return (
						<span
							key={col}
							className="inline-flex h-7 max-w-[260px] items-center gap-1 rounded-sm bg-[color-mix(in_srgb,var(--color-accent)_12%,transparent)] pr-1 pl-2 text-[11.5px] text-text-2"
						>
							<button
								type="button"
								className="inline-flex min-w-0 cursor-pointer items-center gap-1 border-0 bg-transparent p-0 text-inherit"
								onClick={(e) =>
									setFilterFor({ col, rect: e.currentTarget.getBoundingClientRect() })
								}
							>
								<Icon size={11} className="shrink-0 text-accent" />
								<span className="font-medium">{sheet.columns[col]}</span>
								<span className="truncate text-text-3">
									{describeFilter(filter, sheet.stats[col]!.type)}
								</span>
							</button>
							<button
								type="button"
								aria-label={`Remove filter on ${sheet.columns[col]}`}
								className="inline-flex size-5 cursor-pointer items-center justify-center rounded-xs border-0 bg-transparent text-muted hover:bg-elevate hover:text-ink"
								onClick={() => setFilter(col, undefined)}
							>
								<X size={11} />
							</button>
						</span>
					);
				})}
				{activeFilters.length > 1 && (
					<button
						type="button"
						className="h-7 cursor-pointer rounded-sm border-0 bg-transparent px-2 text-[12px] text-muted hover:text-ink"
						onClick={() => setFilters(new Map())}
					>
						Clear all
					</button>
				)}
				<div className="ml-auto flex items-center gap-1.5">
					{sheet.truncated && (
						<span
							className="rounded-sm bg-fill px-2 py-1 text-[11px] text-text-3"
							title="Large files load their first rows; the agent still sees the whole file."
						>
							From the first {ROW_LIMIT.toLocaleString()} rows
						</span>
					)}
					<span className="px-1 font-mono text-[11px] text-muted tabular-nums">
						{order.length === sheet.rows.length
							? `${sheet.rows.length.toLocaleString()} rows`
							: `${order.length.toLocaleString()} of ${sheet.rows.length.toLocaleString()} rows`}
						{' · '}
						{shownColumns.length}
						{hidden.size ? `/${sheet.columns.length}` : ''} cols
					</span>
					<button
						type="button"
						className={NEW_BTN}
						onClick={(e) => setColumnsMenu(e.currentTarget.getBoundingClientRect())}
					>
						<Columns3 size={13} />
						Columns
					</button>
					<button type="button" className={NEW_BTN} onClick={download}>
						<Download size={13} />
						Download
					</button>
				</div>
			</div>

			<div
				ref={gridRef}
				tabIndex={0}
				role="grid"
				aria-rowcount={order.length}
				aria-colcount={shownColumns.length}
				aria-label={name}
				className="relative min-h-0 flex-1 overflow-auto bg-elevate outline-0"
				onScroll={(e) => {
					setTopRow(Math.floor(e.currentTarget.scrollTop / ROW_H));
					if (filterFor) setFilterFor(null);
				}}
				onKeyDown={onKeyDown}
			>
				<div style={{ width: totalWidth, minWidth: '100%' }}>
					<div
						role="row"
						className="sticky top-0 z-[3] flex border-b border-line bg-[color-mix(in_srgb,var(--color-fill)_70%,var(--color-elevate))]"
						style={{ height: HEAD_H }}
					>
						<div
							className="sticky left-0 z-[4] flex shrink-0 items-end justify-end border-r border-line bg-inherit px-2 pb-1.5 font-mono text-[10px] text-muted"
							style={{ width: GUTTER_W }}
						>
							#
						</div>
						{shownColumns.map((col) => {
							const stats = sheet.stats[col]!;
							const Icon = TYPE_ICON[stats.type];
							const sorted = sort?.column === col ? sort.dir : null;
							const filtered = filters.has(col);
							const isSelected = selection?.col === col;
							return (
								<div
									key={col}
									role="columnheader"
									aria-sort={sorted === 'asc' ? 'ascending' : sorted === 'desc' ? 'descending' : 'none'}
									className={cx(
										'group/head relative flex shrink-0 flex-col justify-between border-r border-line/80 px-2 pt-1.5 pb-1.5',
										isSelected && 'bg-[color-mix(in_srgb,var(--color-accent)_9%,transparent)]'
									)}
									style={{ width: widths[col] }}
								>
									<div className="flex min-w-0 items-center gap-1">
										<span className="font-mono text-[9.5px] text-muted/80">{columnLetter(col)}</span>
										<Icon size={11} className="shrink-0 text-muted" aria-label={stats.type} />
										<button
											type="button"
											title={`${sheet.columns[col]} — click to sort`}
											className="min-w-0 flex-1 cursor-pointer truncate border-0 bg-transparent p-0 text-left text-[12px] font-semibold text-text-strong"
											onClick={() => cycleSort(col)}
										>
											{sheet.columns[col]}
										</button>
										<span
											className={cx(
												'inline-flex size-5 shrink-0 items-center justify-center text-muted',
												!sorted && 'opacity-0 group-hover/head:opacity-60'
											)}
											aria-hidden
										>
											{sorted === 'asc' ? (
												<ArrowUp size={12} className="text-accent" />
											) : sorted === 'desc' ? (
												<ArrowDown size={12} className="text-accent" />
											) : (
												<ArrowUpDown size={12} />
											)}
										</span>
										<button
											type="button"
											aria-label={`Filter ${sheet.columns[col]}`}
											className={cx(
												'inline-flex size-5 shrink-0 cursor-pointer items-center justify-center rounded-xs border-0 transition-opacity',
												filtered
													? 'bg-accent text-white opacity-100'
													: 'bg-transparent text-muted opacity-0 group-hover/head:opacity-100 hover:bg-line/70 hover:text-ink focus-visible:opacity-100'
											)}
											onClick={(e) =>
												setFilterFor({ col, rect: e.currentTarget.getBoundingClientRect() })
											}
										>
											<ListFilter size={12} />
										</button>
									</div>
									<Sparkline stats={stats} rows={sheet.rows.length} />
									<span
										role="separator"
										aria-orientation="vertical"
										className="absolute top-0 -right-[3px] z-[1] h-full w-[6px] cursor-col-resize hover:bg-accent/40"
										onPointerDown={(e) => startResize(e, col)}
										onDoubleClick={() =>
											setWidths((current) => {
												const fresh = initialWidths(sheet);
												return current.map((w, i) => (i === col ? fresh[col]! : w));
											})
										}
									/>
								</div>
							);
						})}
					</div>

					<div className="relative" style={{ height: order.length * ROW_H }}>
						{order.slice(first, last).map((r, i) => {
							const pos = first + i;
							const rowSelected = selection?.row === pos;
							return (
								<div
									key={r}
									role="row"
									aria-rowindex={pos + 1}
									className={cx(
										'group/row absolute left-0 flex w-full',
										pos % 2 === 1 && 'bg-[color-mix(in_srgb,var(--color-fill)_45%,transparent)]'
									)}
									style={{ top: pos * ROW_H, height: ROW_H }}
								>
									<div
										className={cx(
											'sticky left-0 z-[2] flex shrink-0 items-center justify-end border-r border-b border-line/70 px-2 font-mono text-[10.5px] tabular-nums',
											rowSelected
												? 'bg-[color-mix(in_srgb,var(--color-accent)_14%,var(--color-elevate))] text-accent'
												: 'bg-[color-mix(in_srgb,var(--color-fill)_70%,var(--color-elevate))] text-muted'
										)}
										style={{ width: GUTTER_W }}
									>
										{r + 1}
									</div>
									{shownColumns.map((col) => {
										const value = sheet.rows[r]![col] ?? '';
										const type = sheet.stats[col]!.type;
										const empty = isNull(value);
										const selected = rowSelected && selection?.col === col;
										return (
											<div
												key={col}
												role="gridcell"
												aria-selected={selected}
												title={value.length > 24 ? value : undefined}
												className={cx(
													'relative flex shrink-0 items-center overflow-hidden border-r border-b border-line/55 px-2 font-mono text-[12px] whitespace-nowrap group-hover/row:bg-ink/[0.035]',
													type === 'number' && 'justify-end tabular-nums',
													type === 'boolean' && 'justify-center',
													empty ? 'text-muted/70 italic' : 'text-text-strong',
													selected &&
														'z-[1] bg-[color-mix(in_srgb,var(--color-accent)_8%,transparent)] shadow-[inset_0_0_0_2px_var(--color-accent)]'
												)}
												style={{ width: widths[col] }}
												onMouseDown={() => setSelection({ row: pos, col })}
											>
												<span className="truncate">
													{empty ? (value.trim() ? value : '∅') : <Highlight text={value} needle={needle} />}
												</span>
											</div>
										);
									})}
								</div>
							);
						})}
					</div>
				</div>

				{order.length === 0 && (
					<div className="pointer-events-none absolute inset-x-0 top-[96px] flex flex-col items-center gap-1 text-center">
						<p className="m-0 text-[13px] font-medium text-ink">No rows match</p>
						<p className="m-0 text-[12px] text-muted">Loosen a filter or clear the search.</p>
					</div>
				)}
			</div>

			<div className="flex h-8 shrink-0 items-center gap-3 overflow-hidden border-t border-line/80 bg-paper px-3 font-mono text-[11px] text-muted">
				{selection ? (
					<>
						<span className="shrink-0 rounded-xs bg-fill px-1.5 py-px text-text-2">
							{columnLetter(selection.col)}
							{order[selection.row]! + 2}
						</span>
						<span className="shrink-0 font-sans font-medium text-text-2">
							{sheet.columns[selection.col]}
						</span>
						<span className="min-w-0 truncate text-ink">{selectedValue || '∅'}</span>
						<span className="ml-auto flex shrink-0 gap-3">
							{selectedStats?.map(([label, value]) => (
								<span key={label}>
									{label} <span className="text-text-2 tabular-nums">{value}</span>
								</span>
							))}
						</span>
					</>
				) : (
					<span>Click a cell to inspect · ↑↓←→ to move · ⌘C to copy · drag header edges to resize</span>
				)}
			</div>

			{filterFor && (
				<ColumnFilterPopover
					anchor={filterFor.rect}
					name={sheet.columns[filterFor.col]!}
					stats={sheet.stats[filterFor.col]!}
					filter={filters.get(filterFor.col)}
					sort={sort?.column === filterFor.col ? sort.dir : null}
					onChange={(f) => setFilter(filterFor.col, f)}
					onSort={(dir) => setSort(dir ? { column: filterFor.col, dir } : null)}
					onHide={() => {
						setHidden((current) => new Set(current).add(filterFor.col));
						setFilterFor(null);
					}}
					onClose={() => setFilterFor(null)}
				/>
			)}

			{columnsMenu && (
				<Popover anchor={columnsMenu} align="right" width={240} onClose={() => setColumnsMenu(null)}>
					<div className="flex items-center justify-between px-2.5 pt-2 pb-1">
						<span className="text-[11px] font-semibold tracking-[0.05em] text-muted uppercase">Columns</span>
						<button
							type="button"
							className="cursor-pointer border-0 bg-transparent p-0 text-[11.5px] text-accent"
							onClick={() => setHidden(new Set())}
						>
							Show all
						</button>
					</div>
					<div className="max-h-[320px] overflow-y-auto p-1">
						{sheet.columns.map((column, c) => {
							const Icon = TYPE_ICON[sheet.stats[c]!.type];
							return (
								<label
									key={c}
									className="flex cursor-pointer items-center gap-2 rounded-[7px] px-2 py-1.5 text-[12.5px] text-text-strong hover:bg-fill"
								>
									<input
										type="checkbox"
										className="accent-[var(--color-accent)]"
										checked={!hidden.has(c)}
										onChange={() =>
											setHidden((current) => {
												const next = new Set(current);
												if (next.has(c)) next.delete(c);
												else if (next.size < sheet.columns.length - 1) next.add(c);
												return next;
											})
										}
									/>
									<Icon size={12} className="shrink-0 text-muted" />
									<span className="truncate">{column}</span>
								</label>
							);
						})}
					</div>
				</Popover>
			)}
		</div>
	);
});
